const kobe6Products = [
    {
        "name": "Nike Kobe 6 Protro Mambacita Sweet 16",
        "price": 150,
        "type": "kobe",
        "description": "`Nike honors the legacy of Kobe Bryant and his daughter Gigi with the Kobe 6 Protro 'Mambacita Sweet Sixteen.' Black snake scales across the upper reference the Laker legend's Black Mamba alter ego",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Protro-Mamba-Forever-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Black/White-Metallic Gold",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Protro Grinch (2020)",
        "price": 155,
        "description": "Originally released in 2010 for a Christmas Day collection",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Protro-Grinch-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Green Apple/Volt-Crimson-Black",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Kobe 6 Protro Playoff Pack White Del Sol",
        "price": 150,
        "description": "Nike Kobe 6",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Kobe-6-Protro-Playoff-Pack-White-Del-Sol-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "White/Neutral Grey-Del Sol-Black",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Protro Challenge Red All-Star (2021)",
        "price": 155,
        "description": "Nike Kobe 6",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Protro-Challenge-Red-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Challenge Red/Black-White",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe Protro 6 Think Pink",
        "price": 200,
        "description": "Nike Kobe 6",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-Protro-6-Think-Pink-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Pinkfire/Metallic Silver/White",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Black Del Sol",
        "price": 150,
        "description": "The inaugural colorway of the Zoom Kobe 6",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Black-Del-Sol-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Black/Del Sol-Dark Grey-White",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Protro Grinch (2020) (Includes Storyteller Collection Books)",
        "price": 308,
        "description": "Originally released in 2010 for a Christmas Day collection",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Protro-Grinch-2020-Includes-Storyteller-Collection-Books.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Green Apple/Volt-Crimson-Black",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Protro EYBL",
        "price": 225,
        "description": "Nike Kobe 6",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Protro-EYBL.png645063261",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Black/Lavender Mint",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Grinch (2010)",
        "price": 150,
        "description": "Released on Christmas Day 2010",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Grinch-Christmas-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Lime Green/Varsity Red/Black",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Prelude (All-Star MVP)",
        "price": 160,
        "description": "Part of an eight-shoe capsule leading up to the release of the Kobe 9",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Prelude-All-Star-MVP-Product.png610080200",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Cannon/Volt-Purple Venom-Turf Orange",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Supreme Rice",
        "price": 150,
        "description": "The Zoom Kobe 6 Supreme 'Rice' pays tribute to Harlem's Rice High School",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Supreme-Rice-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Moss Green/Green Apple-Black",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 ASG East LA",
        "price": 155,
        "description": "One of four colorways for the 2011 NBA All-Star Game",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-ASG-East-LA.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Drenched Blue/Metallic Silver-Sport Red",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Helicopter",
        "price": 150,
        "description": "Also known as the 'Glass Blue",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Glass-Helicopter.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Dark Grey/Vibrant Yellow/Glass Blue/TTL",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 BHM (2011)",
        "price": 150,
        "description": "The Zoom Kobe 6 features a metallic gold accents representing championship accomplishments",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-BHM-2011.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Black/Metallic Gold",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Black Mamba Collection Fade to Black",
        "price": 160,
        "description": "The Zoom Kobe 6 ‘FTB’ dropped in 2016 as part of Nike’s massive ‘Fade to Black’ collection",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Fade-To-Black-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "River Rock/River Rock",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 ASG West Challenge Red",
        "price": 155,
        "description": "This Zoom Kobe 6 All-Star dropped in 2011 as part of four-piece Kobe 6 pack celebrating Los Angeles",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-ASG-West-Challenge-Red.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Challenge Red/White-Black",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 ASG Hollywood 3D",
        "price": 155,
        "description": "The Zoom Kobe 6 All-Star '3D/Hollywood' was one of three Kobe 6 All-Star models released for the 2011 All-Star Game",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-ASG-Hollywood-3D-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Dark Grey/Chlorine Blue-Daring Red",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Dark Knight",
        "price": 150,
        "description": "The Nike Zoom Kobe 6 ‘Dark Knight’ dropped in 2011",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Dark-Knight-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Dark Grey/Blue Glow-Black-Challenge Red",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Zoom Kobe VI 3D Lakers",
        "price": 150,
        "description": "Giving the nod to the only franchise Kobe Bryant played for",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Zoom-Kobe-VI-3D-Lakers.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "White/Club Purple-Del Sol",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Lower Merion Aces",
        "price": 150,
        "description": "The Zoom Kobe 6 ‘Lower Merion Aces’ features a grey midsole",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Lower-Merion-Aces-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Platinum/Varsity Crimson-Cool Grey (Lower Merion HS)",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Supreme Chaos",
        "price": 150,
        "description": "The 2011 Zoom Kobe 6 Supreme ‘Chaos’ features a color scheme inspired by the Joker",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Supreme-Chaos-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Ink/Volt-Dark Grey-White",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 FC Barcelona Home",
        "price": 150,
        "description": "A character driven shoe based on the athlete’s Black Mamba persona",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-FC-Barcelona-Home-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Storm Blue/Yellow Ochre-Stream Red",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Kay Yow Think Pink",
        "price": 150,
        "description": "The Zoom Kobe 6 ‘Think Pink’ launched in 2011 as part of a larger footwear collection dedicated to raising awareness for the Kay Yow Cancer Fund. Kobe Bryant’s signature shoe is dressed in a snakeskin-textured upper dressed in Pinkfire",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Kay-Yow-Think-Pink.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Pink Fire I/White-Metallic",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 China 3D",
        "price": 150,
        "description": "The Zoom Kobe 6 'China' gives the nod to Kobe Bryant's following in China. The shoe's snakeskin-textured upper is finished Metallic Pewter",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-China-3D-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Pewter/Ink-White-Crimson",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Imperial Purple",
        "price": 150,
        "description": "The Zoom Kobe 6 'Imperial Purple' emerges with a Los Angeles Lakers-style colorway. Featuring Imperial Purple throughout its upper",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Imperial-Purple.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Imperial Purple / Del Sol",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Draft Day",
        "price": 150,
        "description": "The Zoom Kobe 6 'Draft Day' gives the nod to the famous 1996 draft day trade that saw the Charlotte Hornets send the 13th overall pick to the Los Angeles Lakers in exchange for Vlade Divac. The Lakers would take Kobe Bryant",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Draft-Day.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "White/Varsity Purple-Photo Blue Black",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Concord",
        "price": 150,
        "description": "The Zoom Kobe 6 'Concord' dresses Kobe Bryant's sixth signature shoe in a colorway more familiar to Jordan Brand. The shoe's white snakeskin-textured upper is accented by Concord on the stabilizing heel counter and lining. The signature color takes over the Zoom midsole",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Concord-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "White/Black-Neutral Grey-Concord",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Lightbulb",
        "price": 150,
        "description": "Debuting on the feet of Kobe Bryant during the 2011 NBA Playoffs",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Lightbulb.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Del Sol/Black-Tour Yellow-White",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Steelers",
        "price": 150,
        "description": "The Zoom Kobe 6 'Steelers' emerges with a Pittsburgh Steelers-style colorway. The white and grey upper features a 3D snakeskin texture",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Steelers.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "White/Black-Del Sol-Dark Grey",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 FC Barcelona Mango",
        "price": 150,
        "description": "The Zoom Kobe 6 'Barcelona' is inspired by FC Barcelona",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-FC-Barcelona-Mango.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Bright Mango/Black-White",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Metallic Silver Metallic Silver White",
        "price": 150,
        "description": "The Nike Zoom Kobe 6 takes on a Metallic Silver finish",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Metallic-Silver.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Silver/White",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Italian Camo",
        "price": 150,
        "description": "The Zoom Kobe 6 'Camo' features a utilitarian colorway that works a camo pattern into its signature polyurethane snakeskin-textured upper. The tongue and Swoosh branding add contrasting crimson",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Italian-Camo.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Black/Khaki-Olive-Crimson",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Lakers Home",
        "price": 150,
        "description": "Kobe Bryant's sixth signature shoe with Nike gets a colorway inspired by the only NBA team he ever played for. The Zoom Kobe 6 'Lakers Home' features a white synthetic upper with snakeskin detailing throughout the forefoot and quarter panel",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Lakers-Home.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "White/Del Sol-Neutral Grey-Concord",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Blue Camo",
        "price": 150,
        "description": "The Zoom Kobe 6 'Blue Camo' features a colorful Photo Blue camo pattern throughout its snakeskin-textured upper. Supported by a padded tongue and collar",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Blue-Camo-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Photo Blue/White-Black-Volt",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 ASG Orange County Sunset",
        "price": 155,
        "description": "In celebration of the 2011 NBA All-Star Game",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-ASG-Orange-County-OC-Sunset-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Orange Peel/Cannon-Black",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Purple Gradient",
        "price": 150,
        "description": "The Zoom Kobe 6 'Purple Gradient' features a two-tone polyurethane upper that transitions from Concord to black. A metallic silver Swoosh accents the snakeskin-textured look",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Purple-Gradient.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Black/Metallic Silver-Concord-White",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Zoom Kobe 6 White Del Sol",
        "price": 155,
        "description": "nike-zoom-kobe-6-white-del-sol",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Zoom-Kobe-6-White-Del-Sol.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "White/Black/Del Sol",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Lakers Gradient Away",
        "price": 150,
        "description": "Featuring a Los Angeles Lakers colorway",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Lakers-Gradient-Away.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Club Purple/White-Del Sol",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Team Bank Colorways",
        "price": 150,
        "description": "The Zoom Kobe 6 'Duke' features a color scheme that recalls the Duke Blue Devils",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Team-Bank.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Various",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Urban Camo",
        "price": 150,
        "description": "The Zoom Kobe 6 ‘Urban Camo’ complements the low-top’s snakeskin texture with a subtle camouflage print made up of brown",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Urban-Camo.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Concord/Grey Black-White",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 TB Midnight Navy",
        "price": 155,
        "description": "nike-kobe-6-tb-midnight-navy",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-TB-Midnight-Navy.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Midnight Navy/White/Metallic Silver",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Bred",
        "price": 150,
        "description": "The Zoom Kobe 6 ‘Bred’ showcases a familiar color scheme",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Bred-Product.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Black/White-Varsity Red",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Protro Chaos",
        "price": 160,
        "description": "nike-kobe-6-protro-chaos",
        "currency": "USD",
        "image": "https://stockx-assets.imgix.net/media/Product-Placeholder-Default-20210415.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Ink/Dark Grey-White-Volt",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Grey Black",
        "price": 150,
        "description": " complemented by a black Swoosh and heel counter. A white tongue contrasts the look",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Grey-Black.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Medium Grey/Black-White",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Black Gold (PS)",
        "price": 150,
        "description": "[object Object]",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-VI-Black-Gold-PS.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Black/Gold/Grey",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Protro Think Pink",
        "price": 155,
        "description": "Nike Kobe 6",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Protro-Think-Pink.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Pinkfire/Metallic Silver-White",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Grinch (GS)",
        "price": 150,
        "description": "Officially named the 'Green Mamba",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Grinch-GS.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Volt/Black-Green Apple-Crimson",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 USC PE",
        "price": 150,
        "description": "[object Object]",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-USC-PE.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "White/Gym Red/Yellow",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    },
    {
        "name": "Nike Kobe 6 Prelude All-Star MVP (GS)",
        "price": 150,
        "description": "Nike Kobe 6",
        "currency": "USD",
        "image": "./public/assets/images/products/kobe6/Nike-Kobe-6-Prelude-All-Star-MVP-GS.png",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Cannon/Volt-Turf Orange-Neo Turquoise",
        "url": "nike-kobe-6-protro-mambacita-sweet-16",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mambacita-sweet-16",
        },
    }
];

module.exports = kobe6Products