export const ROUTES = {
  HOME: "/",
  PRODUCT: `/products`,
  SHOP: "/shop",
  KOBE: "/kobe",
  KOBE5: "/kobe/kobe-5",
  KOBE6: "/kobe/kobe-6",
  JA1: "/ja1",
  CHECKOUT: "/checkout",
  CONTACT: "/contact-us",
  TERMS: "/terms",
  POLICY: "/privacy",
  FAQ: "/faq",
  FORGET_PASSWORD: "/forget-password",
  ACCOUNT: "/my-account",
  ORDERS: "/my-account/orders",
  ACCOUNT_DETAILS: "/my-account/account-details",
  CHANGE_PASSWORD: "/my-account/change-password",
  SHOPS: "/shops",
  LOGIN: "/signin",
  SIGN_UP: "/signup",
  SEARCH: "/search",
  COLLECTIONS: "/collections",
  CATEGORY: "/category",
  ORDER: "/order",
};
