const balenciagaProducts = [
    {
        "_id": "64c3566b3848d8e72c7972dd",
        "name": "Balenciaga Track Trainer White (Women's)",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "517",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Trainer-White-W-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-trainer-white-w",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-trainer-white-w",
        "make": "Balenciaga Track Trainer",
        "retailPrice": "895",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2022-03-21"
    },
    // {
    //     "_id": "64c3566b3848d8e72c7972de",
    //     "name": "Balenciaga Track White Orange",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "745",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-White-Orange-Product.jpg",
    //     "description": "The Balenciaga Track White Orange is a highly sought-after sneaker that was released on September 3, 2018, with a retail price of $1120. This shoe features a white and orange colorway that is eye-catching and unique. The upper is made of a combination of mesh, nylon, and rubber materials, which provide both durability and breathability. The shoe also features a chunky sole that is both comfortable and stylish. One of the standout features of the Balenciaga Track White Orange is its attention to detail. The shoe features a complex layering system that creates a dynamic and textured look. The orange accents on the shoe add a pop of color that makes it stand out from other sneakers on the market. Something we love about the Balenciaga Track White Orange is its ability to blend fashion and function seamlessly. The shoe is not only stylish but also comfortable and practical for everyday wear. Our experts think that the best features of this shoe are its unique design and attention to detail. If you're looking for a statement piece that will turn heads, the Balenciaga Track White Orange is the perfect choice.",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-white-orange",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-white-orange",
    //     "make": "Balenciaga Track",
    //     "retailPrice": "1120",
    //     "releaseDate": "2018-09-03"
    // },
    {
        "_id": "64c3566b3848d8e72c7972df",
        "name": "Balenciaga Track Leather Free White Silver Multi",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "575",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Leather-Free-White-Silver-Multi-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-leather-free-white-silver-multi",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-leather-free-white-silver-multi",
        "make": "Balenciaga Track",
        "retailPrice": "1050",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2022-09-09"
    },
    // {
    //     "_id": "64c3566b3848d8e72c7972e0",
    //     "name": "Balenciaga Track Yellow",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "690",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Yellow-Product.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-yellow",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-yellow",
    //     "make": "Balenciaga Track",
    //     "retailPrice": "1050",
    //     "metadata_": {
    //         "brand": "balenciaga",
    //         "category": "balenciaga",
    //         "collection": "balenciaga",
    //         "slug": "balenciaga-track-led-black"
    //     },
    //     "releaseDate": "2018-09-03"
    // },
    // {
    //     "_id": "64c3566b3848d8e72c7972e1",
    //     "name": "Balenciaga Track Trainer Red",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "731",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Trainer-Red-Product.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-trainer-red",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-trainer-red",
    //     "make": "Balenciaga Track Trainer",
    //     "retailPrice": "895",
    //     "metadata_": {
    //         "brand": "balenciaga",
    //         "category": "balenciaga",
    //         "collection": "balenciaga",
    //         "slug": "balenciaga-track-led-black"
    //     },
    //     "releaseDate": "2022-03-22"
    // },
    {
        "_id": "64c3566b3848d8e72c7972e2",
        "name": "Balenciaga Track Runners Blue",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Runners-Blue.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-runners-blue",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-runners-blue",
        "make": "Balenciaga Track Runners",
        "retailPrice": "895",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2019-09-01"
    },
    // {
    //     "_id": "64c3566b3848d8e72c7972e3",
    //     "name": "Balenciaga Track White",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "706",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-White-Product.png",
    //     "description": "The Balenciaga Track White is a highly sought-after sneaker that combines style and functionality. Released in 2019, this shoe features a white mesh upper with synthetic overlays in shades of grey and black. The chunky sole is made of rubber and features a unique tread pattern that provides excellent traction on any surface. One of the standout features of the Balenciaga Track White is its attention to detail. The shoe is crafted from high-quality materials, including mesh, synthetic leather, and rubber, which ensures durability and longevity. The shoe's design is also highly functional, with a padded tongue and collar that provide comfort and support. At a retail price of $835, the Balenciaga Track White is a premium sneaker that is worth the investment. Its sleek design and high-quality construction make it a versatile shoe that can be worn with a variety of outfits. Something we love about Balenciaga Track White is its ability to seamlessly blend style and functionality. Our experts think that the shoe's attention to detail and high-quality materials are its best features. Whether you're hitting the gym or running errands, the Balenciaga Track White is a shoe that will keep you looking and feeling great.",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-white",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-white",
    //     "make": "Balenciaga Track",
    //     "retailPrice": "835",
    //     "metadata_": {
    //         "brand": "balenciaga",
    //         "category": "balenciaga",
    //         "collection": "balenciaga",
    //         "slug": "balenciaga-track-led-black"
    //     },
    //     "releaseDate": "2019-01-01"
    // },
    // {
    //     "_id": "64c3566b3848d8e72c7972e4",
    //     "name": "Balenciaga Track LED Black",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "988",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-LED-Black.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-led-black",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-led-black",
    //     "make": "Balenciaga Track LED",
    //     "retailPrice": "1305",
    //     "releaseDate": "2021-11-04"
    // },
    // {
    //     "_id": "64c3566b3848d8e72c7972e5",
    //     "name": "Balenciaga Track Black 2021",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "870",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Black-2021-Product.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-black-2021",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-black-2021",
    //     "make": "Balenciaga Track",
    //     "retailPrice": "975",
    //     "releaseDate": "2021-03-31"
    // },
    {
        "_id": "64c3566b3848d8e72c7972e6",
        "name": "Balenciaga Track 2 Black",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "721",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-2-Black-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-2-black",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-2-black",
        "make": "Balenciaga Track 2",
        "retailPrice": "755",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2019-06-25"
    },
    {
        "_id": "64c3566b3848d8e72c7972e7",
        "name": "Balenciaga Track Clear Sole White (Women's)",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "413",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Clear-Sole-White-W.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-clear-sole-white-w",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-clear-sole-white-w",
        "make": "Balenciaga Track Clear Sole",
        "retailPrice": "995",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2022-03-21"
    },
    // {
    //     "_id": "64c3566b3848d8e72c7972e8",
    //     "name": "Balenciaga Track Black Neon Yellow",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "835",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Black-Neon-Yellow-Product.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-black-neon-yellow",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-black-neon-yellow",
    //     "make": "Balenciaga Track",
    //     "retailPrice": "1050",
    //     "metadata_": {
    //         "brand": "balenciaga",
    //         "category": "balenciaga",
    //         "collection": "balenciaga",
    //         "slug": "balenciaga-track-led-black"
    //     },
    //     "releaseDate": "2022-04-21"
    // },
    {
        "_id": "64c3566b3848d8e72c7972e9",
        "name": "Balenciaga Track Faded Black",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "707",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Faded-Black-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-faded-black",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-faded-black",
        "make": "Balenciaga Track Faded",
        "retailPrice": "1090",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2021-10-25"
    },
    // {
    //     "_id": "64c3566b3848d8e72c7972ea",
    //     "name": "Balenciaga Track White Blue",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "676",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-White-Blue-Product.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-white-blue",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-white-blue",
    //     "make": "Balenciaga Track",
    //     "retailPrice": "995",
    //     "metadata_": {
    //         "brand": "balenciaga",
    //         "category": "balenciaga",
    //         "collection": "balenciaga",
    //         "slug": "balenciaga-track-led-black"
    //     },
    //     "releaseDate": "2018-09-24"
    // },
    // {
    //     "_id": "64c3566b3848d8e72c7972eb",
    //     "name": "Balenciaga Track White Blue Green",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "602",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-White-Blue-Green-Product.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-white-blue-green",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-white-blue-green",
    //     "make": "Balenciaga Track",
    //     "retailPrice": "995",
    //     "metadata_": {
    //         "brand": "balenciaga",
    //         "category": "balenciaga",
    //         "collection": "balenciaga",
    //         "slug": "balenciaga-track-led-black"
    //     },
    //     "releaseDate": "2022-03-22"
    // },
    {
        "_id": "64c3566b3848d8e72c7972ec",
        "name": "Balenciaga Track Runners Blue (Women's)",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "707",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Runners-Blue-W-Product.jpg",
        "description": "The Balenciaga Track Runners Blue W is a stylish and functional sneaker that is perfect for any fashion-forward individual. These sneakers were released on September 24th, 2018, and have since become a popular choice for those who want to make a statement with their footwear. The Balenciaga Track Runners Blue W is made from a combination of materials, including mesh, nylon, and rubber. This combination of materials provides a comfortable and durable shoe that can withstand the wear and tear of everyday use. The blue colorway is eye-catching and adds a pop of color to any outfit. One of the standout features of the Balenciaga Track Runners Blue W is the unique design. The layered construction and chunky sole give the shoe a futuristic look that is both stylish and functional. The shoe also features a lace-up closure and a padded tongue and collar for added comfort. Something we love about Balenciaga Track Runners Blue W is the attention to detail. The shoe is meticulously crafted and features high-quality materials that are built to last. Our experts think the best features of the Balenciaga Track Runners Blue W are the unique design and comfortable fit. Overall, we love the Balenciaga Track Runners Blue W for its style, comfort, and durability.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-runners-blue-w",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-runners-blue-w",
        "make": "Balenciaga Track",
        "retailPrice": "895",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2018-09-24"
    },
    // {
    //     "_id": "64c3566b3848d8e72c7972ed",
    //     "name": "Balenciaga Track Faded Beige",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "684",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Faded-Beige.png",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-faded-beige",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-faded-beige",
    //     "make": "Balenciaga Track Faded",
    //     "retailPrice": "1090",
    //     "metadata_": {
    //         "brand": "balenciaga",
    //         "category": "balenciaga",
    //         "collection": "balenciaga",
    //         "slug": "balenciaga-track-led-black"
    //     },
    //     "releaseDate": "2021-10-25"
    // },
    // {
    //     "_id": "64c3566b3848d8e72c7972ee",
    //     "name": "Balenciaga Track Black Grey Red",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "724",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Black-Grey-Red-Product.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-black-grey-red",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-black-grey-red",
    //     "make": "Balenciaga Track",
    //     "retailPrice": "895",
    //     "metadata_": {
    //         "brand": "balenciaga",
    //         "category": "balenciaga",
    //         "collection": "balenciaga",
    //         "slug": "balenciaga-track-led-black"
    //     },
    //     "releaseDate": "2019-01-01"
    // },
    {
        "_id": "64c3566b3848d8e72c7972ef",
        "name": "Balenciaga Track Trainer Pink (Women's)",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "884",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Trainer-Pink-W-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-trainer-pink-w",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-trainer-pink-w",
        "make": "Balenciaga Track Trainer",
        "retailPrice": "895",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2022-03-21"
    },
    {
        "_id": "64c3566b3848d8e72c7972f0",
        "name": "Balenciaga Track Clear Sole Black",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "707",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Clear-Sole-Black-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-clear-sole-black",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-clear-sole-black",
        "make": "Balenciaga Track Clear Sole",
        "retailPrice": "995",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2021-10-25"
    },
    {
        "_id": "64c3566b3848d8e72c7972f1",
        "name": "Balenciaga Track Sandal Beige (Women's)",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "430",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Sandal-Beige-W.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-sandal-beige-w",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-sandal-beige-w",
        "make": "Balenciaga Track Sandal",
        "retailPrice": "995",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2020-03-20"
    },
    {
        "_id": "64c3566b3848d8e72c7972f2",
        "name": "Balenciaga Track Hike Black Black White",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "575",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Hike-Black-Black-White.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-hike-black-black-white",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-hike-black-black-white",
        "make": "Balenciaga Track Hike",
        "retailPrice": "1050",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2022-08-04"
    },
    {
        "_id": "64c3566b3848d8e72c7972f3",
        "name": "Balenciaga Track Mule Black (Women's)",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "733",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Mule-Black-W.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-mule-black-w",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-mule-black-w",
        "make": "Balenciaga Track Mule",
        "retailPrice": "895",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2022-03-21"
    },
    {
        "_id": "64c3566b3848d8e72c7972f4",
        "name": "Balenciaga Track.2 White (Women's)",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "635",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track2-White-W-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track2-white-w",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track2-white-w",
        "make": "Balenciaga Track.2",
        "retailPrice": "895",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2019-10-02"
    },
    // {
    //     "_id": "64c3566b3848d8e72c7972f5",
    //     "name": "Balenciaga Track Triple Grey",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "654",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Grey.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-triple-grey",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-triple-grey",
    //     "make": "Balenciaga Track",
    //     "retailPrice": "895",
    //     "metadata_": {
    //         "brand": "balenciaga",
    //         "category": "balenciaga",
    //         "collection": "balenciaga",
    //         "slug": "balenciaga-track-led-black"
    //     },
    //     "releaseDate": "2022-03-21"
    // },
    {
        "_id": "64c3566b3848d8e72c7972f6",
        "name": "Balenciaga Track Black Green",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "720",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Dark-Grey-Green-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-dark-grey-green",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-dark-grey-green",
        "make": "Balenciaga Track",
        "retailPrice": "975",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2020-11-25"
    },
    {
        "_id": "64c3566b3848d8e72c7972f7",
        "name": "Balenciaga Track Sandal Black",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "445",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Sandal-Black-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-sandal-black",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-sandal-black",
        "make": "Balenciaga Track Sandal",
        "retailPrice": "595",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2018-09-24"
    },
    {
        "_id": "64c3566b3848d8e72c7972f8",
        "name": "Balenciaga Track.2 Clear Sole Black",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "550",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track2-Clear-Sole-Black-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track2-clear-sole-black",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track2-clear-sole-black",
        "make": "Balenciaga Track.2 Clear Sole",
        "retailPrice": "1090",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2022-03-21"
    },
    // {
    //     "_id": "64c3566b3848d8e72c7972f9",
    //     "name": "Balenciaga Track LED Gray",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "968",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-LED-Gray.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-led-gray",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-led-gray",
    //     "make": "Balenciaga Track LED",
    //     "retailPrice": "1350",
    //     "metadata_": {
    //         "brand": "balenciaga",
    //         "category": "balenciaga",
    //         "collection": "balenciaga",
    //         "slug": "balenciaga-track-led-black"
    //     },
    //     "releaseDate": "2018-09-24"
    // },
    {
        "_id": "64c3566b3848d8e72c7972fa",
        "name": "Balenciaga Track 2 Blue Red",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "516",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-2-Blue-Red-Product.png",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-2-blue-red",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-2-blue-red",
        "make": "Balenciaga Track 2",
        "retailPrice": "755",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2019-06-25"
    },
    {
        "_id": "64c3566b3848d8e72c7972fb",
        "name": "Balenciaga Track Sandal Black (Women's)",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "523",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Sandal-Black-W.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-sandal-black-w",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-sandal-black-w",
        "make": "Balenciaga Track Sandal",
        "retailPrice": "595",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2020-03-30"
    },
    {
        "_id": "64c3566b3848d8e72c7972fc",
        "name": "Balenciaga Track Clear Sole Red",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "653",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Clear-Sole-Red.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-clear-sole-red",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-clear-sole-red",
        "make": "Balenciaga Track Clear Sole",
        "retailPrice": "995",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2018-09-24"
    },
    {
        "_id": "64c3566b3848d8e72c7972fd",
        "name": "Balenciaga Track Clear Sole Gray",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "600",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Clear-Sole-Gray-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-clear-sole-gray",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-clear-sole-gray",
        "make": "Balenciaga Track Clear Sole",
        "retailPrice": "1050",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2022-03-21"
    },
    {
        "_id": "64c3566b3848d8e72c7972fe",
        "name": "Balenciaga Track.2 Blue Grey",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "916",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track2-Blue-Grey-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track2-blue-grey",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track2-blue-grey",
        "make": "Balenciaga Track.2",
        "retailPrice": "1050",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2022-03-21"
    },
    {
        "_id": "64c3566b3848d8e72c7972ff",
        "name": "Balenciaga Track Sandal Fake Fur Black",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "419",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Sandal-Fake-Fur-Black-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-sandal-fake-fur-black",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-sandal-fake-fur-black",
        "make": "Balenciaga Track Sandal Fake Fur",
        "retailPrice": "1050",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2018-09-24"
    },
    {
        "_id": "64c3566b3848d8e72c797300",
        "name": "Balenciaga Track Hike White White Black",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "563",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Hike-White-White-Black-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-hike-white-white-black",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-hike-white-white-black",
        "make": "Balenciaga Track Hike",
        "retailPrice": "1100",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2022-08-04"
    },
    {
        "_id": "64c3566b3848d8e72c797301",
        "name": "Balenciaga Track Mule Black White",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "654",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Mule-Black-White.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-mule-black-white",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-mule-black-white",
        "make": "Balenciaga Track Mule",
        "retailPrice": "950",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2018-09-24"
    },
    {
        "_id": "64c3566b3848d8e72c797302",
        "name": "Balenciaga Track.2 Black Grey Red",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "788",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track2-Black-Grey-Red.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track2-black-grey-red",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track2-black-grey-red",
        "make": "Balenciaga Track.2",
        "retailPrice": "895",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2020-01-16"
    },
    {
        "_id": "64c3566b3848d8e72c797303",
        "name": "Balenciaga Track 2.0 Pink",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "857",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-20-Pink.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-20-pink",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-20-pink",
        "make": "Balenciaga Track 2.0",
        "retailPrice": "1050",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2022-04-10"
    },
    // {
    //     "_id": "64c3566b3848d8e72c797304",
    //     "name": "Balenciaga Track Clear Sole White/Black (Women's)",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "690",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Clear-Sole-White-Black-W.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-clear-sole-white-black-w",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-clear-sole-white-black-w",
    //     "make": "Balenciaga Track Clear Sole",
    //     "retailPrice": "1090",
    //     "metadata_": {
    //         "brand": "balenciaga",
    //         "category": "balenciaga",
    //         "collection": "balenciaga",
    //         "slug": "balenciaga-track-led-black"
    //     },
    //     "releaseDate": "2018-09-24"
    // },
    {
        "_id": "64c3566b3848d8e72c797305",
        "name": "Balenciaga Track Clear Sole Black (Women's)",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "720",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Clear-Sole-Black-W.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-clear-sole-black-w",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-clear-sole-black-w",
        "make": "Balenciaga Track Clear Sole",
        "retailPrice": "995",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2018-09-24"
    },
    // {
    //     "_id": "64c3566b3848d8e72c797306",
    //     "name": "Balenciaga Track Faded Pink (Women's)",
    //     "brand": "Balenciaga",
    //     "lowestResellPrice.stockX": "675",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Faded-Pink-W.png",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "balenciaga-track-faded-pink-w",
    //     "resellLinks.stockX": "https://stockx.com/balenciaga-track-faded-pink-w",
    //     "make": "Balenciaga Track Faded",
    //     "retailPrice": "1090",
    //     "metadata_": {
    //         "brand": "balenciaga",
    //         "category": "balenciaga",
    //         "collection": "balenciaga",
    //         "slug": "balenciaga-track-led-black"
    //     },
    //     "releaseDate": "2021-09-16"
    // },
    {
        "_id": "64c3566b3848d8e72c797307",
        "name": "Balenciaga Track Pastel (Women's)",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "844",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Pastel-W.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-pastel-w",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-pastel-w",
        "make": "Balenciaga Track",
        "retailPrice": "1050",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2018-09-24"
    },
    {
        "_id": "64c3566b3848d8e72c797308",
        "name": "Balenciaga Track.2 Black White",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "742",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track2-Black-White.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track2-black-white",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track2-black-white",
        "make": "Balenciaga Track.2",
        "retailPrice": "975",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-black"
        },
        "releaseDate": "2020-09-11"
    }
]

module.exports = balenciagaProducts;