const cloudburst = [
    // {
    //     "_id": "64cefc861f6b94bc194e5a7f",
    //     "name": "Prada Cloudbust Thunder Knit Black",
    //     "brand": "Prada",
    //     "lowestResellPrice.stockX": "810",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Thunder-Knit-Black-Product.jpg",
    //     "description": "",
    //     "url": "prada-cloudbust-thunder-knit-black",
    //     "resellLinks.stockX": "https://stockx.com/prada-cloudbust-thunder-knit-black",
    //     "make": "Prada Cloudbust Thunder Knit",
    //     "retailPrice": "895",
    //     "releaseDate": "2019-08-01"
    // },
    {
        "_id": "64cefc861f6b94bc194e5a80",
        "name": "Prada Cloudbust Air Technical Fabric Black",
        "brand": "Prada",
        "lowestResellPrice.stockX": "785",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Air-Technical-Fabric-Black.jpg",
        "description": "",
        "url": "prada-cloudbust-air-technical-fabric-black",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-air-technical-fabric-black",
        "make": "Prada Cloudbust Air Technical Fabric",
        "retailPrice": "1070",
        "releaseDate": "2023-01-25"
    },
    {
        "_id": "64cefc861f6b94bc194e5a81",
        "name": "Prada Cloudbust Thunder Sandal Black Nylon",
        "brand": "Prada",
        "lowestResellPrice.stockX": "475",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Thunder-Sandal-Black-Nylon.jpg",
        "description": "",
        "url": "prada-cloudbust-thunder-sandal-black-nylon",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-thunder-sandal-black-nylon",
        "make": "Prada Cloudbust Thunder Sandal",
        "retailPrice": "683",
        "releaseDate": "2022-09-06"
    },
    // {
    //     "_id": "64cefc861f6b94bc194e5a82",
    //     "name": "Prada Cloudbust Red",
    //     "brand": "Prada",
    //     "lowestResellPrice.stockX": "",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Red.jpg",
    //     "description": "",
    //     "url": "prada-cloudbust-red",
    //     "resellLinks.stockX": "https://stockx.com/prada-cloudbust-red",
    //     "make": "Prada Cloudbust",
    //     "retailPrice": "745",
    //     "releaseDate": "2019-12-13"
    // },
    {
        "_id": "64cefc861f6b94bc194e5a83",
        "name": "Prada Cloudbust Thunder Sneakers Black (Women's)",
        "brand": "Prada",
        "lowestResellPrice.stockX": "525",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Thunder-Sneakers-Black-W-Product.jpg",
        "description": "",
        "url": "prada-cloudbust-thunder-sneakers-black-w",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-thunder-sneakers-black-w",
        "make": "Prada Cloudbust Thunder Sneakers",
        "retailPrice": "1200",
        "releaseDate": "2022-12-20"
    },
    {
        "_id": "64cefc861f6b94bc194e5a84",
        "name": "Prada Cloudbust Thunder Knit White",
        "brand": "Prada",
        "lowestResellPrice.stockX": "971",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Thunder-Knit-White.jpg",
        "description": "",
        "url": "prada-cloudbust-thunder-knit-white",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-thunder-knit-white",
        "make": "Prada Cloudbust Thunder Knit",
        "retailPrice": "895",
        "releaseDate": "2019-10-04"
    },
    {
        "_id": "64cefc861f6b94bc194e5a85",
        "name": "Prada Cloudbust Neon Green",
        "brand": "Prada",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Neon-Green.jpg",
        "description": "",
        "url": "prada-cloudbust-neon-green",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-neon-green",
        "make": "Prada Cloudbust",
        "retailPrice": "745",
        "releaseDate": "2019-05-31"
    },
    {
        "_id": "64cefc861f6b94bc194e5a86",
        "name": "Prada Cloudbust Black",
        "brand": "Prada",
        "lowestResellPrice.stockX": "500",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Black.jpg",
        "description": "",
        "url": "prada-cloudbust-black",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-black",
        "make": "Prada Cloudbust",
        "retailPrice": "745",
        "releaseDate": "2020-02-17"
    },
    {
        "_id": "64cefc861f6b94bc194e5a87",
        "name": "Prada Cloudbust Thunder Low Top Black",
        "brand": "Prada",
        "lowestResellPrice.stockX": "1037",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Thunder-Low-Top-Black.jpg",
        "description": "",
        "url": "prada-cloudbust-thunder-low-top-black",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-thunder-low-top-black",
        "make": "Prada Cloudbust Thunder Low Top",
        "retailPrice": "1200",
        "releaseDate": ""
    },
    {
        "_id": "64cefc861f6b94bc194e5a88",
        "name": "Prada Cloudbust Thunder High Top Black",
        "brand": "Prada",
        "lowestResellPrice.stockX": "902",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Thunder-High-Top-Black.jpg",
        "description": "",
        "url": "prada-cloudbust-thunder-high-top-black",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-thunder-high-top-black",
        "make": "Prada Cloudbust Thunder High Top",
        "retailPrice": "",
        "releaseDate": ""
    },
    {
        "_id": "64cefc861f6b94bc194e5a89",
        "name": "Prada Cloudbust Thunder Knit Green",
        "brand": "Prada",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Thunder-Knit-Green.jpg",
        "description": "",
        "url": "prada-cloudbust-thunder-knit-green",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-thunder-knit-green",
        "make": "Prada Cloudbust Thunder Knit",
        "retailPrice": "895",
        "releaseDate": "2019-10-04"
    },
    {
        "_id": "64cefc861f6b94bc194e5a8a",
        "name": "Prada Cloudbust Thunder Technical Fabric Navy/Black",
        "brand": "Prada",
        "lowestResellPrice.stockX": "1614",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Thunder-Technical-Fabric-Navy-Black.jpg",
        "description": "",
        "url": "prada-cloudbust-thunder-technical-fabric-navy-black",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-thunder-technical-fabric-navy-black",
        "make": "Prada Cloudbust Thunder Technical Fabric",
        "retailPrice": "1140",
        "releaseDate": ""
    },
    {
        "_id": "64cefc861f6b94bc194e5a8b",
        "name": "Prada Cloudbust Thunder Sneakers White (Women's)",
        "brand": "Prada",
        "lowestResellPrice.stockX": "897",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Thunder-Sneakers-White-W.jpg",
        "description": "",
        "url": "prada-cloudbust-thunder-sneakers-white-w",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-thunder-sneakers-white-w",
        "make": "Prada Cloudbust Thunder Sneakers",
        "retailPrice": "",
        "releaseDate": ""
    },
    {
        "_id": "64cefc861f6b94bc194e5a8c",
        "name": "Prada Cloudbust Thunder Technical Fabric Silver",
        "brand": "Prada",
        "lowestResellPrice.stockX": "1614",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Thunder-Technical-Fabric-Silver.jpg",
        "description": "",
        "url": "prada-cloudbust-thunder-technical-fabric-silver",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-thunder-technical-fabric-silver",
        "make": "Prada Cloudbust Thunder Technical Fabric",
        "retailPrice": "1140",
        "releaseDate": "2022-05-04"
    },
    {
        "_id": "64cefc861f6b94bc194e5a8d",
        "name": "Prada Cloudbust Neon Yellow",
        "brand": "Prada",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Cloudbust-Neon-Yellow.jpg",
        "description": "",
        "url": "prada-cloudbust-neon-yellow",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-neon-yellow",
        "make": "Prada Cloudbust",
        "retailPrice": "745",
        "releaseDate": "2020-02-05"
    },
    {
        "_id": "64cefc861f6b94bc194e5a8e",
        "name": "Prada Cloudbust Neon Orange",
        "brand": "Prada",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Neon-Orange.jpg",
        "description": "",
        "url": "prada-cloudbust-neon-orange",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-neon-orange",
        "make": "Prada Cloudbust",
        "retailPrice": "745",
        "releaseDate": ""
    },
    {
        "_id": "64cefc861f6b94bc194e5a8f",
        "name": "Prada Cloudbust Neon Blue",
        "brand": "Prada",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Neon-Blue.jpg",
        "description": "",
        "url": "prada-cloudbust-neon-blue",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-neon-blue",
        "make": "Prada Cloudbust",
        "retailPrice": "745",
        "releaseDate": "2019-05-31"
    },
    {
        "_id": "64cefc861f6b94bc194e5a90",
        "name": "Prada Cloudbust Black Orange",
        "brand": "Prada",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/prada/Prada-Cloudbust-Black-Orange-Product.jpg",
        "description": "",
        "url": "prada-cloudbust-black-orange",
        "resellLinks.stockX": "https://stockx.com/prada-cloudbust-black-orange",
        "make": "Prada Cloudbust",
        "retailPrice": "745",
        "releaseDate": "2019-05-31"
    }
]

module.exports = cloudburst