
const dior = [
    {
        "_id": "64d1d981bb458ee5a1494ef1",
        "name": "Dior B22 Orange Olive Olive Black",
        "brand": "Dior",
        "lowestResellPrice.stockX": "880",
        "image": "https://images.stockx.com/images/Dior-B22-Orange-Olive-Olive-Black.jpg",
        "description": "",
        "url": "dior-b22-orange-olive-olive-black",
        "resellLinks.stockX": "https://stockx.com/dior-b22-orange-olive-olive-black",
        "make": "Dior B22",
        "retailPrice": "1300",
        "releaseDate": "2022-03-08"
    },
    {
        "_id": "64d1d981bb458ee5a1494ef2",
        "name": "Dior B22 White Blue",
        "brand": "Dior",
        "lowestResellPrice.stockX": "800",
        "image": "https://images.stockx.com/images/Dior-B22-White-Blue-Product.jpg",
        "description": "",
        "url": "dior-b22-white-blue",
        "resellLinks.stockX": "https://stockx.com/dior-b22-white-blue",
        "make": "Dior B22",
        "retailPrice": "1100",
        "releaseDate": "2021-03-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494ef3",
        "name": "Dior B22 Black",
        "brand": "Dior",
        "lowestResellPrice.stockX": "978",
        "image": "https://images.stockx.com/images/Dior-B22-Black-Product.jpg",
        "description": "",
        "url": "dior-b22-black",
        "resellLinks.stockX": "https://stockx.com/dior-b22-black",
        "make": "Dior B22",
        "retailPrice": "1100",
        "releaseDate": "2018-04-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494ef4",
        "name": "Dior B22 Olive/Blue",
        "brand": "Dior",
        "lowestResellPrice.stockX": "1000",
        "image": "https://images.stockx.com/images/Dior-B22-Olive-Blue-Product.jpg",
        "description": "",
        "url": "dior-b22-olive-blue",
        "resellLinks.stockX": "https://stockx.com/dior-b22-olive-blue",
        "make": "Dior B22",
        "retailPrice": "1300",
        "releaseDate": "2021-08-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494ef5",
        "name": "Dior B22 Blue Black",
        "brand": "Dior",
        "lowestResellPrice.stockX": "875",
        "image": "https://images.stockx.com/images/Dior-B22-Blue-Black-Product.jpg",
        "description": "",
        "url": "dior-b22-blue-black",
        "resellLinks.stockX": "https://stockx.com/dior-b22-blue-black",
        "make": "Dior B22",
        "retailPrice": "1100",
        "releaseDate": "2018-04-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494ef6",
        "name": "Dior B22 White Silver",
        "brand": "Dior",
        "lowestResellPrice.stockX": "848",
        "image": "https://images.stockx.com/images/Dior-B22-White-Silver-Product.jpg",
        "description": "",
        "url": "dior-b22-white-silver",
        "resellLinks.stockX": "https://stockx.com/dior-b22-white-silver",
        "make": "Dior B22",
        "retailPrice": "1100",
        "releaseDate": "2023-05-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494ef7",
        "name": "Dior B22 Cream Beige White",
        "brand": "Dior",
        "lowestResellPrice.stockX": "1289",
        "image": "https://images.stockx.com/images/dior-b22-cream-beige-white.jpg",
        "description": "",
        "url": "dior-b22-cream-beige-white",
        "resellLinks.stockX": "https://stockx.com/dior-b22-cream-beige-white",
        "make": "Dior B22",
        "retailPrice": "1300",
        "releaseDate": "2022-08-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494ef8",
        "name": "Dior B22 Pale Pink Grey",
        "brand": "Dior",
        "lowestResellPrice.stockX": "1099",
        "image": "https://images.stockx.com/images/Dior-B22-Pale-Pink-Grey-Product.png",
        "description": "",
        "url": "dior-b22-pale-pink-grey",
        "resellLinks.stockX": "https://stockx.com/dior-b22-pale-pink-grey",
        "make": "Dior B22",
        "retailPrice": "1100",
        "releaseDate": "2018-04-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494ef9",
        "name": "Dior B22 Triple Grey",
        "brand": "Dior",
        "lowestResellPrice.stockX": "874",
        "image": "https://images.stockx.com/images/Dior-B22-Triple-Grey-Product.jpg",
        "description": "",
        "url": "dior-b22-triple-grey",
        "resellLinks.stockX": "https://stockx.com/dior-b22-triple-grey",
        "make": "Dior B22",
        "retailPrice": "1300",
        "releaseDate": "2018-04-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494efa",
        "name": "Dior B22 Pink Technical Mesh Pink Silver",
        "brand": "Dior",
        "lowestResellPrice.stockX": "979",
        "image": "https://images.stockx.com/images/Dior-B22-Pink-Technical-Mesh-Pink-Silver.jpg",
        "description": "",
        "url": "dior-b22-pink-technical-mesh-pink-silver",
        "resellLinks.stockX": "https://stockx.com/dior-b22-pink-technical-mesh-pink-silver",
        "make": "Dior B22",
        "retailPrice": "1300",
        "releaseDate": "2018-04-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494efb",
        "name": "Dior B22 Lavender Cream",
        "brand": "Dior",
        "lowestResellPrice.stockX": "1190",
        "image": "https://images.stockx.com/images/Dior-B22-Lavender-Cream-Product.jpg",
        "description": "",
        "url": "dior-b22-lavender-cream",
        "resellLinks.stockX": "https://stockx.com/dior-b22-lavender-cream",
        "make": "Dior B22",
        "retailPrice": "1300",
        "releaseDate": "2018-04-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494efc",
        "name": "Dior B22 Violet White",
        "brand": "Dior",
        "lowestResellPrice.stockX": "850",
        "image": "https://images.stockx.com/images/Dior-B22-Violet-White-Product.jpg",
        "description": "",
        "url": "dior-b22-violet-white",
        "resellLinks.stockX": "https://stockx.com/dior-b22-violet-white",
        "make": "Dior B22",
        "retailPrice": "1100",
        "releaseDate": "2020-11-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494efd",
        "name": "Dior B22 Yellow White Ebony Camel",
        "brand": "Dior",
        "lowestResellPrice.stockX": "1136",
        "image": "https://images.stockx.com/images/Dior-B22-Yellow-White-Ebony-Camel-Product.jpg",
        "description": "",
        "url": "dior-b22-yellow-white-ebony-camel",
        "resellLinks.stockX": "https://stockx.com/dior-b22-yellow-white-ebony-camel",
        "make": "Dior B22",
        "retailPrice": "1300",
        "releaseDate": "2018-04-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494efe",
        "name": "Dior B22 Blue Technical Mesh Light Blue Grey Orange",
        "brand": "Dior",
        "lowestResellPrice.stockX": "857",
        "image": "https://images.stockx.com/images/Dior-B22-Blue-Technical-Mesh-Light-Blue-Grey-Orange.jpg",
        "description": "",
        "url": "dior-b22-blue-technical-mesh-light-blue-grey-orange",
        "resellLinks.stockX": "https://stockx.com/dior-b22-blue-technical-mesh-light-blue-grey-orange",
        "make": "Dior B22",
        "retailPrice": "1300",
        "releaseDate": "2018-04-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494eff",
        "name": "Dior B22 Blue Technical Mesh Silver-Tone White",
        "brand": "Dior",
        "lowestResellPrice.stockX": "1000",
        "image": "https://images.stockx.com/images/Dior-B22-Blue-Technical-Mesh-Silver-Tone-White-Product.jpg",
        "description": "",
        "url": "dior-b22-blue-technical-mesh-silver-tone-white",
        "resellLinks.stockX": "https://stockx.com/dior-b22-blue-technical-mesh-silver-tone-white",
        "make": "Dior B22",
        "retailPrice": "1300",
        "releaseDate": "2018-04-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494f00",
        "name": "Dior B22 White Red Blue",
        "brand": "Dior",
        "lowestResellPrice.stockX": "1415",
        "image": "https://images.stockx.com/images/Dior-B22-White-Red-Blue-Product.jpg",
        "description": "",
        "url": "dior-b22-white-red-blue",
        "resellLinks.stockX": "https://stockx.com/dior-b22-white-red-blue",
        "make": "Dior B22",
        "retailPrice": "1200",
        "releaseDate": "2018-05-01"
    },
    {
        "_id": "64d1d981bb458ee5a1494f01",
        "name": "Dior B22 White Red",
        "brand": "Dior",
        "lowestResellPrice.stockX": "",
        "image": "https://images.stockx.com/images/Dior-B22-White-Red.jpg",
        "description": "",
        "url": "dior-b22-white-red",
        "resellLinks.stockX": "https://stockx.com/dior-b22-white-red",
        "make": "Dior B22",
        "retailPrice": "1100",
        "releaseDate": "2018-04-01"
    }
]

module.exports = dior