const eyblProducts = [
    {
        "_id": "64c3501cd5108ecc23fa0e3c",
        "name": "Nike Ja 1 EYBL Melon Tint",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "159",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Ja-1-EYBL-Melon-Tint.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-ja-1-eybl-melon-tint",
        "resellLinks.stockX": "https://stockx.com/nike-ja-1-eybl-melon-tint",
        "make": "Nike Ja 1",
        "retailPrice": "120",
        "releaseDate": "2023-07-25",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "ja",
            "slug": "nike-ja-1-eybl-melon-tint",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e3d",
        "name": "Nike Air Zoom G.T. Cut EYBL Team USA Sport Red",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "414",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Air-Zoom-GT-Cut-Sport-Red-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-air-zoom-gt-cut-sport-red",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-sport-red",
        "retailPrice": "170",
        "releaseDate": "2021-07-06",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "GT",
            "slug": "nike-air-zoom-gt-cut-sport-red",
        },
    },
    // {
    //     "_id": "64c3501cd5108ecc23fa0e3e",
    //     "name": "Nike Kobe 5 Protro EYBL Girls (2020)",
    //     "brand": "Nike",
    //     "price": "150",
    //     "lowestResellPrice.stockX": "360",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Kobe-5-Protro-EYBL-Forest-Green-2020-Product.jpg",
    //     "description": "Part of a collection that released for Mamba Week, the Zoom Kobe 5 Protro 'EYBL' dropped in August 2020. Inspired by Greek mythology, the shoe's synthetic upper includes a scaly texture modeled after Medusa. The left tongue sports an EYBL logo, with Kobe branding on the right shoe. The collar lining and heel accent the look, while underfoot, Zoom in the midsole provides cushioning.",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "nike-kobe-5-protro-eybl-forest-green-2020",
    //     "resellLinks.stockX": "https://stockx.com/nike-kobe-5-protro-eybl-forest-green-2020",
    //     "retailPrice": "180",
    //     "releaseDate": "2020-08-29",
    //     "metadata_": {
    //         "brand": "nike",
    //         "category": "eybl",
    //         "collection": "kobe-5",
    //         "slug": "nike-kobe-5-protro-eybl-forest-green-2020",
    //     },
    // },
    {
        "_id": "64c3501cd5108ecc23fa0e3f",
        "name": "Nike KD 13 EYBL White (2020)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "194",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-KD-13-EYBL-White-2020-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kd-13-eybl-white-2020",
        "resellLinks.stockX": "https://stockx.com/nike-kd-13-eybl-white-2020",
        "retailPrice": "150",
        "releaseDate": "2020-07-28",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "slug": "nike-kd-13-eybl-white-2020",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e40",
        "name": "Nike KD 15 EYBL Nationals",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "326",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-KD-15-EYBL-Nationals-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kd-15-eybl-nationals",
        "resellLinks.stockX": "https://stockx.com/nike-kd-15-eybl-nationals",
        "retailPrice": "150",
        "releaseDate": "2022-12-01",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "slug": "nike-kd-15-eybl-nationals",
        },
    },
    // {
    //     "_id": "64c3501cd5108ecc23fa0e41",
    //     "name": "Nike Kobe 6 Protro EYBL",
    //     "brand": "Nike",
    //     "price": "150",
    //     "lowestResellPrice.stockX": "2108",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Kobe-6-Protro-EYBL.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "nike-kobe-6-protro-eybl",
    //     "resellLinks.stockX": "https://stockx.com/nike-kobe-6-protro-eybl",
    //     "make": "Nike Kobe 6 Protro",
    //     "retailPrice": "225",
    //     "releaseDate": "2022-05-01",
    //     "metadata_": {
    //         "brand": "nike",
    //         "category": "eybl",
    //         "collection": "kobe6",
    //         "slug": "nike-kobe-6-protro-eybl",
    //     },
    // },
    // {
    //     "_id": "64c3501cd5108ecc23fa0e42",
    //     "name": "Nike Air Zoom G.T. Cut EYBL Black",
    //     "brand": "Nike",
    //     "price": "150",
    //     "lowestResellPrice.stockX": "399",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Air-Zoom-GT-Cut-EYBL-Black.jpg",
    //     "description": "",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "nike-air-zoom-gt-cut-eybl-black",
    //     "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-eybl-black",
    //     "make": "Nike Air Zoom G.T. Cut",
    //     "retailPrice": "140",
    //     "releaseDate": "2022-02-13",
    //     "metadata_": {
    //         "brand": "nike",
    //         "category": "eybl",
    //         "collection": "kobe6",
    //         "slug": "nike-air-zoom-gt-cut-eybl-black",
    //     },
    // },
    {
        "_id": "64c3501cd5108ecc23fa0e43",
        "name": "Nike KD 7 Elite EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "275",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-KD-7-Elite-EYBL-Product.jpg",
        "description": "The Elite Youth Basketball League is dedicated to educating potential athletes and encouraging the youth of the nation to follow their dreams. The KD 7 Elite ' EYBL ' released in combination with its annual tournament features an upper Metallic Red Bronze Hyperposite with big breathability perforations on the medial sides. Also the sneaker sports black accents on the tongue, collar lining, Swoosh forefoot, and on the heel's partly exposed air unit.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kd-7-elite-eybl",
        "resellLinks.stockX": "https://stockx.com/kd-7-elite-eybl",
        "retailPrice": "220",
        "releaseDate": "2015-05-08",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "slug": "kd-7-elite-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e44",
        "name": "Nike KD 12 EYBL Nike Nationals",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "335",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-KD-12-EYBL-Nike-Nationals-Product.png",
        "description": "The Nike KD 12 EYBL Nike Nationals is a basketball shoe that combines style and performance. The shoe features a black and white colorway with a unique graphic design on the upper. The upper is made of Flywire cables and a lightweight mesh material that provides breathability and support. The shoe also features a full-length Zoom Air cushioning system that delivers a responsive and comfortable ride. The outsole is made of durable rubber that provides traction on the court. The Nike KD 12 EYBL Nike Nationals was released on July 18, 2019, and retails for $150. This shoe is perfect for basketball players who want a stylish and comfortable shoe that can handle the demands of the game.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kd-12-eybl-nike-nationals",
        "resellLinks.stockX": "https://stockx.com/nike-kd-12-eybl-nike-nationals",
        "retailPrice": "150",
        "releaseDate": "2019-07-18",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "slug": "nike-kd-12-eybl-nike-nationals",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e45",
        "name": "Nike KD 11 EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "577",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-KD-11-EYBL-Product.png",
        "description": "Usually reserved for high school players participating in the Nike EYBL (Elite Youth Basketball) circuit, fans of the Nike KD 11 EYBL can rejoice that these sneakers received a broader release. This colorway draws inspiration from the annual Peach Jam tournament held in Georgia. There is a peach logo embroidered on the lateral side of on shoe, with the KD logo on the other. This pair uses hot punch on the flyknit upper, with lime blast and pure platinum detailing. Releasing in July, this pair retailed for $150.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kd-11-eybl",
        "retailPrice": "150",
        "releaseDate": "2018-07-12",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "url": "nike-kd-11-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e46",
        "name": "Nike Cosmic Unity EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "270",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Cosmic-Unity-EYBL.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-cosmic-unity-eybl",
        "resellLinks.stockX": "https://stockx.com/nike-cosmic-unity-eybl",
        "retailPrice": "150",
        "releaseDate": "",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "nike",
            "slug": "nike-cosmic-unity-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e47",
        "name": "Nike Kobe 5 Protro EYBL (2020)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1730",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Kobe-5-Protro-EYBL-2020.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-5-protro-eybl-2020",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-5-protro-eybl-2020",
        "retailPrice": "180",
        "releaseDate": "2020-08-28",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "kobe5",
            "slug": "nike-kobe-5-protro-eybl-2020",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e48",
        "name": "Nike PG 1 EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "537",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-PG-1-EYBL.png",
        "description": "Featuring a colorway inspired by Nike’s Elite Youth Basketball League, the PG 1 ‘EYBL’ utilizes an all-black upper built with a combination of suede and mesh. The stealthy finish is contrasted by an iridescent Swoosh and a vibrant multi-color design on the interior bootie. A black midsole, coated with pink and blue speckling, is supported underfoot by an icy translucent outsole.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-pg-1-eybl",
        "resellLinks.stockX": "https://stockx.com/nike-pg-1-eybl",
        "retailPrice": "110",
        "releaseDate": "2017-05-13",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "pg",
            "slug": "nike-pg-1-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e49",
        "name": "Nike Kyrie 2 EYBL Promo",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "642",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Kyrie-2-EYBL-Promo.png",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kyrie-2-eybl-promo",
        "resellLinks.stockX": "https://stockx.com/nike-kyrie-2-eybl-promo",
        "retailPrice": "130",
        "releaseDate": "2016-04-15",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "kyrie",
            "slug": "nike-kyrie-2-eybl-promo",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e4a",
        "name": "Nike Kyrie 5 Low EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "350",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Kyrie-5-Low-EYBL.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kyrie-5-low-eybl",
        "resellLinks.stockX": "https://stockx.com/nike-kyrie-5-low-eybl",
        "retailPrice": "120",
        "releaseDate": "2022-08-01",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "kyrie",
            "slug": "nike-kyrie-5-low-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e4b",
        "name": "Nike Zoom KD 11 EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Zoom-KD-11-EYBL.jpg",
        "description": "The Zoom KD 11 ‘EYBL’ showcases a special colorway inspired by the Peach Jam, the annual tournament that hosts the Finals for the Elite Youth Basketball League. Kevin Durant’s eleventh signature shoe features a vibrant Hot Punch finish on its Flyknit upper, accented with Lime Blast on the sock-like collar. A Peach Jam logo adorns the lateral heel of the left shoe, while ‘KD’ adorns the opposite shoe.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-zoom-kd-11-eybl",
        "resellLinks.stockX": "https://stockx.com/nike-zoom-kd-11-eybl",
        "retailPrice": "150",
        "releaseDate": "2018-07-13",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "slug": "nike-zoom-kd-11-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e4c",
        "name": "Nike KD 12 EYBL Floral Midsole",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-KD-12-EYBL-Floral-Midsole.jpg",
        "description": "A vibrant release, the Nike Zoom KD 12 'EYBL' commemorates the Elite Youth Basketball League with this colorful retool. Presented in October 2019, the sneaker is garbed in a transparent film upper with a patterned underlay, checkered Swooshes, and vivid Flywire cables. Floral depictions tumble across the heel and translucent Zoom Air-enhanced midsole. The versatile rubber outsole delivers excellent traction.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kd-12-eybl-floral-midsole",
        "resellLinks.stockX": "https://stockx.com/nike-kd-12-eybl-floral-midsole",
        "retailPrice": "150",
        "releaseDate": "2019-10-25",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "slug": "nike-kd-12-eybl-floral-midsole",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e4d",
        "name": "Nike KD 11 EYBL (GS)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "425",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-KD-11-EYBL-GS.png",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kd-11-eybl-gs",
        "resellLinks.stockX": "https://stockx.com/nike-kd-11-eybl-gs",
        "retailPrice": "125",
        "releaseDate": "2018-07-12",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "slug": "nike-kd-11-eybl-gs",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e4e",
        "name": "Nike Kyrie 2 EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "649",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Kyrie-2-EYBL.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kyrie-2-eybl",
        "resellLinks.stockX": "https://stockx.com/kyrie-2-eybl",
        "retailPrice": "125",
        "releaseDate": "2016-04-15",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "kyrie",
            "slug": "kyrie-2-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e4f",
        "name": "Nike LeBron 13 EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Lebron-13-EYBL-Product.jpg",
        "description": "Originally made exclusively for players in Nike’s EYBL basketball tournament, the LeBron 13 Promo ‘EYBL’ features a unique multicolor design that resembles a NASCAR livery. Instead of various sponsors, however, the shoe is covered in various LeBron James and Nike motifs, including a callout to James’ hometown of Akron. The shoe itself is built with a series of Hyperposite panels and supported by Flywire cables, with Zoom Air units underfoot for cushioning.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "lebron-13-eybl",
        "resellLinks.stockX": "https://stockx.com/lebron-13-eybl",
        "retailPrice": "200",
        "releaseDate": "2016-05-10",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "lebron",
            "slug": "lebron-13-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e50",
        "name": "Nike Kyrie Infinity EYBL Nationals",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "249",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Kyrie-Infinity-EYBL-Nationals.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kyrie-infinity-eybl-nationals",
        "resellLinks.stockX": "https://stockx.com/nike-kyrie-infinity-eybl-nationals",
        "retailPrice": "140",
        "releaseDate": "2022-12-01",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "kyrie",
            "slug": "nike-kyrie-infinity-eybl-nationals",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e51",
        "name": "Nike KD 5 Elite EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "774",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Zoom-KD-5-Elite-EYBL.jpg",
        "description": "The KD 5 Elite ‘EYBL’ was made available exclusively for 2013 participants in Nike’s Elite Youth Basketball League. The performance hoops shoe sports an eye-catching color scheme, highlighted by pops of Volt on a one-piece upper finished in gradient blue-red coloring. Underfoot, EYBL logo hits are visible underneath the translucent green rubber outsole.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kd-5-elite-eybl",
        "resellLinks.stockX": "https://stockx.com/kd-5-elite-eybl",
        "retailPrice": "180",
        "releaseDate": "2013-05-01",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "slug": "kd-5-elite-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e52",
        "name": "Nike Kyrie 3 EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1000",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Kyrie-3-EYBL-Product.jpg",
        "description": "The Kyrie 3 'EYBL' originally released only to players taking part in the Elite Youth Basketball League (EYBL). The shoe's simple white mesh upper is supported by Flywire cables, while vibrant multicolor Swooshes bring flair to the design. The colorful pattern continues most prominently on the sockliner, but it also makes its way to the midsole specking and outsole. An iridescent lace deubré adds a final colorful touch, while the footbed sports an EYBL logo as a nod to the collaboration.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kyrie-3-eybl",
        "resellLinks.stockX": "https://stockx.com/nike-kyrie-3-eybl",
        "retailPrice": "120",
        "releaseDate": "2017-05-13",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "kyrie",
            "slug": "nike-kyrie-3-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e53",
        "name": "Nike KD 6 Elite EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "4517",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-KD-6-Elite-EYBL-Product.jpg",
        "description": "The KD 6 Elite Promo ‘EYBL’ pays homage to Nike’s Elite Youth Basketball League with a vibrant multi-color design. Orange and purple hues dominate the synthetic upper, complemented by purple laces and orange Flywire cables. Those same contrasting hues are featured on the midsole, while light blue appears on the translucent outsole and KD logo on the lateral heel.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kd-6-elite-eybl",
        "resellLinks.stockX": "https://stockx.com/kd-6-elite-eybl",
        "retailPrice": "150",
        "releaseDate": "2014-05-01",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "slug": "kd-6-elite-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e54",
        "name": "Nike Hyperlive Promo EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "914",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Hyperlive-Promo-EYBL.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-hyperlive-promo-eybl",
        "resellLinks.stockX": "https://stockx.com/nike-hyperlive-promo-eybl",
        "retailPrice": "",
        "releaseDate": "",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "nike",
            "slug": "nike-hyperlive-promo-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e55",
        "name": "Nike KD 4 EYBL Grey",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-KD-4-EYBL-Grey.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kd-4-eybl-grey",
        "resellLinks.stockX": "https://stockx.com/nike-kd-4-eybl-grey",
        "retailPrice": "",
        "releaseDate": "",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "slug": "nike-kd-4-eybl-grey",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e56",
        "name": "Nike PG 3 EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1000",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-PG-3-EYBL.png",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-pg-3-eybl",
        "resellLinks.stockX": "https://stockx.com/nike-pg-3-eybl",
        "retailPrice": "110",
        "releaseDate": "2019-05-04",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "pg",
            "slug": "nike-pg-3-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e57",
        "name": "Nike Ja 1 EYBL Peach Jam",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "995",
        "image": "https://stockx-assets.imgix.net/media/Product-Placeholder-Default-20210415.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-ja-1-eybl-peach-jam",
        "resellLinks.stockX": "https://stockx.com/nike-ja-1-eybl-peach-jam",
        "retailPrice": "120",
        "releaseDate": "",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "ja",
            "slug": "nike-ja-1-eybl-peach-jam",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e58",
        "name": "Nike Ja 1 EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1000",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Ja-1-EYBL.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-ja-1-eybl",
        "resellLinks.stockX": "https://stockx.com/nike-ja-1-eybl",
        "retailPrice": "120",
        "releaseDate": "",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "ja",
            "slug": "nike-ja-1-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e59",
        "name": "Nike Zoom KD 12 EYBL Nationals",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "4504",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Zoom-KD-12-EYBL-Nationals.jpg",
        "description": "The Zoom KD 12 'EYBL Nationals' released for the girls' Nike Nationals in Chicago in July 2019. Outfitting Kevin Durant's 12th signature shoe in a vibrant colorway, the shoe's synthetic construction works a series of colors into its construction in a gradient fashion, supported by quadaxial Flywire cables for locked-down support. Underfoot, a double-stacked Zoom Air unit provides cushioning, giving way to an icy translucent outsole for traction.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-zoom-kd-12-eybl-nationals",
        "resellLinks.stockX": "https://stockx.com/nike-zoom-kd-12-eybl-nationals",
        "retailPrice": "150",
        "releaseDate": "2019-07-18",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "slug": "nike-zoom-kd-12-eybl-nationals",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e5a",
        "name": "Nike KD 4 EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/KD-4-EYBL.png",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kd-4-eybl",
        "resellLinks.stockX": "https://stockx.com/kd-4-eybl",
        "retailPrice": "130",
        "releaseDate": "",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "KD",
            "slug": "kd-4-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e5b",
        "name": "Nike PG 2 EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-PG-2-EYBL-Product.jpg",
        "description": "The PG 2 Promo TB 'EYBL' released to players in the 2018 Elite Youth Basketball League. Built with mesh, the shoe's upper sports a bright camouflage print throughout its construction, which includes a half-bootie build and an adaptive forefoot band. A heel pull-loop provides easy on and off, while underfoot, Zoom Air in the forefoot provides cushioning. A purple rubber outsole is included for traction.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-pg-2-eybl",
        "resellLinks.stockX": "https://stockx.com/nike-pg-2-eybl",
        "retailPrice": "160",
        "releaseDate": "2018-06-01",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "pg",
            "slug": "nike-pg-2-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e5c",
        "name": "Nike Air Force 1 Retro EYBL Dragon Red",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "180",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Air-Force-1-Retro-EYBL-Dragon-Red-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-air-force-1-retro-eybl-dragon-red",
        "resellLinks.stockX": "https://stockx.com/nike-air-force-1-retro-eybl-dragon-red",
        "retailPrice": "120",
        "releaseDate": "",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "af1",
            "slug": "nike-air-force-1-retro-eybl-dragon-red",
        },
    },
    // {
    //     "_id": "64c3501cd5108ecc23fa0e5d",
    //     "name": "Nike KD 12 NRG Peach Jam",
    //     "brand": "Nike",
    //     "price": "150",
    //     "lowestResellPrice.stockX": "292",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-KD-12-EYBL-Product.jpg",
    //     "description": "The Nike KD 12 NRG Peach Jam is a special-edition colorway of the NBA star Kevin Durant's 12th signature shoe with Nike.",
    //     "currency": "USD",
    //     "shippable": true,
    //     "statement_descriptor": "PRIME ORCA LLC",
    //     "url": "nike-kd-12-eybl",
    //     "resellLinks.stockX": "https://stockx.com/nike-kd-12-eybl",
    //     "retailPrice": "150",
    //     "releaseDate": "2019-07-13",
    //     "metadata_": {
    //         "brand": "nike",
    //         "category": "eybl",
    //         "collection": "KD",
    //         "slug": "nike-kd-12-eybl",
    //     },
    // },
    {
        "_id": "64c3501cd5108ecc23fa0e5e",
        "name": "Nike Blazer Mid Eyelets Bone (Women's)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "124",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Blazer-Mid-Eyelets-Bone.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-blazer-mid-eyelets-bone-w",
        "resellLinks.stockX": "https://stockx.com/nike-blazer-mid-eyelets-bone-w",
        "retailPrice": "100",
        "releaseDate": "",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "nike",
            "slug": "nike-blazer-mid-eyelets-bone-w",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e5f",
        "name": "Nike Hyperdunk 2016 TB Team Red (White Eyelets)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "image": "https://stockx-assets.imgix.net/media/Product-Placeholder-Default-20210415.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-hyperdunk-2016-tb-team-red-white-eyelets",
        "resellLinks.stockX": "https://stockx.com/nike-hyperdunk-2016-tb-team-red-white-eyelets",
        "retailPrice": "140",
        "releaseDate": "2016-01-01",
        "metadata_": {
            "brand": "nike",
            "category": "eybl",
            "collection": "hyperdunk",
            "slug": "nike-hyperdunk-2016-tb-team-red-white-eyelets",
        },
    },
]

module.exports = eyblProducts;