[
    {
        "_id": "64cf14d6f7204deafca9447f",
        "name": "Nike Air Zoom G.T. Cut 2 Black Phantom Orange",
        "price": "135",
        "brand": "Nike",
        "lowestResellPrice.stockX": "105",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-2-Black-Phantom-Orange-Product.jpg",
        "description": "",
        "url": "nike-air-zoom-gt-cut-2-black-phantom-orange",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-2-black-phantom-orange",
        "make": "Nike Air Zoom G.T. Cut 2",
        "retailPrice": "155",
        "releaseDate": "2023-03-01"
    },
    {
        "_id": "64cf14d6f7204deafca94480",
        "name": "Nike Air Zoom G.T. Cut Grinch",
        "price": "135",
        "brand": "Nike",
        "lowestResellPrice.stockX": "346",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-Grinch-Product.jpg",
        "description": "Since its first release, Nike Air Zoom GT Cut Grinch continues to be one of the variants of Nike Air Zoom, making the highest number of sales. A synthetic fiber that is sandwiched between plastics is the main material that makes up Nike Air Zoom GT Cut Grinch. Its tongue and across the toe-box are made up of neoprene-like material. Its midsole is made up of white rubber. The outsole of this shoe is made up of rubber, coming in different shades of green. Nike Air Zoom GT Cut Grinch was first released on June 18, 2021. At the time first release, its price was $100.",
        "url": "nike-air-zoom-gt-cut-grinch",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-grinch",
        "make": "Nike Air Zoom G.T. Cut",
        "retailPrice": "170",
        "releaseDate": "2022-08-12"
    },
    // {
    //     "_id": "64cf14d6f7204deafca94481",
    //     "name": "Nike Air Zoom G.T. Cut Black Crimson Green",
    //     "price": "108",
    //     "brand": "Nike",
    //     "lowestResellPrice.stockX": "292",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-Black-Crimson-Green-Product.jpg",
    //     "description": "The Nike Air Zoom GT Cut Black Crimson Green was created with insights from WNBA point guard Sabrina Ionescu and NBA point guard De’Aaron Fox. The shoe was designed with comfort and stability in mind. The Nike Air Zoom GT Cut Black Crimson Green boasts a clean black base paired with open mesh weaves to enhance breathability. In addition, the nylon panels on the instep, tongue, and toe box add a bit of contrast to the design. The shoes also feature non-filled lateral Swooshes and branded heels that sit on a rubber outsole. This shoe, which comes in a black/hyper crimson/vapor green/ghost colorway was released on May 26, 2021, and retailed for $170.",
    //     "url": "nike-air-zoom-gt-cut-black-crimson-green",
    //     "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-black-crimson-green",
    //     "make": "Nike Air Zoom G.T. Cut",
    //     "retailPrice": "170",
    //     "releaseDate": "2021-05-26"
    // },
    {
        "_id": "64cf14d6f7204deafca94482",
        "name": "Nike Air Zoom G.T. Cut 2 Coconut Milk Pink Spell",
        "price": "135",
        "brand": "Nike",
        "lowestResellPrice.stockX": "167",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-2-Coconut-Milk-Pink-Spell.jpg",
        "description": "",
        "url": "nike-air-zoom-gt-cut-2-coconut-milk-pink-spell",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-2-coconut-milk-pink-spell",
        "make": "Nike Air Zoom G.T. Cut 2",
        "retailPrice": "180",
        "releaseDate": "2023-02-01"
    },
    {
        "_id": "64cf14d6f7204deafca94483",
        "name": "Nike Air Zoom G.T. Cut EYBL Team USA Sport Red",
        "price": "135",
        "brand": "Nike",
        "lowestResellPrice.stockX": "414",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-Sport-Red-Product.jpg",
        "description": "",
        "url": "nike-air-zoom-gt-cut-sport-red",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-sport-red",
        "make": "Nike Air Zoom G.T. Cut",
        "retailPrice": "170",
        "releaseDate": "2021-07-06"
    },
    {
        "_id": "64cf14d6f7204deafca94484",
        "name": "Nike Air Zoom G.T. Cut Team USA Sport Red",
        "price": "135",
        "brand": "Nike",
        "lowestResellPrice.stockX": "280",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-USA-Sport-Red-Product.jpg",
        "description": "",
        "url": "nike-air-zoom-gt-cut-usa-sport-red",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-usa-sport-red",
        "make": "Nike Air Zoom G.T. Cut",
        "retailPrice": "170",
        "releaseDate": "2021-07-06"
    },
    {
        "_id": "64cf14d6f7204deafca94485",
        "name": "Nike Air Zoom G.T. Cut Violet Crimson",
        "price": "135",
        "brand": "Nike",
        "lowestResellPrice.stockX": "175",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-Violet-Crimson-Product.jpg",
        "description": "",
        "url": "nike-air-zoom-gt-cut-violet-crimson",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-violet-crimson",
        "make": "Nike Air Zoom G.T. Cut",
        "retailPrice": "170",
        "releaseDate": "2021-12-01"
    },
    // {
    //     "_id": "64cf14d6f7204deafca94486",
    //     "name": "Nike Air Zoom G.T. Cut Ghost",
    //     "price": "108",
    //     "brand": "Nike",
    //     "lowestResellPrice.stockX": "347",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-Ghost.jpg",
    //     "description": "",
    //     "url": "nike-air-zoom-gt-cut-ghost",
    //     "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-ghost",
    //     "make": "Nike Air Zoom G.T. Cut",
    //     "retailPrice": "175",
    //     "releaseDate": "2022-04-06"
    // },
    // {
    //     "_id": "64cf14d6f7204deafca94487",
    //     "name": "Nike Air Zoom G.T. Cut Crimson",
    //     "price": "108",
    //     "brand": "Nike",
    //     "lowestResellPrice.stockX": "380",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-Crimson.jpg",
    //     "description": "The Nike Air Zoom G.T. Cut Crimson was a stand-alone sneaker that was released in 2021. The Cut Crimson Nike Air Zoom G.T. has an upper that is made of a lightweight, breathable mesh material that provides ventilation and helps to keep the feet cool. It comes in a white and crimson colorway, with black accents. The sneaker is accessorized with white flat laces that allow for a customized fit and provides added support around the midfoot. The midsole is made of a combination of Nike React foam and Air Zoom cushioning, providing a responsive and comfortable ride. The outsole features a durable rubber material and a multidirectional herringbone pattern, which delivers traction and allows for quick cuts and changes of direction. The shoe has crimson accents on the sole and the heel tab. The Nike Air Zoom G.T. Cut Crimson was released on July 6th, 2021 at a retail price of $170.",
    //     "url": "nike-air-zoom-gt-cut-crimson",
    //     "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-crimson",
    //     "make": "Nike Air Zoom G.T. Cut",
    //     "retailPrice": "170",
    //     "releaseDate": "2021-07-06"
    // },
    // {
    //     "_id": "64cf14d6f7204deafca94488",
    //     "name": "Nike Air Zoom G.T. Cut Think Pink",
    //     "price": "108",
    //     "brand": "Nike",
    //     "lowestResellPrice.stockX": "479",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-Think-Pink-Product.jpg",
    //     "description": "",
    //     "url": "nike-air-zoom-gt-cut-think-pink",
    //     "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-think-pink",
    //     "make": "Nike Air Zoom G.T. Cut",
    //     "retailPrice": "170",
    //     "releaseDate": "2022-02-22"
    // },
    {
        "_id": "64cf14d6f7204deafca94489",
        "name": "Nike Air Zoom G.T. Cut Blue Void Purple Red",
        "price": "135",
        "brand": "Nike",
        "lowestResellPrice.stockX": "383",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-Blue-Void-Purple-Red-Product.jpg",
        "description": "",
        "url": "nike-air-zoom-gt-cut-blue-void-purple-red",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-blue-void-purple-red",
        "make": "Nike Air Zoom G.T. Cut",
        "retailPrice": "170",
        "releaseDate": "2021-06-20"
    },
    // {
    //     "_id": "64cf14d6f7204deafca9448a",
    //     "name": "Nike Air Zoom G.T. Cut White Black Laser Blue",
    //     "price": "108",
    //     "brand": "Nike",
    //     "lowestResellPrice.stockX": "380",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-White-Black-Laser-Blue-Product.jpg",
    //     "description": "The Nike Air Zoom G.T. Cut White Black Laser Blue is a new running shoe released by Nike. The White Black Laser Blue Nike Air Zoom G.T. Cut features a white upper with black overlays, and Laser Blue detailing. The midsole has a Zoom Air sole unit that provides cushioning and support to the foot, and the Nike Swoosh is prominently displayed on the side of the shoe. We think that one of the key features of the Nike Air Zoom G.T. Cut is its lightweight construction which makes it a versatile shoe that can be used for different kinds of workouts, including running, training, and even casual wear. The shoe is composed of a breathable mesh upper and boasts a foam material provided by Nike called React foam, which is soft and yet responsive. This combination of materials reduces the overall weight of the shoe while providing maximum comfort to the wearer. The Nike Air Zoom G.T. Cut White Black Laser Blue was released on May 26, 2021 at a retail price of $170.",
    //     "url": "nike-air-zoom-gt-cut-white-black-laser-blue",
    //     "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-white-black-laser-blue",
    //     "make": "Nike Air Zoom G.T. Cut",
    //     "retailPrice": "170",
    //     "releaseDate": "2021-05-26"
    // },
    {
        "_id": "64cf14d6f7204deafca9448b",
        "name": "Nike Air Zoom G.T. Cut EYBL Black",
        "price": "135",
        "brand": "Nike",
        "lowestResellPrice.stockX": "399",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-EYBL-Black.jpg",
        "description": "",
        "url": "nike-air-zoom-gt-cut-eybl-black",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-eybl-black",
        "make": "Nike Air Zoom G.T. Cut",
        "retailPrice": "140",
        "releaseDate": "2022-02-13"
    },
    {
        "_id": "64cf14d6f7204deafca9448c",
        "name": "Nike Air Zoom G.T. Cut 2 Desert Berry Valerian Blue",
        "price": "135",
        "brand": "Nike",
        "lowestResellPrice.stockX": "150",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-2-Desert-Berry-Valerian-Blue.jpg",
        "description": "",
        "url": "nike-air-zoom-gt-cut-2-desert-berry-valerian-blue",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-2-desert-berry-valerian-blue",
        "make": "Nike Air Zoom G.T. Cut 2",
        "retailPrice": "155",
        "releaseDate": ""
    },
    // {
    //     "_id": "64cf14d6f7204deafca9448d",
    //     "name": "Nike Air Zoom G.T. Cut University Red White Yellow",
    //     "price": "108",
    //     "brand": "Nike",
    //     "lowestResellPrice.stockX": "506",
    //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-University-Red-White-Yellow.jpg",
    //     "description": "",
    //     "url": "nike-air-zoom-gt-cut-university-red-white-yellow",
    //     "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-university-red-white-yellow",
    //     "make": "Nike Air Zoom G.T. Cut",
    //     "retailPrice": "170",
    //     "releaseDate": ""
    // },
    {
        "_id": "64cf14d6f7204deafca9448e",
        "name": "Nike Air Zoom G.T. Cut TB University Red White",
        "price": "135",
        "brand": "Nike",
        "lowestResellPrice.stockX": "469",
        "image": "https://stockx-assets.imgix.net/media/Product-Placeholder-Default-20210415.jpg",
        "description": "",
        "url": "nike-air-zoom-gt-cut-tb-university-red-white",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-tb-university-red-white",
        "make": "Nike Air Zoom G.T. Cut TB",
        "retailPrice": "170",
        "releaseDate": "2021-06-01"
    },
    {
        "_id": "64cf14d6f7204deafca9448f",
        "name": "Nike Air Zoom G.T. Cut White Laser Blue",
        "price": "135",
        "brand": "Nike",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-White-Laser-Blue.jpg",
        "description": "",
        "url": "nike-air-zoom-gt-cut-white-laser-blue",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-white-laser-blue",
        "make": "Nike Air Zoom G.T. Cut",
        "retailPrice": "170",
        "releaseDate": "2021-06-14"
    }
]