const kobe6Products = [
    {
        "_id": "64a3210b5d8fce08b7d5d6fa",
        "name": "Nike Kobe 6 Protro Mambacita Sweet 16",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "570",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Protro-Mamba-Forever-Product.png",
        "description": "`Nike honors the legacy of Kobe Bryant and his daughter Gigi with the Kobe 6 Protro 'Mambacita Sweet Sixteen.' Black snake scales across the upper reference the Laker legend's Black Mamba alter ego, while the Swoosh, tongue logo and leather back panels are executed in white. A Mamba & Mambacita Sports Foundation crest appears in place of the traditional Kobe signature heel mold, with \"Kobe\" and \"Gigi\" printed on the left and right shoe, respectively. A gold \"2\" on the lateral window represents Gigi's AAU uniform number. The insole design pays further tribute to Gigi with an illustration that features a halo, angel wings, the nickname \"Mambacita\" and another \"2.\"\n`",
        "url": "nike-kobe-6-protro-mamba-forever",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-protro-mamba-forever",
        "make": "Nike Kobe 6 Protro",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mamba-forever"
        },
        "releaseDate": "2022-05-01"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d6e3",
        "name": "Nike Kobe 6 Protro Reverse Grinch",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "10000",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/kobe-6-reverse-grinches.png",
        "description": "`Reverse Grinches.`",
        "url": "nike-kobe-6-reverse-grinch",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "",
        "make": "Nike Kobe 6 Protro",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-reverse-grinch"
        },
        "releaseDate": "2023-12-16"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d6fb",
        "name": "Nike Kobe 6 Protro Grinch (2020)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "620",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Protro-Grinch-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1611766717",
        "description": "Originally released in 2010 for a Christmas Day collection, the Zoom Kobe 6 Protro 'Grinch' dropped in December 2020. The shoe's upper features a Green Apple and Volt look, with polyurethane detailing creating a snakeskin-style texture throughout the construction. Crimson on the branding and laces adds to the holiday aesthetic, while underfoot, the midsole incorporates Zoom Air to provide cushioning.",
        "url": "nike-kobe-6-protro-grinch",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-protro-grinch",
        "make": "Nike Kobe 6 Protro",
        "retailPrice": "190",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2020-12-24"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d6fc",
        "name": "Kobe 6 Protro Playoff Pack White Del Sol",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "440",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Kobe-6-Protro-Playoff-Pack-White-Del-Sol-Product.png",
        "description": "",
        "url": "kobe-6-protro-playoff-pack-white-del-sol",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-protro-playoff-pack-white-del-sol",
        "make": "Kobe 6 Protro",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2021-06-03"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d6fd",
        "name": "Nike Kobe 6 Protro Challenge Red All-Star (2021)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "449",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Protro-Challenge-Red-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1659335330",
        "description": "",
        "url": "nike-kobe-6-protro-challenge-red",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-protro-challenge-red",
        "make": "Nike Kobe 6 Protro",
        "retailPrice": "190",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2021-03-15"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d6fe",
        "name": "Nike Kobe Protro 6 Think Pink",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "2999",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-Protro-6-Think-Pink-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1648066322",
        "description": "",
        "url": "nike-kobe-protro-6-think-pink",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-protro-6-think-pink",
        "make": "Nike Kobe Protro 6",
        "retailPrice": "225",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2021-12-28"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d6ff",
        "name": "Nike Kobe 6 Black Del Sol",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "950",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Black-Del-Sol-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610078703",
        "description": "The inaugural colorway of the Zoom Kobe 6, the Zoom Kobe 6 'Black Del Sol' is most notable for the snakeskin detailing throughout the upper. Created through the application of polyurethane 'islands' on the mesh upper, the shoe's black makeup is accented by bright Del Sol on the Swoosh and heel branding. The black midsole features Phylon and Zoom Air, giving way to an outsole sporting another hit of Del Sol.",
        "url": "kobe-6-black-del-sol",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-black-del-sol",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2010-12-26"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d700",
        "name": "Nike Kobe 6 Protro Grinch (2020) (Includes Storyteller Collection Books)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "849",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Protro-Grinch-2020-Includes-Storyteller-Collection-Books.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1674711086",
        "description": "Originally released in 2010 for a Christmas Day collection, the Zoom Kobe 6 Protro 'Grinch' dropped in December 2020. The shoe's upper features a Green Apple and Volt look, with polyurethane detailing creating a snakeskin-style texture throughout the construction. Crimson on the branding and laces adds to the holiday aesthetic, while underfoot, the midsole incorporates Zoom Air to provide cushioning.",
        "url": "nike-kobe-6-protro-grinch-2020-includes-storyteller-collection-books",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-protro-grinch-2020-includes-storyteller-collection-books",
        "make": "Nike Kobe 6 Protro",
        "retailPrice": "308",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2022-12-25"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d701",
        "name": "Nike Kobe 6 Protro EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "2200",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Protro-EYBL.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1645063261",
        "description": "",
        "url": "nike-kobe-6-protro-eybl",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-protro-eybl",
        "make": "Nike Kobe 6 Protro",
        "retailPrice": "225",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2022-05-01"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d702",
        "name": "Nike Kobe 6 Grinch (2010)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1455",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Grinch-Christmas-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1606317200",
        "description": "Released on Christmas Day 2010, the Zoom Kobe 6 'Grinch' features a lime green colorway that recalls Dr. Suess' infamous holiday grouch. However, the shoe itself was actually inspired by the green mamba, a colorful take on Bryant's Black Mamba nickname. The shoe's snakeskin-textured upper further plays to that inspiration, while Varsity Red adds to the Christmas look. Zoom Air and an external heel counter support the fit.",
        "url": "kobe-6-grinch",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-grinch",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2010-12-25"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d703",
        "name": "Nike Kobe 6 Prelude (All-Star MVP)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1795",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Prelude-All-Star-MVP-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610080170",
        "description": "Part of an eight-shoe capsule leading up to the release of the Kobe 9, the Zoom Kobe 6 'Prelude' features a colorful graffiti design sporting a variety of images, incuding palm trees and sharks. The design is inspired by the eclectic Venice, California, while the design itslef is put on an upper with a snakeskin texture. Zoom Air provides cushioning in the midsole, with a heel counter adding stability.",
        "url": "kobe-6-prelude-all-star-mvp",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-prelude-all-star-mvp",
        "make": "Nike Kobe 6",
        "retailPrice": "200",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2014-01-11"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d704",
        "name": "Nike Kobe 6 Supreme Rice",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "988",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Supreme-Rice-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610078769",
        "description": "The Zoom Kobe 6 Supreme 'Rice' pays tribute to Harlem's Rice High School, one of the schools that Kobe Bryant sponsors. Featuring a black and metallic Moss Green upper, the polyurethane construction incorporates a raised snakeskin pattern. Green Apple brings contrast to the Swoosh and outsole, while a heel counter and Zoom cushioning support the fit. Rice's logo emerges on the medial side.",
        "url": "kobe-6-supreme-rice",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-supreme-rice",
        "make": "Nike Kobe 6",
        "retailPrice": "150",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2011-03-05"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d705",
        "name": "Nike Kobe 6 ASG East LA",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "893",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-ASG-East-LA.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610078689",
        "description": "One of four colorways for the 2011 NBA All-Star Game, the Zoom Kobe 6 All-Star 'La' features a purple snakeskin-textured upper depicting a graphic of the Los Angeles skyline, with tattoo-style artwork on the heel. More tattoo designs emerge on insole, while the fit is supported by an external heel counter. The Zoom midsole gives way to a translucent outsole.",
        "url": "kobe-6-asg-east-la",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-asg-east-la",
        "make": "Nike Kobe 6",
        "retailPrice": "135",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2011-02-17"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d706",
        "name": "Nike Kobe 6 Helicopter",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1100",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Glass-Helicopter.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610078732",
        "description": "Also known as the 'Glass Blue,' the Zoom Kobe 6 'Helicopter' features a grey base on its snakeskin-textured polyurethane upper. Glass Blue emerges on the laces and external heel counter, matched by the Phylon and Zoom Air midsole. The outsole and branding add hits of Vibrant Yellow, while the outsole itself also takes on a translucent speckled finish at the forefoot.",
        "url": "kobe-6-helicopter",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-helicopter",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2011-03-05"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d707",
        "name": "Nike Kobe 6 BHM (2011)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "300",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-BHM-2011.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610079526",
        "description": "The Zoom Kobe 6 features a metallic gold accents representing championship accomplishments, woodcut handcraft celebrating African-American art, and a black base inspired by the black Chucks worn by athletes in the 60s. It was released as part of a larger Nike collection celebrating Black History Month.",
        "url": "nike-kobe-6-bhm-2011",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-bhm-2011",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2011-02-26"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d708",
        "name": "Nike Kobe 6 Black Mamba Collection Fade to Black",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "906",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Fade-To-Black-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1627414656",
        "description": "The Zoom Kobe 6 ‘FTB’ dropped in 2016 as part of Nike’s massive ‘Fade to Black’ collection, a 13-shoe sendoff meant to commemorate Kobe Bryant’s final season in the NBA. This pair features a monochromatic greyscale color scheme inspired by Kobe’s 2011 trip to the Philippines, where he demonstrated his unrelenting competitiveness in pick-up games against UAAP All-Stars.",
        "url": "kobe-6-black-mamba-collection-fade-to-black",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-black-mamba-collection-fade-to-black",
        "make": "Nike Kobe 6",
        "retailPrice": "200",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2016-04-05"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d709",
        "name": "Nike Kobe 6 ASG West Challenge Red",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "630",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-ASG-West-Challenge-Red.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610078794",
        "description": "This Zoom Kobe 6 All-Star dropped in 2011 as part of four-piece Kobe 6 pack celebrating Los Angeles, host city of that year’s midseason exhibition game. This red and black colorway, reflecting the uniform of the Western Conference squad, is the actual shoe that Kobe wore during the All-Star Game. Unique details include a hologram-like graphic on the tongue and custom All-Star insoles.",
        "url": "kobe-6-asg-west-challenge-red",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-asg-west-challenge-red",
        "make": "Nike Kobe 6",
        "retailPrice": "135",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2011-02-17"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d70a",
        "name": "Nike Kobe 6 ASG Hollywood 3D",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "927",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-ASG-Hollywood-3D-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1648066171",
        "description": "The Zoom Kobe 6 All-Star '3D/Hollywood' was one of three Kobe 6 All-Star models released for the 2011 All-Star Game, which was held in Los Angeles. Featuring a mix of red and Chlorine Blue on the snakeskin-inspired design of the upper, the two colors work together to create a traditional 3D effect. The mismatched shoes also feature red and Chlorine Blue on the branding and heel counters to represent the Eastern and Western Conferences, while the inside of the tongue sports a graphic of a pair of 3D glasses.",
        "url": "kobe-6-asg-hollywood-3d",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-asg-hollywood-3d",
        "make": "Nike Kobe 6",
        "retailPrice": "135",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "Nike-Kobe-5-Protro-Bruce-Lee-Product"
        },
        "releaseDate": "2011-02-17"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d70b",
        "name": "Nike Kobe 6 Dark Knight",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "2304",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Dark-Knight-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1612830594",
        "description": "The Nike Zoom Kobe 6 ‘Dark Knight’ dropped in 2011, an adversarial colorway that followed a Joker-themed Kobe 6 from earlier in the year. The low-top hoops shoe features a snakeskin-textured upper in black, accented with a Blue Glow swoosh and Kobe’s personal logo in red atop a grey leather tongue. A matching black phylon midsole packs Nike Zoom Air at both the forefoot and heel.",
        "url": "kobe-6-dark-knight",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-dark-knight",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-grinch"
        },
        "releaseDate": "2011-11-21"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d70c",
        "name": "Nike Zoom Kobe VI 3D Lakers",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "858",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Zoom-Kobe-VI-3D-Lakers.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1648866306",
        "description": "Giving the nod to the only franchise Kobe Bryant played for, the Zoom Kobe 6 '3D Lakers' emerges with a distinctly Los Angeles Lakers colorway. The shoe's upper is defined by the lenticular 3D effect throughout, finished in a familiar mix of Club Purple and Del Sol, with the two colors appearing mismatched on the laces, TPU heel counter and rubber outsole. Air underfoot provides cushioning.",
        "url": "nike-zoom-kobe-vi-3d-lakers",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-zoom-kobe-vi-3d-lakers",
        "make": "Nike Zoom Kobe VI",
        "retailPrice": "160",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-zoom-kobe-vi-3d-lakers"
        },
        "releaseDate": "2011-11-02"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d70d",
        "name": "Nike Kobe 6 Lower Merion Aces",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1100",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Lower-Merion-Aces-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610078738",
        "description": "The Zoom Kobe 6 ‘Lower Merion Aces’ features a grey midsole, a Pure Platinum outsole and the basketball team’s logo, the Aces, on the lateral heel. It is a tribute to Kobe Bryant’s alma mater by combining Cool Grey and metallic platinum hues on its snakeskin upper alongside a Varsity Crimson Swoosh.",
        "url": "kobe-6-lower-merion-aces",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-lower-merion-aces",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-lower-merion-aces"
        },
        "releaseDate": "2011-09-10"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d70e",
        "name": "Nike Kobe 6 Supreme Chaos",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "981",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Supreme-Chaos-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1624468279",
        "description": "The 2011 Zoom Kobe 6 Supreme ‘Chaos’ features a color scheme inspired by the Joker, Batman’s arch nemesis. Preceding the launch of an accompanying ‘Dark Knight’ Kobe 6, the low-top features a purple-tinged snakeskin texture on the upper, accented with a bright Volt Swoosh. Red speckled detailing appears on a white phylon midsole, reinforced underfoot by a Volt rubber outsole.",
        "url": "kobe-6-supreme-chaos",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-supreme-chaos",
        "make": "Nike Kobe 6",
        "retailPrice": "150",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-supreme-chaos"
        },
        "releaseDate": "2011-04-09"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d70f",
        "name": "Nike Kobe 6 FC Barcelona Home",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "997",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-FC-Barcelona-Home-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610079434",
        "description": "A character driven shoe based on the athlete’s Black Mamba persona, the Zoom Kobe 6 arrives in a ‘Barcelona’ edition that gives the nod to Kobe’s passion for soccer. The colorway takes inspiration from FC Barcelona, featuring a snakeskin-like upper in Storm Blue with a contrasting yellow Swoosh and pops of red on the heel cage and midsole.",
        "url": "kobe-6-fc-barcelona-home",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-fc-barcelona-home",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-fc-barcelona-home"
        },
        "releaseDate": "2011-01-01"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d710",
        "name": "Nike Kobe 6 Kay Yow Think Pink",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "4100",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Kay-Yow-Think-Pink.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610079454",
        "description": "The Zoom Kobe 6 ‘Think Pink’ launched in 2011 as part of a larger footwear collection dedicated to raising awareness for the Kay Yow Cancer Fund. Kobe Bryant’s signature shoe is dressed in a snakeskin-textured upper dressed in Pinkfire, accented with contrasting white hits on the signature Swoosh and heel panel. The latter is adorned with a pink ribbon emblem.",
        "url": "kobe-6-kay-yow-think-pink",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-kay-yow-think-pink",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-kay-yow-think-pink"
        },
        "releaseDate": "2011-08-26"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d711",
        "name": "Nike Kobe 6 China 3D",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "995",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-China-3D-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610079540",
        "description": "The Zoom Kobe 6 'China' gives the nod to Kobe Bryant's following in China. The shoe's snakeskin-textured upper is finished Metallic Pewter, complemented by an Ink Swoosh and lining. Crimson appears on the tongue branding, while an external heel counter and Zoom Air support the fit. 'Venomenon' appears on the toe of the midsole.",
        "url": "kobe-6-china-3d",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-china-3d",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-china-3d"
        },
        "releaseDate": "2011-03-05"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d712",
        "name": "Nike Kobe 6 Imperial Purple",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "876",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Imperial-Purple.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610078809",
        "description": "The Zoom Kobe 6 'Imperial Purple' emerges with a Los Angeles Lakers-style colorway. Featuring Imperial Purple throughout its upper, which sports a 3D snakeskin texture, Imperial Purple continues onto the external heel counter, while the tongue, branding and outsole are finished in Del Sol. Supported by Flywire cables, the midsole includes Zoom cushioning.",
        "url": "kobe-6-imperial-purple",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-imperial-purple",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-imperial-purple"
        },
        "releaseDate": "2011-09-01"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d713",
        "name": "Nike Kobe 6 Draft Day",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "700",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Draft-Day.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1617290549",
        "description": "The Zoom Kobe 6 'Draft Day' gives the nod to the famous 1996 draft day trade that saw the Charlotte Hornets send the 13th overall pick to the Los Angeles Lakers in exchange for Vlade Divac. The Lakers would take Kobe Bryant, whose signature shoe appears here in the colors of the team that didn't draft him. The shoe's white snakeskin-textured upper sports a Varsity Purple Swoosh and laces, with Photo Blue on the heel counter, lining and midsole to complete the team look.",
        "url": "kobe-6-draft-day",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-draft-day",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-draft-day"
        },
        "releaseDate": "2011-05-26"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d714",
        "name": "Nike Kobe 6 Concord",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "810",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Concord-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610079561",
        "description": "The Zoom Kobe 6 'Concord' dresses Kobe Bryant's sixth signature shoe in a colorway more familiar to Jordan Brand. The shoe's white snakeskin-textured upper is accented by Concord on the stabilizing heel counter and lining. The signature color takes over the Zoom midsole, while black branding finishes off the look.",
        "url": "kobe-6-concord",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-concord",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-concord"
        },
        "releaseDate": "2011-01-15"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d715",
        "name": "Nike Kobe 6 Lightbulb",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "2500",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Lightbulb.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1617290173",
        "description": "Debuting on the feet of Kobe Bryant during the 2011 NBA Playoffs, the Zoom Kobe 6 ‘Light Bulb’ features a yellow finish on the upper, featuring a series of polyurethane ‘islands’ to simulate the look of snakeskin. Contrasting hits of black appear on the Swoosh, heel counter and phylon injected midsole, fitted with Zoom Air units in the heel and forefoot for responsive cushioning.",
        "url": "kobe-6-lightbulb",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-lightbulb",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-lightbulb"
        },
        "releaseDate": "2011-05-21"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d716",
        "name": "Nike Kobe 6 Steelers",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "600",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Steelers.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1617291685",
        "description": "The Zoom Kobe 6 'Steelers' emerges with a Pittsburgh Steelers-style colorway. The white and grey upper features a 3D snakeskin texture, while the black external heel counter is matched by the side wall Swoosh. Del Sole emerges on the lining and outsole to add color to the look, while the Phylon midsole with Zoom Air units provides cushioning.",
        "url": "kobe-6-steelers",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-steelers",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-steelers"
        },
        "releaseDate": "2011-04-01"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d717",
        "name": "Nike Kobe 6 FC Barcelona Mango",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "2699",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-FC-Barcelona-Mango.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610079576",
        "description": "The Zoom Kobe 6 'Barcelona' is inspired by FC Barcelona, who count Kobe Bryant as a fan. The shoe's Bright Mango finish on the snakesin-textured upper is complemented by black on the Swoosh and TPU heel counter, a look modeled after Barcelona's alternate jerseys. More black emerges on the Zoom midsole, with a translucent finish on the outsole.",
        "url": "kobe-6-fc-barcelona-mango",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-fc-barcelona-mango",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-fc-barcelona-mango"
        },
        "releaseDate": "2011-01-01"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d718",
        "name": "Nike Kobe 6 Metallic Silver Metallic Silver White",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "3250",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Metallic-Silver.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1617289278",
        "description": "The Nike Zoom Kobe 6 takes on a Metallic Silver finish, complementing a snakeskin-like upper that gives the nod to Kobe Bryant’s Black Mamba persona. The monochromatic coloring up top is broken up by a white signature Swoosh, matched by a white phylon midsole that packs Zoom Air units in both the heel and forefoot for lightweight cushioning on the hardwood.",
        "url": "nike-kobe-6-metallic-silver-metallic-silver-white",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-metallic-silver-metallic-silver-white",
        "make": "Nike Kobe 6 Metallic Silver",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-metallic-silver-metallic-silver-white"
        },
        "releaseDate": "2011-07-01"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d719",
        "name": "Nike Kobe 6 Italian Camo",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "925",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Italian-Camo.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1612830877",
        "description": "The Zoom Kobe 6 'Camo' features a utilitarian colorway that works a camo pattern into its signature polyurethane snakeskin-textured upper. The tongue and Swoosh branding add contrasting crimson, while the heel counter maintains the otherwise-subdued look. The black midsole houses Zoom Air in the forefoot and heel.",
        "url": "kobe-6-italian-camo",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-italian-camo",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-italian-camo"
        },
        "releaseDate": "2011-06-04"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d71a",
        "name": "Nike Kobe 6 Lakers Home",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "832",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Lakers-Home.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1612830262",
        "description": "Kobe Bryant's sixth signature shoe with Nike gets a colorway inspired by the only NBA team he ever played for. The Zoom Kobe 6 'Lakers Home' features a white synthetic upper with snakeskin detailing throughout the forefoot and quarter panel, while Del Sol Swoosh and purple heel create the team look. The speckled heel counter also sports yellow speckled detailing, while Zoom in the midsole is included for cushioning.",
        "url": "kobe-6-lakers-home",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-lakers-home",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-lakers-home"
        },
        "releaseDate": "2011-10-01"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d71b",
        "name": "Nike Kobe 6 Blue Camo",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "810",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Blue-Camo-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1678264757",
        "description": "The Zoom Kobe 6 'Blue Camo' features a colorful Photo Blue camo pattern throughout its snakeskin-textured upper. Supported by a padded tongue and collar, a white Swoosh cuts through the quarter panel. The heel counter adds a vibrant hit of Volt, while the black, Photo Blue and grey midsole incorporates Zoom cushioning.",
        "url": "kobe-6-blue-camo",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-blue-camo",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-blue-camo"
        },
        "releaseDate": "2011-07-01"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d71c",
        "name": "Nike Kobe 6 ASG Orange County Sunset",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1198",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-ASG-Orange-County-OC-Sunset-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610078347",
        "description": "In celebration of the 2011 NBA All-Star Game, Nike dropped a collection of four Zoom Kobe 6 colorways, each taking inspiration from Southern California. This pair gives the nod to Orange County, featuring an upper dressed in a blend of orange and yellow to evoke the look of a Cali sunset. The dominant warm hues up top are contrasted by flashes of teal on the outsole and heel counter.",
        "url": "kobe-6-asg-orange-county-sunset",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-asg-orange-county-sunset",
        "make": "Nike Kobe 6",
        "retailPrice": "135",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-asg-orange-county-sunset"
        },
        "releaseDate": "2011-02-17"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d71d",
        "name": "Nike Kobe 6 Purple Gradient",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "549",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Purple-Gradient.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1617295624",
        "description": "The Zoom Kobe 6 'Purple Gradient' features a two-tone polyurethane upper that transitions from Concord to black. A metallic silver Swoosh accents the snakeskin-textured look, with more metallic silver on the external heel counter. A white Phylon midsole houses Zoom Air in the forefoot and heel, while black and Concord are featured together on the outsole.",
        "url": "kobe-6-purple-gradient",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-purple-gradient",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-purple-gradient"
        },
        "releaseDate": "2011-05-05"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d71e",
        "name": "Nike Zoom Kobe 6 White Del Sol",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "650",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Zoom-Kobe-6-White-Del-Sol.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1651432226",
        "description": "",
        "url": "nike-zoom-kobe-6-white-del-sol",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-zoom-kobe-6-white-del-sol",
        "make": "Nike Zoom Kobe 6",
        "retailPrice": "",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2011-07-15"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d71f",
        "name": "Nike Kobe 6 Lakers Gradient Away",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1146",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Lakers-Gradient-Away.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1617289286",
        "description": "Featuring a Los Angeles Lakers colorway, the Zoom Kobe 6 'Lakers Gradient' is a performance basketball shoe. The team's signature mix of Club Purple and Del Sol emerges throughout the signature upper, which includes polyurethane 'islands.' A white Swoosh is matched by the TPU heel counter which offers stability, while underfoot, Zoom Air in the forefoot and heel of the midsole provides cushioning.",
        "url": "nike-kobe-6-lakers-gradient-away",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-lakers-gradient-away",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-lakers-gradient-away"
        },
        "releaseDate": "2011-11-19"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d720",
        "name": "Nike Kobe 6 Team Bank Colorways",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "995",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Team-Bank.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1617297119",
        "description": "The Zoom Kobe 6 'Duke' features a color scheme that recalls the Duke Blue Devils, where Kobe Bryant might have played had he not gone directly to the NBA. The shoe's snakeskin-textured upper is finished in Varsity Royal, contrasted by a white Swoosh and supported by a black heel counter. A white Zoom midsole gives way to more blue on the outsole.",
        "url": "kobe-6-team-bank-colorways",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-team-bank-colorways",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-team-bank-colorways"
        },
        "releaseDate": "2011-09-12"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d721",
        "name": "Nike Kobe 6 Urban Camo",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "693",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Urban-Camo.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1617290734",
        "description": "The Zoom Kobe 6 ‘Urban Camo’ complements the low-top’s snakeskin texture with a subtle camouflage print made up of brown, tan and grey hues. The neutral palette is accented with pops of Concord on the Swoosh and collar lining. The low-top sits atop a contrasting black phylon midsole, fitted with Nike Zoom units in the heel and forefoot, and is offset by a white rubber outsole.",
        "url": "kobe-6-urban-camo",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-urban-camo",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-urban-camo"
        },
        "releaseDate": "2011-07-26"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d722",
        "name": "Nike Kobe 6 TB Midnight Navy",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-TB-Midnight-Navy.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1679496702",
        "description": "",
        "url": "nike-kobe-6-tb-midnight-navy",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-tb-midnight-navy",
        "make": "Nike Kobe 6 TB",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-tb-midnight-navy"
        },
        "releaseDate": "2011-07-01"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d723",
        "name": "Nike Kobe 6 Bred",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "2500",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Bred-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1686755916",
        "description": "The Zoom Kobe 6 ‘Bred’ showcases a familiar color scheme, highlighted by a snakeskin-like polyurethane upper finished in black. Contrasting hits of Varsity Red appear on the shoe’s external heel counter and phylon midsole, which houses Zoom Air units in the forefoot and heel for responsive cushioning. A white signature Swoosh is matched underfoot by a white rubber outsole.",
        "url": "kobe-6-bred",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-bred",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-bred"
        },
        "releaseDate": "2011-02-05"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d724",
        "name": "Nike Kobe 6 Protro Chaos",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "images": "https://stockx-assets.imgix.net/media/Product-Placeholder-Default-20210415.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=0",
        "description": "",
        "url": "nike-kobe-6-protro-chaos",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-protro-chaos",
        "make": "Nike Kobe 6 Protro",
        "retailPrice": "190",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-chaos"
        },
        "releaseDate": ""
    },
    {
        "_id": "64a3210b5d8fce08b7d5d725",
        "name": "Nike Kobe 6 Grey Black",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Grey-Black.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1617290723",
        "description": "The Zoom Kobe 6 features a neutral look on its performance design. The upper's signature 3D snakeskin texture is finished in Medium Grey, complemented by a black Swoosh and heel counter. A white tongue contrasts the look, while the black midsole houses Zoom Air cushioning. Underfoot, the white ousole sports a strategic traction pattern.",
        "url": "kobe-6-grey-black",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/kobe-6-grey-black",
        "make": "Nike Kobe 6",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "kobe-6-grey-black"
        },
        "releaseDate": "2011-02-25"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d726",
        "name": "Nike Kobe VI Black Gold (PS)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-VI-Black-Gold-PS.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1648512993",
        "description": "",
        "url": "nike-kobe-vi-black-gold-ps",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-vi-black-gold-ps",
        "make": "Nike Kobe VI",
        "retailPrice": "",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-vi-black-gold-ps"
        },
        "releaseDate": ""
    },
    {
        "_id": "64a3210b5d8fce08b7d5d727",
        "name": "Nike Kobe 6 Protro Think Pink",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "88888",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Protro-Think-Pink.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1626290246",
        "description": "",
        "url": "nike-kobe-6-protro-think-pink",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-protro-think-pink",
        "make": "Nike Kobe 6 Protro",
        "retailPrice": "190",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-think-pink"
        },
        "releaseDate": ""
    },
    {
        "_id": "64a3210b5d8fce08b7d5d728",
        "name": "Nike Kobe 6 Grinch (GS)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Grinch-GS.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1610079450",
        "description": "Officially named the 'Green Mamba,' the Kobe 6 GS 'Grinch' released on Christmas Day 2010, and its resemblance to the iconic holiday curmudgeon led to the fan-given 'Grinch' nickname. Featuring a Green Apple finish on the textured upper, Volt complements the look on the tongue and heel of the midsole. Hits of red contribute to the festive design.",
        "url": "nike-kobe-6-grinch-gs",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-grinch-gs",
        "make": "Nike Kobe 6",
        "retailPrice": "110",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-grinch-gs"
        },
        "releaseDate": "2010-12-25"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d729",
        "name": "Nike Kobe 6 USC PE",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-USC-PE.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1663002910",
        "description": "",
        "url": "nike-kobe-6-usc-pe",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-usc-pe",
        "make": "Nike Kobe 6",
        "retailPrice": "",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-usc-pe"
        },
        "releaseDate": "2011-03-01"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d72a",
        "name": "Nike Kobe 6 Prelude All-Star MVP (GS)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "650",
        "images": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Prelude-All-Star-MVP-GS.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1617292834",
        "description": "",
        "url": "nike-kobe-6-prelude-all-star-mvp-gs",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-prelude-all-star-mvp-gs",
        "make": "Nike Kobe 6",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-prelude-all-star-mvp-gs"
        },
        "releaseDate": "2014-01-11"
    }
];

module.exports = kobe6Products