
const kobe8Products = [
    {
        "_id": "64c9d60c64ce863dd80f3c84",
        "name": "Nike Kobe 8 What the Kobe (WTK)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1390",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-What-the-Kobe-Product.jpg",
        "description": "The Kobe 8 System Premium 'What The Kobe' combines nearly 30 colorways from previous Kobe 8 releases. The right shoe emerges with an Electric Orange base complemented by a Volt Swoosh, with various shades of red and green throughout. The darker left shoe sports a Deep Night base with an Electric Orange Swoosh, with various shades of blue throughout.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-what-the-kobe-wtk",
        "resellLinks.stockX": "https://stockx.com/kobe-8-what-the-kobe-wtk",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-12-06"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c85",
        "name": "Nike Kobe 8 SS Christmas (2013)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "570",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-SS-Christmas-2013-Product.jpg",
        "description": "The Nike Kobe 8 SS ‘Christmas’ rings in the holidays with an especially scaly translucent overlay atop a black and white knit upper. A subtle snakeskin texture is used on the black leather collar, while contrasting pops of Electric Green appear on the shoe’s branding elements and rubber outsole. Additional green speckled detailing coats the black midsole.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-ss-christmas-2013",
        "resellLinks.stockX": "https://stockx.com/kobe-8-ss-christmas-2013",
        "make": "Nike Kobe 8 SS",
        "retailPrice": "160",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-12-26"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c86",
        "name": "Nike Kobe 8+ All-Star Area 72",
        "brand": "Nike",
        "lowestResellPrice.stockX": "600",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Kobe-8-All-Star-Area-72-Product.jpg",
        "description": "Part of the Area 72 collection, the Kobe 8 System+ 'All Star - Extraterrestrial' plays off the 2013 NBA All-Star Game's host city of Houston. The shoe's Engineered Mesh upper features an orange and white swirling design modeled after the surface of a planet, accented by Sport Turquoise hits sporting unique details. The contrasting white midsole houses Zoom Air, while the lining and insole feature an interstellar graphic.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-all-star-area-72",
        "resellLinks.stockX": "https://stockx.com/kobe-8-all-star-area-72",
        "make": "Nike Kobe 8+",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-02-15"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c87",
        "name": "Nike Kobe 8 Easter",
        "brand": "Nike",
        "lowestResellPrice.stockX": "600",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Easter-Product.jpg",
        "description": "The Nike Kobe 8 System ‘Easter’ takes inspiration from the springtime holiday with a gradient tri-color finish on the one-piece engineered mesh upper. The purple, gold and teal hues are contrasted by a speckled black midsole, built with Nike Lunarlon for lightweight cushioning. Underfoot, a rubber outsole is finished in a snake scale-like traction pattern.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-easter",
        "resellLinks.stockX": "https://stockx.com/kobe-8-easter",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-03-29"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c88",
        "name": "Nike Kobe 8 Year of the Horse",
        "brand": "Nike",
        "lowestResellPrice.stockX": "430",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Year-of-the-Horse-Product.jpg",
        "description": "Releasing on New Year's Day 2014, the Kobe 8 System 'Year of the Horse' celebrates the Chinese zodiac. Featuring a Light Crimson Engineered Mesh upper accented by Bright Citron on the branding, the colorway reflects the colors traditionally used in Chinese New Year celebrations. Vivid Blue emerges on the lining and outsole, with Lunarlon and a heel counter supporting the fit.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-year-of-the-horse",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-year-of-the-horse",
        "make": "Nike Kobe 8",
        "retailPrice": "160",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2014-01-01"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c89",
        "name": "Nike Kobe 8 EXT Year of the Snake (Black)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "617",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-EXT-Year-of-the-Snake-Black-Product.png",
        "description": "The Zoom Kobe 8 EXT 'Year of the Snake' helped celebrate Lunar New Year 2013, with an appropriate design for the signature shoe of the player nicknamed 'Black Mamba.' The resulting upper emerges almost entirely in black, with snakeskin detailing featured throughout. Rough suede is used on the lateral-side Swoosh and Kobe branding at the heel, while purple on the outsole adds a touch of Los Angeles Lakers flavor.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-ext-year-of-the-snake-black",
        "resellLinks.stockX": "https://stockx.com/kobe-8-ext-year-of-the-snake-black",
        "make": "Nike Kobe 8 EXT",
        "retailPrice": "150",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-03-09"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c8a",
        "name": "Nike Kobe 8 Playoffs Purple Platinum",
        "brand": "Nike",
        "lowestResellPrice.stockX": "899",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Purple-Platinum-Product.jpg",
        "description": "Released during the 2013 playoffs, the Kobe 8 System 'Playoff' features an Engineered Mesh upper finished in a purple gradient snakeskin print. The two-tone midsole includes purple speckling, with Lunarlon providing cushioning.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-playoffs-purple-platinum",
        "resellLinks.stockX": "https://stockx.com/kobe-8-playoffs-purple-platinum",
        "make": "Nike Kobe 8 Playoffs",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-05-11"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c8b",
        "name": "Nike Kobe 8 Christmas (2012)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "528",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Christmas-Product.jpg",
        "description": "Releasing in late December 2012, the Kobe 8 System 'Christmas' features a vibrant mix of colors on its Engineered Mesh upper. Although seasonally appropriate, the look is actually modeled after the rhinoceros viper. Accented by Bright Crimson on the Swoosh and laces, the speckled Lunarlon midsole gives way to a bright green outsole.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-christmas-2012",
        "resellLinks.stockX": "https://stockx.com/kobe-8-christmas-2012",
        "make": "Nike Kobe 8",
        "retailPrice": "150",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2012-12-26"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c8c",
        "name": "Nike Kobe 8 Mine Grey",
        "brand": "Nike",
        "lowestResellPrice.stockX": "589",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Mine-Grey-Product.jpg",
        "description": "The Kobe 8 'Mine Grey' features a graphic snakeskin print throughout its Engineered Mesh upper, which emerges in a greyscale pattern based in Mine Grey. Court Purple on the laces and University Red on the heel counter adds color to the look, with both hues combining on the speckled Lunarlon midsole. The outsole sports a snake scale and herringbone traction pattern.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-mine-grey",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-mine-grey",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-11-30"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c8d",
        "name": "Nike Kobe 8 Sulfur / Electric",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1312",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Sulfer-Electric-Product.jpg",
        "description": "The Kobe 8 System 'Sulfur Electric' puts a vibrant contrasting look on the snakeskin-inspired pattern on its Engineered Mesh upper. Finished in a mix of black and Vivid Sulfer, an anatomical heel counter supports the fit. Vivid Grey adds a subtle accent to the Swoosh and heel, while full-length Lunarlon, reinforced with a glass composite shank, provides cushioning and stability underfoot. A thin web rubber outsole in further Vivid Sulfer provides traction.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-sulfur-electric",
        "resellLinks.stockX": "https://stockx.com/kobe-8-sulfur-electric",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2012-12-20"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c8e",
        "name": "Nike Kobe 8 Mambacurial",
        "brand": "Nike",
        "lowestResellPrice.stockX": "537",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Mambacurial-Product.png",
        "description": "The Kobe 8 System MC ‘Mambacurial’ reflects the athlete’s interest in the sport of soccer. Borrowing design elements from the Nike Mercurial Vapor 9 soccer boot, the low-top sports a gradient finish on the engineered mesh upper that transitions from Red Plum to Pink Flash. Contrasting pops of Electric Green appear on the forefoot Swoosh, padded tongue and rubber outsole.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-mambacurial",
        "resellLinks.stockX": "https://stockx.com/kobe-8-mambacurial",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-06-07"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c8f",
        "name": "Nike Kobe 8 Black History Month",
        "brand": "Nike",
        "lowestResellPrice.stockX": "730",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Black-History-Month-Product.jpg",
        "description": "Part of the 2013 Black History Month Collection, the Kobe 8 System 'BHM' features an African-style print throughout its Anthracite and Sport Grey Engineered Mesh upper. The stabilizing heel counter emerges in Total Orange, matched by the patterned laces, lining and Lunarlon midsole. The side wall sports a Pure Platinum Swoosh.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-black-history-month",
        "resellLinks.stockX": "https://stockx.com/kobe-8-black-history-month",
        "make": "Nike Kobe 8",
        "retailPrice": "160",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-01-26"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c90",
        "name": "Nike Kobe 8 Prelude (Reflection)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "776",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Prelude-Reflection-Product.jpg",
        "description": "Inspired by contemporary art, the Kobe 8 System 'Prelude' features a vibrant swirling design on its Engineered Mesh upper. The chrome finish on the heel counter is designed to symbolize Kobe Bryant's period of reflection after suffering various injuries during the 2012-2013 season, while Volt on the Swoosh brings added color to the look. The outsole spors a red to purple gradient to finish off the design.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-prelude-reflection",
        "resellLinks.stockX": "https://stockx.com/kobe-8-prelude-reflection",
        "make": "Nike Kobe 8",
        "retailPrice": "200",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2014-01-25"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c91",
        "name": "Nike Kobe 8 GC Venice Beach",
        "brand": "Nike",
        "lowestResellPrice.stockX": "800",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Venice-Beach.jpg",
        "description": "The tie-dye pattern throughout the Engineered Mesh upper of the Kobe 8 System ‘Venice Beach’ takes its cue from the graffiti seen on the Venice Beach Boardwalk. The seamless, breathable design mixes red, blue, green and yellow with Stadium Grey, while more blue emerges on the heel counter and the midsole, which is designed to accommodate drop-in Lunarlon cushioning. A red and yellow pattern emerges on the laces.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-gc-venice-beach",
        "resellLinks.stockX": "https://stockx.com/kobe-8-gc-venice-beach",
        "make": "Nike Kobe 8 GC",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-05-25"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c92",
        "name": "Nike Kobe 8 Elite+ Black Gold",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1400",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Elite-Black-Gold-Product.jpg",
        "description": "The Kobe 8 System Elite+ 'Away' features an elevated two-tone colorway, with its black Engineered Mesh upper highlighted by a metallic gold Swoosh, heel detailing and Kobe branding. Supported by a tonal heel counter, the tooling includes a full-length drop-in Lunarlon midsole. Exposed Flywire cables emerge at the lower eyelets.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-elite-black-gold",
        "resellLinks.stockX": "https://stockx.com/kobe-8-elite-black-gold",
        "make": "Nike Kobe 8 Elite+",
        "retailPrice": "220",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-06-01"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c93",
        "name": "Nike Kobe 8 Pit Viper",
        "brand": "Nike",
        "lowestResellPrice.stockX": "750",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Pit-Viper.jpg",
        "description": "The Kobe 8 System 'Pit Viper' features an Engineered Mesh upper in Raspberry Red that's been patterned with a snakeskin design. Contrasted by a Green Glow Swoosh, heel and inner lining, more Raspberry Red emerges on the supportive heel counter. The laces, toe overlay and Lunarlon midsole are finished in complementary System Purple.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-pit-viper",
        "resellLinks.stockX": "https://stockx.com/kobe-8-pit-viper",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-10-05"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c94",
        "name": "Nike Kobe 8 Year of the Snake (Port)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "499",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Year-of-the-Snake-Port-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-year-of-the-snake-port",
        "resellLinks.stockX": "https://stockx.com/kobe-8-year-of-the-snake-port",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-03-09"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c95",
        "name": "Nike Kobe 8 Black Mamba Collection Fade to Black",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1074",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Fade-To-Black-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-black-mamba-collection-fade-to-black",
        "resellLinks.stockX": "https://stockx.com/kobe-8-black-mamba-collection-fade-to-black",
        "make": "Nike Kobe 8",
        "retailPrice": "200",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2016-04-08"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c96",
        "name": "Nike Kobe 8 Graffiti",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1500",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Graffiti.jpg",
        "description": "The Kobe 8 'Graffiti' emerges with a greyscale graffiti-style design throughought its Engineered Mesh upper. Accented by Flash Lime on the Swoosh, lining and heel, a black heel counter is included for stability. Full-length drop-in Lunarlon provides cushioning, while a mico-tread outsole provides traction.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-graffiti",
        "resellLinks.stockX": "https://stockx.com/kobe-8-graffiti",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-08-24"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c97",
        "name": "Nike Kobe 8 Blue Blitz",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1111",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Blitz-Blue-Product.jpg",
        "description": "The Kobe 8 System 'Blitz Blue' puts a vibrant colorway on its lightweight performance construction, which comes in at just 9.6 ounces. The shoe's Engineered Mesh upper appears in Blitz Blue, with a Total Crimson Swoosh cutting through the side wall. A padded collar is included for comfort, while navy emerges on the stabilizing heel counter, matched by the speckled Lunarlon midsole. A translucent outsole provides traction.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-blue-blitz",
        "resellLinks.stockX": "https://stockx.com/kobe-8-blue-blitz",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-06-29"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c98",
        "name": "Nike Kobe 8 Barcelona Tiger",
        "brand": "Nike",
        "lowestResellPrice.stockX": "750",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Barcelona-Tiger-Product.png",
        "description": "The Kobe 8 System 'Barcelona' features a tiger stripe pattern on its vibrant yellow midsole. Emerging with a Midnight Navy mesh upper, the shoe is accented by red on the external heel counter, while the heel and tongue both incorporate leather applications. All three colors come together on the laces as well as the Kobe branding on the tongue.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-barcelona-tiger",
        "resellLinks.stockX": "https://stockx.com/kobe-8-barcelona-tiger",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-09-07"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c99",
        "name": "Nike Kobe 8+ Supernatural",
        "brand": "Nike",
        "lowestResellPrice.stockX": "5639",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Supernatural-Product.png",
        "description": "The Kobe 8 System+ 'Green Camo' released in 2013 alongside several other colorways. Featuring a Dark Atomic Teal knit upper that works a camo print into the design, a lighter Atomic Teal is featured on the midsole, heel counter and laces. The Swoosh, heel and branding add contrast in yellow, while Lunarlon provides cushioning.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-supernatural",
        "resellLinks.stockX": "https://stockx.com/kobe-8-supernatural",
        "make": "Nike Kobe 8+",
        "retailPrice": "160",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-03-02"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c9a",
        "name": "Nike Kobe 8 Elite Supehero",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1125",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Elite-Superhero-Product.jpg",
        "description": "The Kobe 8 System Elite ‘Superhero’ celebrates Kobe Bryant’s prodigious abilities with an eye-catching Poison Green finish on the shoe’s engineered mesh upper, supported with no-sew synthetic overlays and dynamic Flywire in a matching hue. Details include a black reptilian leather Swoosh and speckled heel counter. Lightweight cushioning comes courtesy of a lightweight Lunarlon.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-elite-supehero",
        "resellLinks.stockX": "https://stockx.com/kobe-8-elite-supehero",
        "make": "Nike Kobe 8 Elite",
        "retailPrice": "200",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-04-27"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c9c",
        "name": "Nike Kobe 8 Milk Snake",
        "brand": "Nike",
        "lowestResellPrice.stockX": "725",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Milk-Snake-Boa-Product.jpg",
        "description": "The Kobe 8 System 'Milk Snake' plays off Kobe Bryant's 'Black Mamba' nickname with a digitzed pattern designed to resemble the skin of a milk snake. The Engineered Mesh upper features a mix of University Red, black and Sail throughout its construction, while the fit is supported by an anatomical heel counter and a Lunarlon midsole. A glass composite shank is included for added stability.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-milk-snake",
        "resellLinks.stockX": "https://stockx.com/kobe-8-milk-snake",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-07-27"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c9d",
        "name": "Nike Kobe 8 Blue Glow",
        "brand": "Nike",
        "lowestResellPrice.stockX": "776",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Blue-Glow.jpg",
        "description": "The Nike Kobe 8 System ‘Blue Coral Snake’ features a two-tone design on an engineered mesh upper. The snakeskin-like pattern is accented by a metallic silver Swoosh, along with Kobe’s signature printed in matching silver atop the external heel counter. A full-length Lunarlon midsole is reinforced underfoot by a thin rubber outsole that combines herringbone and reptilian-scale treads.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-blue-glow",
        "resellLinks.stockX": "https://stockx.com/kobe-8-blue-glow",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-02-23"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c9e",
        "name": "Nike Kobe 8 Volt",
        "brand": "Nike",
        "lowestResellPrice.stockX": "2500",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Volt-Product.jpg",
        "description": "The Kobe 8 System 'Grey Camo' features a greyscale colorway with vibrant accents. The shoe's Engineered Mesh upper emerges with camo pattern throughout, with the Swoosh and heel counter contrasting the look in Volt. Underfoot, both grey and Volt appear on the Lunarlon midsole, with the outsole combining a herringbone and snake scale pattern underfoot.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-volt",
        "resellLinks.stockX": "https://stockx.com/kobe-8-volt",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-03-09"
    },
    {
        "_id": "64c9d60c64ce863dd80f3c9f",
        "name": "Nike Kobe 8 Python",
        "brand": "Nike",
        "lowestResellPrice.stockX": "615",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Python-Product.jpg",
        "description": "While Kobe Bryant will always be associated with the Black Mamba, the Kobe 8 System ‘Python’ carries an engineered mesh upper that recalls a different species of deadly snake. The kicks dropped in February 2013 to ring in the year of the snake, featuring a mix of olive and dark brown tones that are accented by a bright red Swoosh, matching the branding elements on the tongue and heel counter.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-python",
        "resellLinks.stockX": "https://stockx.com/kobe-8-python",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-02-06"
    },
    {
        "_id": "64c9d60c64ce863dd80f3ca0",
        "name": "Nike Kobe 8 System Green Glow Laser Orange",
        "brand": "Nike",
        "lowestResellPrice.stockX": "7500",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-System-Green-Glow-Laser-Orange-Product.jpg",
        "description": "Reflecting Kobe Bryant’s Black Mamba persona, the Kobe 8 ‘Green Glow’ features a distinctive snakeskin print on the low-top’s engineered mesh upper. The shoe’s tongue tag amplifies the reptilian theme, depicting a snaked coiled around Kobe’s personal logo. Contrasting the predominantly green color scheme are pops of Laser Orange on the Swoosh, collar lining and outsole.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-system-green-glow-laser-orange",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-system-green-glow-laser-orange",
        "make": "Nike Kobe 8 System",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-12-20"
    },
    {
        "_id": "64c9d60c64ce863dd80f3ca1",
        "name": "Nike Kobe 8 Sport Pack All-Star (2013)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1028",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Sport-Pack-All-Star-2013-Product.jpg",
        "description": "The Kobe 8 System+ Sp Pk As 'Extraterrestrial W/ Sport Pack' released for the 2013 NBA All-Star Game, which was held in Houtson, Texas. The shoe's Engineered Mesh upper is finished with a Bright Citrus and Total Crimson swirling upper that recalls an alien planet. The laces, Swoosh and lining are finished in Sport Turquoise, while a Lunarlon midsole provides cushioning underfoot. The shoe also incorporates Nike Sport Pack technology, with sensors that relay information to the Nike+ system.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-sport-pack-all-star-2013",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-sport-pack-all-star-2013",
        "make": "Nike Kobe 8",
        "retailPrice": "280",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-02-15"
    },
    {
        "_id": "64c9d60c64ce863dd80f3ca2",
        "name": "Nike Kobe 8 All-Star (2013) (GS)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1200",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-All-Star-2013-GS.png",
        "description": "Celebrating the 2013 NBA All-Star Game in Houston, the Kobe 8 GS ‘Extraterrestrial’ takes on an interstellar design theme, highlighted by an all-over graphic depicting the swirling orange and yellow atmosphere of an alien planet. Contrasting pops of Sport Turquoise appear on the laces, Swoosh and collar lining, while the rubber outsole is finished in a vibrant shade of Total Crimson.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-all-star-2013-gs",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-all-star-2013-gs",
        "make": "Nike Kobe 8",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-02-15"
    },
    {
        "_id": "64c9d60c64ce863dd80f3ca3",
        "name": "Nike Kobe 8 Prelude Reflection (GS)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1115",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Kobe-8-Prelude-Reflection-GS.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-prelude-reflection-gs",
        "resellLinks.stockX": "https://stockx.com/kobe-8-prelude-reflection-gs",
        "make": "Nike Kobe 8",
        "retailPrice": "135",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": ""
    },
    {
        "_id": "64c9d60c64ce863dd80f3ca4",
        "name": "Nike Kobe 8 System Philippines",
        "brand": "Nike",
        "lowestResellPrice.stockX": "615",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-System-Philippines.png",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-system-philippines",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-system-philippines",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-01-01"
    },
    {
        "_id": "64c9d60c64ce863dd80f3ca5",
        "name": "Nike Kobe 8 Challenge Red",
        "brand": "Nike",
        "lowestResellPrice.stockX": "482",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Challenge-Red-Product.jpg",
        "description": "The Kobe 8 System 'Challenge Red' puts a unique black and Challege Red mix throughout its Engineered Mesh construction. Accented by Reflect Silver on the Swoosh and heel detailing, a black heel counter supports the fit. Underfoot, the Lunarlon midsole sports red speckling, while the outsole includes a herringbone and snake scale traction pattern.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-challenge-red",
        "resellLinks.stockX": "https://stockx.com/kobe-8-challenge-red",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-06-15"
    },
    {
        "_id": "64c9d60c64ce863dd80f3ca6",
        "name": "Nike Kobe 8 NSW Gorge Green",
        "brand": "Nike",
        "lowestResellPrice.stockX": "240",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-NSW-Gorge-Green.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-nsw-gorge-green",
        "resellLinks.stockX": "https://stockx.com/kobe-8-nsw-gorge-green",
        "make": "Nike Kobe 8 NSW",
        "retailPrice": "110",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-06-15"
    },
    {
        "_id": "64c9d60c64ce863dd80f3ca7",
        "name": "Nike Kobe 8 NSW Mexican Blanket",
        "brand": "Nike",
        "lowestResellPrice.stockX": "245",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-NSW-Mexican-Blanket.jpg",
        "description": "The Kobe 8 Nsw Lifestyle Le 'Mexican Blanket' emerges with inspiration from south of the border, featuring a vibrant multicolor canvas upper inspired by the colorful serape. The low-top features contrasting brown on its leather heel panel, while Mamba and Swoosh branding are subtly worked into the look. A white rubber cupsole adds cushioning and further contrast.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-nsw-mexican-blanket",
        "resellLinks.stockX": "https://stockx.com/kobe-8-nsw-mexican-blanket",
        "make": "Nike Kobe 8 NSW",
        "retailPrice": "110",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-06-01"
    },
    {
        "_id": "64c9d60c64ce863dd80f3ca8",
        "name": "Nike Kobe 8 Shanghai Fireworks",
        "brand": "Nike",
        "lowestResellPrice.stockX": "8888",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Shanghai-Fireworks.jpg",
        "description": "The Kobe 8 System ‘Spark’ leverages its one-piece Engineered Mesh upper to highlight interesting all-over graphics, like this yellow, orange and red design that calls to mind an electrical current. An external heel counter supports the lightweight build, adorned with a black Swoosh on the side panel. It all rests on a full-length Lunarlon midsole in matching orange.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-shanghai-fireworks",
        "resellLinks.stockX": "https://stockx.com/kobe-8-shanghai-fireworks",
        "make": "Nike Kobe 8",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-09-01"
    },
    {
        "_id": "64c9d60c64ce863dd80f3ca9",
        "name": "Nike Kobe 8 System GC Christmas Solid Outsole (Asia Release) (2012)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1336",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-System-GC-Christmas-2012-Solid-Outsole-Asia-Release.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-system-gc-christmas-2012-solid-outsole-asia-release",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-system-gc-christmas-2012-solid-outsole-asia-release",
        "make": "Nike Kobe 8 System GC",
        "retailPrice": "150",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2012-12-26"
    },
    {
        "_id": "64c9d60c64ce863dd80f3caa",
        "name": "Nike Kobe 8 System Phillippines Grey Team Orange",
        "brand": "Nike",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-System-Phillippines-Grey-Team-Orange.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-system-phillippines-grey-team-orange",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-system-phillippines-grey-team-orange",
        "make": "Nike Kobe 8 System",
        "retailPrice": "225",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-09-07"
    },
    {
        "_id": "64c9d60c64ce863dd80f3cab",
        "name": "Nike Kobe 8 System Philippines Black Silver",
        "brand": "Nike",
        "lowestResellPrice.stockX": "666",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-System-Philippines-Black-Silver.jpg",
        "description": "Part of the Philippines Pack, the Kobe 8 System 'Philippines Black Silver' features a black Engineered Mesh upper accented by white zigzag detailing on the Lunarlon midsole and inner lining. Supported by an external heel counter in silver, the outsole includes a snake scale and herringbone pattern for traction.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-system-philippines-black-silver",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-system-philippines-black-silver",
        "make": "Nike Kobe 8 System",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2014-06-01"
    },
    {
        "_id": "64c9d60c64ce863dd80f3cac",
        "name": "Nike Kobe 8 EXT Year of the Snake (Red)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "750",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-EXT-Year-of-the-Snake-Red-Product.jpg",
        "description": "The Zoom Kobe 8 EXT 'Year Of The Snake' releaesed for Chinese New Year 2013, with a zodiac animal appropriate for Kobe Bryant's 'Black Mamba' nickname. The vibrant University Red colorway emerges on a suede build rather than the usual mesh, with tan accents on the branding. Underfoot, the purple tooling incorporates a Zoom midsole with a herringbone and snakeskin traction pattern.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-ext-year-of-the-snake-red",
        "resellLinks.stockX": "https://stockx.com/kobe-8-ext-year-of-the-snake-red",
        "make": "Nike Kobe 8 EXT",
        "retailPrice": "150",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-03-09"
    },
    {
        "_id": "64c9d60c64ce863dd80f3cad",
        "name": "Nike Kobe 8 Pit Viper (GS)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Pit-Viper-GS.png",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-pit-viper-gs",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-pit-viper-gs",
        "make": "Nike Kobe 8",
        "retailPrice": "115",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-10-05"
    },
    {
        "_id": "64c9d60c64ce863dd80f3cae",
        "name": "Nike Kobe 8 System+ SP Supernatural",
        "brand": "Nike",
        "lowestResellPrice.stockX": "5000",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-System-SP-Supernatural-Product.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-system-sp-supernatural",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-system-sp-supernatural",
        "make": "Nike Kobe 8 System+ SP",
        "retailPrice": "230",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-03-02"
    },
    {
        "_id": "64c9d60c64ce863dd80f3caf",
        "name": "Nike Kobe 8 Christmas (2012) (GS)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "429",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Christmas-2012-GS.png",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-christmas-2012-gs",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-christmas-2012-gs",
        "make": "Nike Kobe 8",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2012-12-26"
    },
    {
        "_id": "64c9d60c64ce863dd80f3cb0",
        "name": "Nike Kobe 8 SS Christmas (2013) (GS)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "699",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-SS-Christmas-2013-GS-Product.jpg",
        "description": "The Kobe 8 GS 'Christmas' is a grade-school shoe with a metallic silver finish throughout its 3D snakeskin-patterned upper. Highlighted by an Electric Green Swoosh, a metallic gold accent emerges on the heel. The Lunarlon midsole sports speckled detailing, with more Electric Green on the outsole.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-ss-christmas-2013-gs",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-ss-christmas-2013-gs",
        "make": "Nike Kobe 8 SS",
        "retailPrice": "115",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-12-26"
    },
    {
        "_id": "64c9d60c64ce863dd80f3cb1",
        "name": "Nike Kobe 8 Mine Grey (GS)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Kobe-8-Mine-Grey-GS.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "kobe-8-mine-grey-gs",
        "resellLinks.stockX": "https://stockx.com/kobe-8-mine-grey-gs",
        "make": "Nike Kobe 8",
        "retailPrice": "",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": ""
    },
    {
        "_id": "64c9d60c64ce863dd80f3cb2",
        "name": "Nike Kobe 8 Protro Triple White",
        "brand": "Nike",
        "lowestResellPrice.stockX": "",
        "image": "https://stockx-assets.imgix.net/media/Product-Placeholder-Default-20210415.jpg",
        "description": "Presenting the Nike Kobe 8 Protro 'Triple White,' a reimagined iteration of Kobe Bryant's eighth signature shoe in a clean, pristine colorway. This low-top sneaker is designed by Eric Avar and features an all-white engineered mesh upper, intersected by Swoosh branding in a matching white tone. Paying homage to Kobe Bryant, his personal logo adorns the tongue while the external heel counter is inscribed with his signature. Performance-wise, the shoe offers exceptional features such as a drop-in React midsole and a carbon fiber shank atop an outsole with herringbone-patterned tread.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-protro-triple-white",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-protro-triple-white",
        "make": "Nike Kobe 8 Protro",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": ""
    },
    {
        "_id": "64c9d60c64ce863dd80f3cb3",
        "name": "Nike Kobe 8 NSW Lifestyle LE Snakeskin",
        "brand": "Nike",
        "lowestResellPrice.stockX": "500",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-NSW-Lifestyle-LE-Snakeskin.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-nsw-lifestyle-le-snakeskin",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-nsw-lifestyle-le-snakeskin",
        "make": "Nike Kobe 8 NSW Lifestyle LE",
        "retailPrice": "110",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-07-11"
    },
    {
        "_id": "64c9d60c64ce863dd80f3cb4",
        "name": "Nike Kobe 8 Graffiti (GS)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "399",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-Graffiti-GS.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-graffiti-gs",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-graffiti-gs",
        "make": "Nike Kobe 8",
        "retailPrice": "115",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-08-24"
    },
    {
        "_id": "64c9d60c64ce863dd80f3cb5",
        "name": "Nike Kobe 8 System Elite GC Superhero",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1060",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-System-Elite-GC-Superhero.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-system-elite-gc-superhero",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-system-elite-gc-superhero",
        "make": "Nike Kobe 8 System Elite GC",
        "retailPrice": "150",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-04-27"
    },
    {
        "_id": "64c9d60c64ce863dd80f3cb6",
        "name": "Nike Kobe 8 System TB Gorge Green",
        "brand": "Nike",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe8/Nike-Kobe-8-System-TB-Gorge-Green.jpg",
        "description": "",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-8-system-tb-gorge-green",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-8-system-tb-gorge-green",
        "make": "Nike Kobe 8 System TB",
        "retailPrice": "140",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe8",
            "slug": "nike-zoom-kobe-6-white-del-sol"
        },
        "releaseDate": "2013-10-16"
    }
]

module.exports = kobe8Products