const mcqueen =
    [
        {
            "_id": "64cfe93d03e7973baa66e211",
            "name": "Alexander McQueen Oversized Ivory Black",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "392",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Ivory-Black-Product.png",
            "description": "The Alexander McQueen Oversized Ivory Black is an oversized sneaker that is primarily made out of calf leather. The  Alexander McQueen Oversized Ivory Black sneaker a rounded rubber toe as well as a rubber sole. The majority of the shoe is a bright white color. On the heel of the shoe, there are black details. The shoe also has perforated air holes in order to help make them be more breathable. The Alexander McQueen Oversized Ivory Black also has white laces. The Alexander McQueen Oversized Ivory Black first became available on the market in December of 2019. This model of shoes had a starting retail price of $490.",
            "url": "alexander-mcqueen-oversized-ivory-black",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-ivory-black",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2019-03-02"
        },
        {
            "_id": "64cfe93d03e7973baa66e212",
            "name": "Alexander McQueen Oversized Ivory Black (Women's)",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "361",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Ivory-Black-W-Product.jpg",
            "description": "The Alexander McQueen Oversized Ivory Black W is an oversized sneaker for women primarily made from leather. The Alexander McQueen Oversized Ivory Black for women features a rounded rubber toe and also sole. A major part of the shoe is covered in a bright white color. At the heel of the shoe, you can find contrasting black details. It also has perforated air holes on the upper to enhance breathability. The eyelets have a 7-hole metal with wide flat laces and the Alexander McQueen logo printed on the tongue, back, and leather insole. The Alexander McQueen Oversized Ivory Black W was released on the December 4, 2019 at a retail price of $590.",
            "url": "alexander-mcqueen-oversized-ivory-black-w",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-ivory-black-w",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "590",
            "releaseDate": "2019-12-04"
        },
        {
            "_id": "64cfe93d03e7973baa66e213",
            "name": "Alexander McQueen Oversized Black",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "400",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Black-Product.jpg",
            "description": "The Alexander McQueen Oversized Black is a stylish and comfortable sneaker that is perfect for any casual occasion. Made from high-quality materials, this sneaker features a sleek black design that is both timeless and modern. The oversized sole provides excellent support and cushioning, making it ideal for all-day wear. Released on April 1, 2020, this sneaker has quickly become a favorite among fashion enthusiasts. With a retail price of $490, it is a premium product that is worth the investment. Whether you're looking for a stylish sneaker to wear on the streets or a comfortable shoe for everyday wear, the Alexander McQueen Oversized Black is an excellent choice.",
            "url": "alexander-mcqueen-oversized-black",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-black",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2020-04-01"
        },
        // {
        //     "_id": "64cfe93d03e7973baa66e214",
        //     "name": "Alexander McQueen Oversized Red",
        //     "brand": "Alexander McQueen",
        //     "lowestResellPrice.stockX": "350",
        //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Red-Product.jpg",
        //     "description": "The Alexander McQueen Oversized Red sneakers are a standalone release of an oversized sneaker by Alexander McQueen. The Red Alexander McQueen Oversized sneaker is crafted with premium materials, including a plush leather upper and a rubber sole. The shoe features an oversized, chunky sole and comes in a white colorway with perforations on each side. The heel tab is red and is made of leather and features Alexander McQueen branding. The tongue is padded and made of leather and comes under a flat-laced system. The Alexander McQueen Oversized Red sneakers were released on December 21, 2021 at a retail price of $490.",
        //     "url": "alexander-mcqueen-oversized-red",
        //     "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-red",
        //     "make": "Alexander McQueen Oversized",
        //     "retailPrice": "490",
        //     "releaseDate": "2021-12-21"
        // },
        {
            "_id": "64cfe93d03e7973baa66e215",
            "name": "Alexander McQueen Oversized Shock Pink (Women's)",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "388",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Shock-Pink-W-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-shock-pink-w",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-shock-pink-w",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "530",
            "releaseDate": "2021-10-10"
        },
        {
            "_id": "64cfe93d03e7973baa66e216",
            "name": "Alexander McQueen Oversized Black White",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "350",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Black-White-Product.jpg",
            "description": "The Alexander McQueen Oversized Black White is crafted of a calfskin leather upper featuring perforations on the quarter panels accenting its construction and adding to breathability. Its all-black finish is contrasted by a white calf leather heel accent, and the midsole is added to a black lace-up sneaker. The sneaker has a broad flat outsole made of white rubber and wide flat laces. The tongue and heel counter are finished with an Alexander McQueen signature. An extra pair of white shoelaces are supplied with the sneaker. The Alexander McQueen Oversized Black White was released on 8th October 2019 and retailed at the price of $490.",
            "url": "alexander-mcqueen-oversized-black-white",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-black-white",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2019-10-08"
        },
        {
            "_id": "64cfe93d03e7973baa66e217",
            "name": "Alexander McQueen Oversized Paris Blue",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "374",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Worker-Blue-Product.jpg",
            "description": "The Alexander McQueen Oversized Paris Blue was released as a part of the brand's permanent collection. The Paris Blue Alexander McQueen Oversized has an upper that is made from high-quality Italian leather and features a white colorway with blue accents. The upper also includes a suede overlay at the heel with the Alexander McQueen logo. The midsole of the Alexander McQueen Oversized Paris Blue is a chunky rubber sole that provides added height and support for the foot. The outsole is made of a durable rubber to provides traction and durability for the shoe. The outsole features a textured design that ensures maximum grip on various surfaces. The tongue is padded and the insole of the shoe is made from a leather material that conforms to the wearer's foot, providing comfort and support. The insole is also cushioned to add an extra layer of comfort for the foot. The Alexander McQueen Oversized Paris Blue was released on March 1st, 2020 at a retail price $490.",
            "url": "alexander-mcqueen-oversized-worker-blue",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-worker-blue",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2020-03-01"
        },
        // {
        //     "_id": "64cfe93d03e7973baa66e218",
        //     "name": "Alexander McQueen Oversized Black White Sole",
        //     "brand": "Alexander McQueen",
        //     "lowestResellPrice.stockX": "384",
        //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Black-White-Sole-Product.jpg",
        //     "description": "The Alexander McQueen Oversized Black White Sole is a stylish and comfortable sneaker that is perfect for any casual occasion. The shoe features a sleek black leather upper with a contrasting white sole that adds a touch of sophistication to the design. The oversized sole is made from durable rubber, providing excellent traction and support for the wearer. Released on March 24th, 2019, the Alexander McQueen Oversized Black White Sole has quickly become a fan favorite among sneaker enthusiasts. The retail price of $490 may seem steep, but the quality of the materials and craftsmanship make it a worthwhile investment for those who appreciate luxury footwear. Something we love about the Alexander McQueen Oversized Black White Sole is its versatility. It can be dressed up or down, making it a great addition to any wardrobe. Our experts think the best features of this shoe are its sleek design and comfortable fit. The standout feature of the Alexander McQueen Oversized Black White Sole is its oversized sole, which adds a unique touch to the overall look of the shoe. Overall, the Alexander McQueen Oversized Black White Sole is a must-have for anyone who appreciates high-quality footwear. Its timeless design and superior craftsmanship make it a great investment that will last for years to come.",
        //     "url": "alexander-mcqueen-oversized-black-white-sole",
        //     "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-black-white-sole",
        //     "make": "Alexander McQueen Oversized",
        //     "retailPrice": "490",
        //     "releaseDate": "2019-03-24"
        // },
        {
            "_id": "64cfe93d03e7973baa66e219",
            "name": "Alexander McQueen Oversized Patchouli (Women's)",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "353",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Multicolor-W-Product.jpg",
            "description": "The Alexander McQueen Oversized Multicolor W is a bold and eye-catching sneaker that is sure to turn heads. Released on April 1st, 2020, this shoe features a unique combination of colors and materials that make it stand out from the crowd. The upper of the shoe is made from a mix of leather and suede, with a multicolored design that includes shades of blue, green, pink, and yellow. The oversized sole is made from rubber and features a textured design that provides excellent traction and durability. One of the standout features of this shoe is its oversized silhouette, which gives it a bold and powerful look. The shoe also features a padded collar and tongue for added comfort, as well as a lace-up closure that ensures a secure fit. At a retail price of $590, the Alexander McQueen Oversized Multicolor W is a high-end sneaker that is sure to appeal to fashion-forward individuals who are looking for a unique and stylish shoe. Something we love about the Alexander McQueen Oversized Multicolor W is its bold and daring design, which is sure to make a statement wherever you go. Our experts also appreciate the high-quality materials and construction of this shoe, which make it a durable and long-lasting option for sneaker enthusiasts.",
            "url": "alexander-mcqueen-oversized-multicolor-w",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-multicolor-w",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "590",
            "releaseDate": "2020-04-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e21a",
            "name": "Alexander McQueen Oversized White Grey Blue (Women's)",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "354",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-Grey-Blue-W-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-grey-blue-w",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-grey-blue-w",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "590",
            "releaseDate": "2022-10-12"
        },
        {
            "_id": "64cfe93d03e7973baa66e21b",
            "name": "Alexander McQueen Oversized White (Women's)",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "372",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-W-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-w",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-w",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2021-10-06"
        },
        {
            "_id": "64cfe93d03e7973baa66e21c",
            "name": "Alexander McQueen Oversized Worker Blue (Women's)",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "347",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Worker-Blue-W-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-worker-blue-w",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-worker-blue-w",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2019-12-26"
        },
        {
            "_id": "64cfe93d03e7973baa66e21d",
            "name": "Alexander McQueen Oversized White Rose Gold (Women's)",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "344",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-Rose-Gold-W-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-rose-gold-w",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-rose-gold-w",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "470",
            "releaseDate": "2015-01-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e21e",
            "name": "Alexander McQueen Oversized Platform Black (Women's)",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "276",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Platform-Black-W.JPG?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1617298076",
            "description": "",
            "url": "alexander-mcqueen-oversized-platform-black-w",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-platform-black-w",
            "make": "Alexander McQueen Oversized Platform",
            "retailPrice": "469",
            "releaseDate": "2015-01-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e21f",
            "name": "Alexander McQueen Oversized Lead Pencil",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "398",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Lead-Pencil.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-lead-pencil",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-lead-pencil",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "590",
            "releaseDate": "2022-04-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e220",
            "name": "Alexander McQueen Oversized White",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "394",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-Product.jpg",
            "description": "Please Note: Extra laces must be included. Different laces may appear on the shoe.",
            "url": "alexander-mcqueen-oversized-white",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2020-04-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e221",
            "name": "Alexander McQueen Oversized Red (Women's)",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "265",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Red-W-Product.jpg",
            "description": "The Alexander McQueen Oversized Red W is a bold and stylish sneaker that is sure to turn heads. Released on January 1st, 2019, this shoe features a striking red colorway that is sure to make a statement. The oversized sole adds a unique touch to the design, while the premium materials ensure durability and comfort. The retail price for this shoe is $490, making it a high-end option for sneaker enthusiasts. Whether you're looking to make a fashion statement or simply want a comfortable and stylish shoe, the Alexander McQueen Oversized Red W is a great choice.",
            "url": "alexander-mcqueen-oversized-red-w",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-red-w",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2019-01-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e222",
            "name": "Alexander McQueen Oversized Shock Pink",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "380",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Shock-Pink-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-shock-pink",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-shock-pink",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "530",
            "releaseDate": "2020-06-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e223",
            "name": "Alexander McQueen Oversized White Metallic",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "298",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-Metallic-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-metallic",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-metallic",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "590",
            "releaseDate": "2019-03-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e224",
            "name": "Alexander McQueen Oversized Black Shiny Sole",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "521",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Black-Shiny-Sole-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-black-shiny-sole",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-black-shiny-sole",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "560",
            "releaseDate": "2020-08-26"
        },
        {
            "_id": "64cfe93d03e7973baa66e225",
            "name": "Alexander McQueen Oversized Light Gold",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "283",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Light-Gold.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-light-gold",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-light-gold",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2020-08-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e226",
            "name": "Alexander McQueen Oversized Triple Black",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "397",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Triple-Black-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-triple-black",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-triple-black",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2020-09-02"
        },
        {
            "_id": "64cfe93d03e7973baa66e227",
            "name": "Alexander McQueen Oversized White Dream Blue (Women's)",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "399",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-Dream-Blue-W-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-dream-blue",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-dream-blue",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2020-07-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e228",
            "name": "Alexander McQueen Oversized Black White Sole (Women's)",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "376",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Black-White-Sole-W-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-black-white-sole-w",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-black-white-sole-w",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2015-01-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e229",
            "name": "Alexander McQueen Oversized White Black Trim",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "370",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-Black-Trim-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-black-trim",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-black-trim",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "560",
            "releaseDate": "2020-08-04"
        },
        {
            "_id": "64cfe93d03e7973baa66e22a",
            "name": "Alexander McQueen Oversized White Warm Orange",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "408",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-Warm-Orange-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-warm-orange",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-warm-orange",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "570",
            "releaseDate": "2021-08-13"
        },
        {
            "_id": "64cfe93d03e7973baa66e22b",
            "name": "Alexander McQueen Oversized Clear Sole Black",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "301",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Clear-Sole-Black.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-clear-sole-black",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-clear-sole-black",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "560",
            "releaseDate": "2020-02-21"
        },
        {
            "_id": "64cfe93d03e7973baa66e22c",
            "name": "Alexander McQueen Oversized Light Gold (Women's)",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "332",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Light-Gold-W-Product.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-light-gold-w",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-light-gold-w",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "490",
            "releaseDate": "2020-03-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e22d",
            "name": "Alexander McQueen Oversized White Light Grey Croc",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "459",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-Light-Grey-Croc.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-light-grey-croc",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-light-grey-croc",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "540",
            "releaseDate": "2021-05-26"
        },
        {
            "_id": "64cfe93d03e7973baa66e22e",
            "name": "Alexander McQueen Oversized White Cedar",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "300",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-Cedar.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-cedar",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-cedar",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "590",
            "releaseDate": "2015-01-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e22f",
            "name": "Alexander McQueen Oversized Brown Suede",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "374",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Brown-Suede.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-brown-suede",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-brown-suede",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "590",
            "releaseDate": "2015-01-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e230",
            "name": "Alexander McQueen Oversized White Studd",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "555",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-Studd.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-studd",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-studd",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "620",
            "releaseDate": "2021-08-01"
        },
        {
            "_id": "64cfe93d03e7973baa66e231",
            "name": "Alexander McQueen Oversized White White Iridescent Silver",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "399",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-White-Iridescent-Silver.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-white-iridescent-silver",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-white-iridescent-silver",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "590",
            "releaseDate": "2022-08-19"
        },
        {
            "_id": "64cfe93d03e7973baa66e232",
            "name": "Alexander McQueen Oversized Suede Grey",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "553",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Suede-Grey.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-suede-grey",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-suede-grey",
            "make": "Alexander McQueen Oversized Suede",
            "retailPrice": "580",
            "releaseDate": "2022-03-09"
        },
        // {
        //     "_id": "64cfe93d03e7973baa66e233",
        //     "name": "Alexander McQueen Oversized Embroidered Black Silver",
        //     "brand": "Alexander McQueen",
        //     "lowestResellPrice.stockX": "412",
        //     "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-Embroidered-Black-Silver.jpg",
        //     "description": "",
        //     "url": "alexander-mcqueen-oversized-embroidered-black-silver",
        //     "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-embroidered-black-silver",
        //     "make": "Alexander McQueen Oversized",
        //     "retailPrice": "590",
        //     "releaseDate": "2022-03-04"
        // },
        {
            "_id": "64cfe93d03e7973baa66e234",
            "name": "Alexander McQueen Oversized White Iron",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "541",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-Iron.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-iron",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-iron",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "580",
            "releaseDate": "2021-11-30"
        },
        {
            "_id": "64cfe93d03e7973baa66e235",
            "name": "Alexander McQueen Oversized White Light Blue",
            "brand": "Alexander McQueen",
            "lowestResellPrice.stockX": "425",
            "image": "https://po-prod.s3.us-west-1.amazonaws.com/mcqueen/Alexander-McQueen-Oversized-White-Light-Blue.jpg",
            "description": "",
            "url": "alexander-mcqueen-oversized-white-light-blue",
            "resellLinks.stockX": "https://stockx.com/alexander-mcqueen-oversized-white-light-blue",
            "make": "Alexander McQueen Oversized",
            "retailPrice": "590",
            "releaseDate": "2021-11-30"
        }
    ]
module.exports = mcqueen