const nikeDunks = [
    {
        "_id": "64e81e0e37437752fdde3ec5",
        "name": "Nike SB Dunk Low Yuto Horigome",
        "brand": "Nike",
        "lowestResellPrice.stockX": "228",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Yuto-Horigome-Product.jpg",
        "description": "The Yuto Horigome x Nike Dunk Low SB collaboration showcases the Japanese pro skateboarder's interpretation of the timeless silhouette. The white leather upper is reinforced by grey suede overlays at the forefoot and heel. A cross-feather graphic on the lateral heel is accompanied by a distinctive leather Swoosh in grey, while Horigome's name appears on the Nike SB tongue tag. The pink suede back tab is stitched with a Nike wordmark that contrasts with the brown suede low-cut padded collar. Underfoot, a sturdy cupsole with white sidewalls rides on a grippy brown rubber outsole.",
        "url": "nike-sb-dunk-low-yuto-horigome",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-yuto-horigome",
        "make": "Nike SB Dunk Low",
        "retailPrice": "130",
        "releaseDate": "2023-08-29"
    },
    {
        "_id": "64e81e0e37437752fdde3ec6",
        "name": "Nike SB Dunk Low Pro White Gum",
        "brand": "Nike",
        "lowestResellPrice.stockX": "133",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-White-Gum-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-pro-white-gum",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-white-gum",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "110",
        "releaseDate": "2023-03-01"
    },
    {
        "_id": "64e81e0e37437752fdde3ec7",
        "name": "Nike SB Dunk Low Pro ISO Orange Label Court Purple",
        "brand": "Nike",
        "lowestResellPrice.stockX": "175",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-ISO-Orange-Label-Court-Purple-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-pro-iso-orange-label-court-purple",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-iso-orange-label-court-purple",
        "make": "Nike SB Dunk Low Pro ISO",
        "retailPrice": "110",
        "releaseDate": "2023-08-23"
    },
    {
        "_id": "64e81e0e37437752fdde3ec8",
        "name": "Nike SB Dunk Low Crenshaw Skate Club",
        "brand": "Nike",
        "lowestResellPrice.stockX": "220",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Crenshaw-Skate-Club-Product.jpg",
        "description": "Created with CSC founder Tobias McIntosh, the Crenshaw Skate club Nike Dunk Low SB features a tan suede upper intersected by cracked leather overlays that evoke a significant landmark in his LA neighborhood, the iconic Crenshaw Square sign. The blue-tinged translucent rubber outsole and the interior tongue feature an graphic paying homage to Tobey's childhood, with an illustration of a daycare scene. The tongue tags and back tabs display alternating Nike and CSC branding.",
        "url": "nike-sb-dunk-low-crenshaw-skate-club",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-crenshaw-skate-club",
        "make": "Nike SB Dunk Low",
        "retailPrice": "130",
        "releaseDate": "2023-08-05"
    },
    {
        "_id": "64e81e0e37437752fdde3ec9",
        "name": "Nike SB Dunk Low Pro Black Gum",
        "brand": "Nike",
        "lowestResellPrice.stockX": "110",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Black-Gum-Product.jpg",
        "description": "The Nike Dunk Low SB 'Black Gum' takes the classic silhouette and adds a practical color scheme composed of adaptable, understated tones. Smooth black nubuck forms the upper and is complemented by a Nike wordmark stitched onto the heel tab and a white leather Swoosh. The tongue is made of plush mesh and is well-padded, offering a comfortable fit. The sneaker's cupsole is standard, with white sidewalls and a tacky gum rubber outsole. The low-cut profile, combined with a Zoom Air unit nestled in the sockliner, ensures that each stride feels responsive and cushioned.",
        "url": "nike-sb-dunk-low-pro-black-gum",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-black-gum",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "110",
        "releaseDate": "2023-03-01"
    },
    {
        "_id": "64e81e0e37437752fdde3eca",
        "name": "Nike SB Dunk Low Orange Emerald Rise",
        "brand": "Nike",
        "lowestResellPrice.stockX": "128",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Orange-Emerald-Rise-Product.jpg",
        "description": "The Nike Dunk Low SB 'Orange Emerald Rise' introduces a distinctive texture with its plush suede upper. The base in Emerald Rise pairs with orange forefoot and heel overlays. Nike logo accents on the tongue tag and rear tab harmonized with the iconic Swoosh on the side. A robust rubber cupsole in a soft Lemon Chiffon hue combines with a strategically placed heel Zoom Air unit in the insole.",
        "url": "nike-sb-dunk-low-orange-emerald-rise",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-orange-emerald-rise",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2023-08-03"
    },
    {
        "_id": "64e81e0e37437752fdde3ecb",
        "name": "Nike SB Dunk Low Pro Why So Sad?",
        "brand": "Nike",
        "lowestResellPrice.stockX": "165",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-Why-So-Sad-Product.jpg",
        "description": "Scottish skateboarder John Rattray brings his commitment to mental health research and suicide prevention into shoe form with the Why So Sad? x Nike Dunk Low SB ‘The Predatory Bird.’ The bird graphic that inspired this low-top's name embellishes the lateral heel, while a lone question mark in yellow adorns the red suede heel tab. The leather upper in cheerful pastel blue and contrasting navy suede overlays has a Swoosh in Coastal Blue fading to Speed Yellow. The interior tongue tag features ‘Why So Sad?’ reflecting Rattray's crusade to bring issues of depression to light. The outsole in clear rubber provides grippiness whether in the bowl or on the street.",
        "url": "nike-sb-dunk-low-pro-why-so-sad",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-why-so-sad",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "120",
        "releaseDate": "2022-11-04"
    },
    {
        "_id": "64e81e0e37437752fdde3ecc",
        "name": "Nike SB Dunk Low Jarritos",
        "brand": "Nike",
        "lowestResellPrice.stockX": "311",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Jarritos-Product.jpg",
        "description": "A collaboration between Jarritos x Nike Dunk Low SB takes inspiration from the famous Mexican soda brand. The upper of the sneaker combines a Malachite green textile Swoosh against the upper of Phantom white leather with hemp canvas overlays. The lateral heel is embellished with the Jarritos logo stitched in green and orange, and the woven tongue tag has dual branding. Alternating heel tabs read 'Nike' and 'Jarritos.' The sneaker rides a sturdy rubber cupsole with white sidewalls atop a green and orange outsole.",
        "url": "nike-sb-dunk-low-jarritos",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-jarritos",
        "make": "Nike SB Dunk Low",
        "retailPrice": "130",
        "releaseDate": "2023-05-10"
    },
    {
        "_id": "64e81e0e37437752fdde3ecd",
        "name": "Nike SB Dunk Low Run The Jewels",
        "brand": "Nike",
        "lowestResellPrice.stockX": "155",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Run-The-Jewels-Product.jpg",
        "description": "The collaboration between Nike and Run The Jewels, a hip-hop duo made up of Killer Mike and El-P, results in the Run The Jewels x Nike Dunk Low SB ‘4/20.’ The low-top features a suede upper in an array of blue hues, with a contrasting hot pink textured nubuck Swoosh. The back tab is embroidered with a Nike wordmark in metallic gold, which matches the tongue’s woven Nike SB. Additional branding appears on the sole with an all-over ‘Run The Jewels’ print and a semi-clear rubber cupsole provides support.",
        "url": "nike-sb-dunk-low-run-the-jewels",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-run-the-jewels",
        "make": "Nike SB Dunk Low",
        "retailPrice": "130",
        "releaseDate": "2023-04-20"
    },
    {
        "_id": "64e81e0e37437752fdde3ece",
        "name": "Nike SB Dunk Low Concepts Orange Lobster",
        "brand": "Nike",
        "lowestResellPrice.stockX": "280",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Concepts-Orange-Lobster-Product.jpg",
        "description": "The Concepts x Nike Dunk Low SB ‘Orange Lobster’ updates this low-top classic as part of a longstanding collaboration with Harvard Square's oldest sneaker storefront. With lobsters as its inspiration, the sneaker is built on a nubuck upper in orange; the overlays have speckle patterning reminiscent of a lobster shell. The white tongue in breathable mesh and white-outlined orange Swoosh pair with the interior lining patterning resembling a lobster shack's requisite bib. Black sidewalls and rubber banding atop the toe box are nods to lobster claw bands. Traction is delivered via a rubber outsole in orange.",
        "url": "nike-sb-dunk-low-concepts-orange-lobster",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-concepts-orange-lobster",
        "make": "Nike SB Dunk Low",
        "retailPrice": "120",
        "releaseDate": "2022-12-20"
    },
    {
        "_id": "64e81e0e37437752fdde3ecf",
        "name": "Nike SB Dunk Low Mystic Red Rosewood",
        "brand": "Nike",
        "lowestResellPrice.stockX": "94",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Mystic-Red-Product.jpg",
        "description": "The Nike Dunk Low SB 'Mystic Red' replaces the usual leather construction with shaggy suede in a striking crimson shade. The signature Swoosh and padded tongue and heel tab Nike branding stand out in a vivid Emerald Rise hue. A sturdy rubber cupsole in a solid Rosewood color provides support for an interior foam insole with a Zoom Air unit in the heel.",
        "url": "nike-sb-dunk-low-mystic-red",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-mystic-red",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": ""
    },
    {
        "_id": "64e81e0e37437752fdde3ed0",
        "name": "Nike SB Dunk Low Pro ISO Orange Label Wolf Grey Gum",
        "brand": "Nike",
        "lowestResellPrice.stockX": "156",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-ISO-Orange-Label-Grey-Gum-Product.jpg",
        "description": "The Nike Dunk Low Pro ISO SB 'Wolf Grey Gum' gives a classic design a sophisticated and understated upgrade. The leather upper is infused with a muted grey hue and is highlighted with contrasting white details on the Nike-branded heel tab and signature Swoosh. A bold orange Swoosh on the woven Nike SB tag adds a pop of color to the padded tongue. The insole is adorned with Orange Label branding and features a resilient Zoom Air unit inside the heel. The low-profile silhouette is anchored by a traditional rubber cupsole with white sidewalls and a tacky gum rubber outsole.",
        "url": "nike-sb-dunk-low-pro-iso-orange-label-grey-gum",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-iso-orange-label-grey-gum",
        "make": "Nike SB Dunk Low Pro ISO",
        "retailPrice": "110",
        "releaseDate": "2023-02-24"
    },
    {
        "_id": "64e81e0e37437752fdde3ed1",
        "name": "Nike SB Dunk Low Sandy Bodecker",
        "brand": "Nike",
        "lowestResellPrice.stockX": "123",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-eBay-Sandy-Boedecker-Product.jpg",
        "description": "Honoring the legend behind Nike Skateboarding is the Nike Dunk Low SB ‘Sandy Bodecker,’ in a design inspired by and recreating the color scheme and build of the original and elusive eBay Dunk from 2003. The upper features patent-leather overlays in eBay’s ubiquitous colors intersected by clear cut-out panels that symbolize the original pair, which was destroyed at the ASR trade show in 2003. The interior of the shoe delivers photographs by James Arizumi which celebrate Sandy Bodecker’s legacy.",
        "url": "nike-sb-dunk-low-ebay-sandy-boedecker",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-ebay-sandy-boedecker",
        "make": "Nike SB Dunk Low",
        "retailPrice": "130",
        "releaseDate": "2022-12-17"
    },
    {
        "_id": "64e81e0e37437752fdde3ed2",
        "name": "Nike SB Dunk Low Pro QS Neckface",
        "brand": "Nike",
        "lowestResellPrice.stockX": "123",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-Dunk-SB-Low-Pro-QS-Neckface-Product.jpg",
        "description": "LA-based graffiti artist Neckface works with Nike SB again on a Dunk Low Pro SB. A black suede upper is the perfect base for a series of patches that feature Neckface's macabre artwork across the entire shoe. The tongue tags feature 'Neck SB' and 'Face SB' while the left shoe features a 'Shockers' graphic wrapped around the left midsole.",
        "url": "nike-dunk-sb-low-pro-qs-neckface",
        "resellLinks.stockX": "https://stockx.com/nike-dunk-sb-low-pro-qs-neckface",
        "make": "Nike SB Dunk Low Pro QS",
        "retailPrice": "120",
        "releaseDate": "2022-10-27"
    },
    {
        "_id": "64e81e0e37437752fdde3ed3",
        "name": "Nike SB Dunk Low Pro PRM 90s Backpack",
        "brand": "Nike",
        "lowestResellPrice.stockX": "95",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-Midnight-Navy-Desert-Ochre-Product.jpg",
        "description": "Inspired by '90s backpacks, the Nike Dunk Low SB 'Navy Desert Ochre' presents a color-blocked design. The shoe's upper blends camel-colored suede at the forefoot with durable navy textile at the back. A pull tab and a suede Nike SB tag can be found on the shoe, while the padded tongue boasts a secret stash pocket with a zip closure. The shoe's low-top design rests on a grippy outsole with an off-white rubber cupsole above featuring stitched sidewall construction.",
        "url": "nike-sb-dunk-low-pro-midnight-navy-desert-ochre",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-midnight-navy-desert-ochre",
        "make": "Nike SB Dunk Low Pro PRM",
        "retailPrice": "110",
        "releaseDate": "2023-05-09"
    },
    {
        "_id": "64e81e0e37437752fdde3ed4",
        "name": "Nike SB Dunk Low Pro Fly Streetwear Gardenia",
        "brand": "Nike",
        "lowestResellPrice.stockX": "159",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-Fly-Streetwear-Product.jpg",
        "description": "The Fly Streetwear x Nike Dunk Low Pro SB is a modern take on the classic shoe, created in collaboration with the Shanghai-based skate shop. Inspired by white jade orchid flowers sold on the streets of Shanghai, the shoe features a white leather upper secured by rope laces, contrasted with a lime green suede Nike-branded heel tab and blue suede overlays inspired by the flower's stalks and the blue cloth that lines the baskets they are sold in. The lateral heel is adorned with a flower earring graphic, complemented by a stitched flowery Swoosh. Fly Streetwear and Nike SB branding appear on the padded tongues’ alternating woven tags. Underfoot, a rubber cupsole with vintage off-white sidewalls and a white rubber outsole provide comfort and support.",
        "url": "nike-sb-dunk-low-pro-fly-streetwear",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-fly-streetwear",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "120",
        "releaseDate": "2023-03-25"
    },
    {
        "_id": "64e81e0e37437752fdde3ed5",
        "name": "Nike SB Dunk Low Adobe",
        "brand": "Nike",
        "lowestResellPrice.stockX": "100",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-Dunk-Low-Adobe-Product.jpg",
        "description": "Featuring an all-over Adobe Red hue across the upper, the Nike Dunk Low SB 'Adobe' is a playful rendition of a classic silhouette. A mix of leather, suede and mesh encompass the upper, while a gum rubber outsole provides durable traction. The sockliner features a variety of graphics that depict skateboard tools and general Do's and Don'ts, a fun reminder to have fun while skating. A woven Nike SB tag and NIKE stitched on the back heel complete the look.",
        "url": "nike-dunk-low-adobe",
        "resellLinks.stockX": "https://stockx.com/nike-dunk-low-adobe",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2023-02-22"
    },
    {
        "_id": "64e81e0e37437752fdde3ed6",
        "name": "Nike SB Dunk Low Los Angeles Dodgers",
        "brand": "Nike",
        "lowestResellPrice.stockX": "316",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Los-Angeles-Dodgers-Product.jpg",
        "description": "Inspired by the Los Angeles Dodgers MLB team, this NIke Dunk Low SB features colors and details from the storied franchise. The upper is constructed with a white leather base, with blue suede overlays and a blue textile Swoosh. The inside tongue tags feature a palm tree graphic on the left shoe and Dodger Stadium's welcome sign on the right shoe. A white midsole leads to a gum rubber outsole, with a small splotch of pink on the right shoe, depicting the look of bubblegum stuck on the heel.",
        "url": "nike-sb-dunk-low-los-angeles-dodgers",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-los-angeles-dodgers",
        "make": "Nike SB Dunk Low",
        "retailPrice": "120",
        "releaseDate": "2022-06-01"
    },
    {
        "_id": "64e81e0e37437752fdde3ed7",
        "name": "Nike SB Dunk Low Decon N7 Black Sail",
        "brand": "Nike",
        "lowestResellPrice.stockX": "181",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Decon-N7-Black-Sail-Product.jpg",
        "description": "Derived from the 2023 N7 Collection, the Nike Dunk Low Decon SB 'Sail Black' salutes indigenous communities through a sports lens. A collaborative endeavor with members of the Haudenosaunee Confederacy and Ojibwe communities, this deconstructed iteration of the Nike Dunk features a white canvas upper with matching leather elements forming the forefoot overlay and iconic Swoosh. Underneath, the sneaker's translucent rubber outsole unveils a striking black-and-white maple wood print. The toe box and heel overlay incorporate black synthetic suede adorned with multicolored embroidered floral patterns.",
        "url": "nike-sb-dunk-low-decon-n7-black-sail",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-decon-n7-black-sail",
        "make": "Nike SB Dunk Low Decon",
        "retailPrice": "110",
        "releaseDate": "2023-06-15"
    },
    {
        "_id": "64e81e0e37437752fdde3ed8",
        "name": "Nike SB Dunk Low HUF San Francisco",
        "brand": "Nike",
        "lowestResellPrice.stockX": "144",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-HUF-San-Francisco-Product.jpg",
        "description": "Recalling the first retail store opened by late professional skateboarder Keith Hufnagel, the HUF x Nike Dunk Low SB ‘San Francisco’ celebrates the Golden City and designer's iconic streetwear brand. The upper appears in tumbled leather in black and white. Against that low-key backdrop the SF Giants get a cameo with their ubiquitous font appearing on the heels in black and orange stitching above the etched SF skyline. On the toe box, HUF branding partners with a sparkling Swoosh while alternating Nike SB and HUF logos adorn the sockliners, in the brand's trademark lime-green. ‘Keith Forever’ is stitched on the heel tabs in the Giants’ trademark font in black and orange font.",
        "url": "nike-sb-dunk-low-huf-san-francisco",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-huf-san-francisco",
        "make": "Nike SB Dunk Low",
        "retailPrice": "130",
        "releaseDate": "2022-11-16"
    },
    {
        "_id": "64e81e0e37437752fdde3ed9",
        "name": "Nike SB Dunk Low Decon N7 Opti Yellow University Red",
        "brand": "Nike",
        "lowestResellPrice.stockX": "175",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Decon-N7-Opti-Yellow-University-Red-Product.jpg",
        "description": "Releasing as one pair in Nike's 2023 N7 Collection, the Nike Dunk Low Decon SB 'Sail University Red' introduces a collaboration with members of the Haudenosaunee Confederacy and Ojibwe communities. Embracing a deconstructed aesthetic, the low-top showcases an exposed-foam tongue and reduced collar padding. The white canvas upper is adorned with floral-embroidered suede overlays, while deco stitching frames the red leather Swoosh and N7-branded heel tab. The sneaker is grounded by a robust cupsole with pristine white sidewalls atop a translucent rubber outsole.",
        "url": "nike-sb-dunk-low-decon-n7-opti-yellow-university-red",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-decon-n7-opti-yellow-university-red",
        "make": "Nike SB Dunk Low Decon",
        "retailPrice": "110",
        "releaseDate": "2023-06-15"
    },
    {
        "_id": "64e81e0e37437752fdde3eda",
        "name": "Nike SB Dunk Low Pro Paisley Brown",
        "brand": "Nike",
        "lowestResellPrice.stockX": "164",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-Paisley-Brown-Product.jpg",
        "description": "An iconic skate favorite gets a bohemian makeover with the Nike Dunk Low Pro Premium SB ‘Paisley.’ Built on a gum rubber outsole, the textile upper is flooded with an allover paisley print in green, blue, pink and brown. Brown piping in leather will dissolve over time to reveal off-white suede in its place. The signatures Swoosh appears in white while ‘Nike’ appears on the leather heel tab in brown.",
        "url": "nike-sb-dunk-low-pro-paisley-brown",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-paisley-brown",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "130",
        "releaseDate": "2022-05-01"
    },
    {
        "_id": "64e81e0e37437752fdde3edb",
        "name": "Nike SB Dunk Low Crenshaw Skate Club (PS)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "109",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Crenshaw-Skate-Club-PS.jpg",
        "description": "The Crenshaw Skate Club x Nike Dunk Low SB PS for little kids showcases an upper in cream suede whose overlays with green and violet grip tape-inspired texture add a playful touch. The iconic Swoosh and back tab appear in pale blue and are adorned with alternating black-and-silver stitched Nike and CSC logos. The blue-tinted clear rubber outsoles reveal a cartoon graphic of a trio of children lifting building blocks, each labeled with the letters C, S, and C, a nod to the Crenshaw Skate Club's unity and spirit. The shoe's interior tongue tags and insoles feature custom CSC branding.",
        "url": "nike-sb-dunk-low-crenshaw-skate-club-ps",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-crenshaw-skate-club-ps",
        "make": "Nike SB Dunk Low",
        "retailPrice": "90",
        "releaseDate": "2023-08-05"
    },
    {
        "_id": "64e81e0e37437752fdde3edc",
        "name": "Nike SB Dunk Low Cherry",
        "brand": "Nike",
        "lowestResellPrice.stockX": "132",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Cherry-Product.jpg",
        "description": "The Nike Dunk Low Pro SB 'Cherry' is a pair in the 'Fruity Pack' designed to give the retro silhouette a fresh new look. This low-top version features a leather upper in crimson with suede overlays in burgundy at the forefoot and heel. The shoe is adorned with various branding elements, including a berry-red Swoosh, a playful cherry graphic on the interior tongue tag and a stitched Nike wordmark on the heel tab. Zoom Air cushioning is featured in the heel’s insole, while the burgundy rubber outsole ensures reliable traction whatever the activity.",
        "url": "nike-sb-dunk-low-cherry",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-cherry",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2022-07-09"
    },
    {
        "_id": "64e81e0e37437752fdde3edd",
        "name": "Nike SB Dunk Low Mummy",
        "brand": "Nike",
        "lowestResellPrice.stockX": "245",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-Dunk-SB-Low-Mummy-Product.jpg",
        "description": "Celebrate Halloween with a monster-inspired shoe in the Nike Dunk Low SB 'Mummy.' A off-white canvas upper has tonal decorative stitching with frayed edges that can be torn away to show a bluish-gray suede underlay that the Swoosh is made up of as well. The semi-translucent rubber cupsole and the pair of embroidered eyes on the back heel glow in the dark. Additional details include an embroidered spider on the left toe box and an ancient Egyptian Eye of Horus graphic on the interior tongue.",
        "url": "nike-dunk-sb-low-mummy",
        "resellLinks.stockX": "https://stockx.com/nike-dunk-sb-low-mummy",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2021-10-28"
    },
    {
        "_id": "64e81e0e37437752fdde3ede",
        "name": "Nike SB Dunk Low Polaroid",
        "brand": "Nike",
        "lowestResellPrice.stockX": "115",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Polaroid-Product.jpg",
        "description": "Inspired by the original instant camera, the Nike Dunk Low SB x Polaroid delivers a colorful take on the lifestyle skate shoe. The upper arrives in black nubuck, with white leather on the back heel piece featuring a debossed Polaroid photo logo. A stacked trio of colored Swooshes in red, yellow and blue adorn the profiles, while a small line of embroidery continues the technicolor theme. Co-branding can be found on the sockliner, along with 'Nike' and 'Polaroid' stitched on the back heel.",
        "url": "nike-sb-dunk-low-polaroid",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-polaroid",
        "make": "Nike SB Dunk Low",
        "retailPrice": "120",
        "releaseDate": "2022-04-12"
    },
    {
        "_id": "64e81e0e37437752fdde3edf",
        "name": "Nike SB Dunk Low Philadelphia Phillies",
        "brand": "Nike",
        "lowestResellPrice.stockX": "246",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Valour-Blue-Team-Maroon-Product.jpg",
        "description": "The Nike Dunk Low Premium SB 'Philadelphia Phillies' is inspired by vintage jerseys of the historic MLB team. The nubuck and suede upper features a light shade of Valor Blue, with a Team Maroon Swoosh outlined with white trim. A contrasting white midsole gives way to a gum rubber outsole where a small patch of pink on the right shoe signifies stepping in bubble gum. Nike SB tags on the outside of the tongue are matched with Philadephia inspired graphics on the inside tongue tags including a cheesesteak on the left shoe and a Liberty Bell on the right.",
        "url": "nike-sb-dunk-low-valour-blue-team-maroon",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-valour-blue-team-maroon",
        "make": "Nike SB Dunk Low",
        "retailPrice": "115",
        "releaseDate": "2022-07-26"
    },
    {
        "_id": "64e81e0e37437752fdde3ee0",
        "name": "Nike SB Dunk Low Pro Bart Simpson",
        "brand": "Nike",
        "lowestResellPrice.stockX": "202",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-Bart-Simpson-Product.jpg",
        "description": "Recalling the iconic 2008 ‘Marge’ Dunk and ‘Homer’ Dunk from 2004, the Nike Dunk Low SB ‘Bart Simpson’ honors the oldest of the Simpson children in an unmistakable colorway. Cushioning is provided by the Nike SB insole's Zoom Air unit in the heel. On the upper, Habanero Red overlays in suede stand out against a yellow leather base with the signature Swoosh in crisp white leather. Additional pops of color include Blue Hero on the rubber outsole and in the collar lining.",
        "url": "nike-sb-dunk-low-pro-bart-simpson",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-bart-simpson",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "110",
        "releaseDate": "2022-06-29"
    },
    {
        "_id": "64e81e0e37437752fdde3ee1",
        "name": "Nike SB Dunk Low Travis Scott (Regular Box)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1001",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Travis-Scott-Product.jpg",
        "description": "Travis Scott teamed up with Nike to create the Travis Scott x SB Dunk Low PRM QS 'Cactus Jack.' Featuring a patchwork design, the shoe's upper emerges with a tan suede base accented by plaid on the quarter panel and paisley on the overlays. The overlays themselves are designed to wear away and reveal an elephant print, while the lateral side Swoosh sports a pink finish. Cactus Jack branding emerges on the tongue tag, while a rubber outsole is included for traction.",
        "url": "nike-sb-dunk-low-travis-scott",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-travis-scott",
        "make": "Nike SB Dunk Low",
        "retailPrice": "150",
        "releaseDate": "2020-02-29"
    },
    {
        "_id": "64e81e0e37437752fdde3ee2",
        "name": "Nike SB Dunk Low Skate Like a Girl",
        "brand": "Nike",
        "lowestResellPrice.stockX": "184",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Skate-Like-a-Girl-Product.jpg",
        "description": "The founders of Skate Like a Girl, a female-founded nonprofit based in the Pacific Northwest, partnered with Nike to bring a new look and feel to the SB Dunk Low. A rich mix of materials, colors and artwork distinguish this skate shoe – a cream suede upper features overlays and a corduroy collar and tongue in violet, with a ridged scarlet Swoosh finishing the look. Branding includes Skate Like a Girl stitching on the tongue tag and linked-arm artwork by J Wu on the back heel. The shoe rides on a gum rubber outsole for traction.",
        "url": "nike-sb-dunk-low-skate-like-a-girl",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-skate-like-a-girl",
        "make": "Nike SB Dunk Low",
        "retailPrice": "130",
        "releaseDate": "2022-10-17"
    },
    {
        "_id": "64e81e0e37437752fdde3ee3",
        "name": "Nike SB Dunk Low Court Purple",
        "brand": "Nike",
        "lowestResellPrice.stockX": "223",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Court-Purple-Product.jpg",
        "description": "The Dunk Low SB 'Court Purple' brings subdued accents to its classic skating construction. Reminiscent of the brand's pink and silver box eras, the shoe's upper is built with a white leather base, contrasted by the black overlays that mark the forefoot, eyestay and collar. The heel instead complements the look in Court Purple, while underfoot, the sockliner incorporates Zoom Air for cushioning. A final hit of Court Purple marks the rubber outsole, which provides traction.",
        "url": "nike-sb-dunk-low-court-purple",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-court-purple",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2021-01-23"
    },
    {
        "_id": "64e81e0e37437752fdde3ee4",
        "name": "Nike SB Dunk Low Ben & Jerry's Chunky Dunky",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1194",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Ben-Jerrys-Chunky-Dunky-Product.jpg",
        "description": "The Dunk Low SB 'Chunky Dunky' released as part of a collaboration with Ben & Jerry's. Drawing from the ice cream company's Chunky Monkey flavor, the shoe emerges with a look modeled after that flavor's packaging, highlighted by blue skies and green pastures on the shoe's leather base. Pony-hair overlays appears with a cow print, while the Swoosh branding sports a melting ice cream design. A Chunky Dunky callout on the tongue tag completes the thematic look.",
        "url": "nike-sb-dunk-low-ben-jerrys-chunky-dunky",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-ben-jerrys-chunky-dunky",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2020-05-26"
    },
    {
        "_id": "64e81e0e37437752fdde3ee5",
        "name": "Nike SB Dunk Low What The Paul",
        "brand": "Nike",
        "lowestResellPrice.stockX": "382",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-What-The-P-Rod-Product.jpg",
        "description": "Paying tribute to Paul Rodriguez Jr. and his longtime partnership with Nike, the Dunk Low SB 'What The Paul' draws from various P-Rod silhouettes to achieve its discordant look. The P-Rod 1 gets the nod via the J-Rod's elephant print overlays, with the toe boxes representing the 'Mexican Blanket' and 'Stash.' The quilted inner lining draws from the P-Rod 2, while a metallic lace deubré is drawn from the 2020 Mexico-themed SB Dunk High. The mismathched tooling completes the look.",
        "url": "nike-sb-dunk-low-what-the-p-rod",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-what-the-p-rod",
        "make": "Nike SB Dunk Low",
        "retailPrice": "150",
        "releaseDate": "2021-05-24"
    },
    {
        "_id": "64e81e0e37437752fdde3ee6",
        "name": "Nike SB Dunk Low Fog",
        "brand": "Nike",
        "lowestResellPrice.stockX": "176",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-Dunk-SB-Low-Fog-Product.jpg",
        "description": "",
        "url": "nike-dunk-sb-low-fog",
        "resellLinks.stockX": "https://stockx.com/nike-dunk-sb-low-fog",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2021-11-01"
    },
    {
        "_id": "64e81e0e37437752fdde3ee7",
        "name": "Nike SB Dunk Low Pro FTC Lagoon Pulse (Regular Box)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "239",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-FTC-Lagoon-Pulse-Product.jpg",
        "description": "Releasing for the 2021 Summer Olympics in Tokyo, the FTC x Dunk Low SB 'Lagoon Pulse' dropped as part of a larger collection. Giving the nod to skateboarding's debut as an Olympic sport, the shoe was made in collaboration with skate shop FTC, appearing in a blue suede base overlaid by brick-like white leather that recalls Japanese bathhouses. The side wall adds metallic silver Swoosh branding, while the heel patch includes 'FTC' branding. An icy rubber outsole offers traction underfoot.",
        "url": "nike-sb-dunk-low-ftc-lagoon-pulse",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-ftc-lagoon-pulse",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "110",
        "releaseDate": "2021-07-21"
    },
    {
        "_id": "64e81e0e37437752fdde3ee8",
        "name": "Nike SB Dunk Low Night of Mischief Halloween",
        "brand": "Nike",
        "lowestResellPrice.stockX": "325",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Night-of-Mischief-Halloween-Product.jpg",
        "description": "The Dunk Low SB 'Night of Mischief' launched in October 2019 just in time for Halloween. The low-top features an upper built with a combination of black suede and orange tumbled leather, with special holiday-themed details including purple spiderweb detailing on the quarter panel, a perforated jack-o’-lantern on the toe box, and ‘Trick’ and ‘Treat’ embroidered on the heel tabs of the left and right shoe.",
        "url": "nike-sb-dunk-low-night-of-mischief-halloween",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-night-of-mischief-halloween",
        "make": "Nike SB Dunk Low",
        "retailPrice": "90",
        "releaseDate": "2019-10-31"
    },
    {
        "_id": "64e81e0e37437752fdde3ee9",
        "name": "Nike SB Dunk Low Pro Be True Xavier Schipani",
        "brand": "Nike",
        "lowestResellPrice.stockX": "114",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-Be-True-Xavier-Schipani-Product.jpg",
        "description": "The Nike Dunk Low SB ‘Be True’ honors a classic with a tribute to tolerance. Xavier Schipani, an Austin-based artist identifying as a trans man, created custom graphics to adorn this low-top that celebrates the LGBTQIA+ community. A white mesh base on the upper with leather overlays in vibrant yellow on the forefoot and gradient lilac-to-pink on the heel combine with asymmetrical Swooshes on each side panel in blue and pink. Branding for Nike SB and Be True alternates on the woven tongue tags. The insole salutes the strength and bond of trans communities around the world with a symbolic chain link graphic.",
        "url": "nike-sb-dunk-low-pro-be-true-xavier-schipani",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-be-true-xavier-schipani",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "115",
        "releaseDate": "2022-11-18"
    },
    {
        "_id": "64e81e0e37437752fdde3eea",
        "name": "Nike SB Dunk Low Pro Parra Abstract Art (2021)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "233",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Parra-2021-Product.jpg",
        "description": "Giving the nod to the 2021 Tokyo Games, where skateboarding debuted as an Olympic sport, the Parra x Dunk Low SB released as part of a larger collection. Designed with the help of Dutch artist Piet Parra, the shoe's upper is built with an off-white leather base, overlaid by abstract designs in a vibrant mix of hues matched by Nike SB's Olympic Federation kits. Black leather marks the shortened Swoosh branding on the quarter panel, while underfoot, a gum rubber outsole is included for traction.",
        "url": "nike-sb-dunk-low-parra-2021",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-parra-2021",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "110",
        "releaseDate": "2021-07-31"
    },
    {
        "_id": "64e81e0e37437752fdde3eeb",
        "name": "Nike SB Dunk Low Pink Pig",
        "brand": "Nike",
        "lowestResellPrice.stockX": "220",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pink-Pig-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-pink-pig",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pink-pig",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2021-02-13"
    },
    {
        "_id": "64e81e0e37437752fdde3eec",
        "name": "Nike SB Dunk Low Crushed D.C.",
        "brand": "Nike",
        "lowestResellPrice.stockX": "152",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Crushed-DC-Product.jpg",
        "description": "The Nike Dunk Low SB 'Golden Hour' is a collaboration between Crushed D.C. skate shop and Nike. The shoe features a low-cut profile and an upper in light grey tumbled leather, with brown suede forefoot and heel overlays. The signature Nike Swoosh sweeps across the side panel with a unique marbled orange and grey finish. Dual-branded tags appear on the stuffed tongues, while the green mesh lining on the interior side displays custom Crushed Skateshop tags. Nike Grind material is incorporated in the speckled orange rubber outsole.",
        "url": "nike-sb-dunk-low-crushed-dc",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-crushed-dc",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2022-10-07"
    },
    {
        "_id": "64e81e0e37437752fdde3eed",
        "name": "Nike SB Dunk Low Pro St. Patrick's Day (2022)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "156",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-St-Patricks-Day-2022-Product.jpg",
        "description": "Celebrating the luck of the Irish is the Nike Dunk Low SB ‘St. Patrick’s Day.’ The upper in soft kelly green suede is intersected by a gold Swoosh in metallic patent leather. The lateral heel reveals a stitched four-leaf clover standing out in white while Nike branding on the tongue tag and suede heel tab is delivered in shiny gold. Underfoot, an outsole in yellow rubber pops beneath the rubber cupsole and its white sidewalls.",
        "url": "nike-sb-dunk-low-pro-st-patricks-day-2022",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-st-patricks-day-2022",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "110",
        "releaseDate": "2022-03-05"
    },
    {
        "_id": "64e81e0e37437752fdde3eee",
        "name": "Nike SB Dunk Low Blue Raspberry",
        "brand": "Nike",
        "lowestResellPrice.stockX": "201",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Blue-Raspberry-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-blue-raspberry",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-blue-raspberry",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2022-06-01"
    },
    {
        "_id": "64e81e0e37437752fdde3eef",
        "name": "Nike SB Dunk Low Concepts Orange Lobster (Special Box)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "497",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Concepts-Orange-Lobster-Special-Box-Product.png",
        "description": "The Concepts x Nike Dunk Low SB ‘Orange Lobster’ updates this low-top classic as part of a longstanding collaboration with Harvard Square's oldest sneaker storefront. With lobsters as its inspiration, the sneaker is built on a nubuck upper in orange; the overlays have speckle patterning reminiscent of a lobster shell. The white tongue in breathable mesh and white-outlined orange Swoosh pair with the interior lining patterning resembling a lobster shack's requisite bib. Black sidewalls and rubber banding atop the toe box are nods to lobster claw bands. Traction is delivered via a rubber outsole in orange.",
        "url": "nike-sb-dunk-low-concepts-orange-lobster-special-box",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-concepts-orange-lobster-special-box",
        "make": "Nike SB Dunk Low",
        "retailPrice": "350",
        "releaseDate": "2022-12-02"
    },
    {
        "_id": "64e81e0e37437752fdde3ef0",
        "name": "Nike SB Dunk Low Club 58 Gulf",
        "brand": "Nike",
        "lowestResellPrice.stockX": "218",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Club-58-Gulf-Product.jpg",
        "description": "Releasing as a follow-up to the Blazer Mid 'Club 58' from 2018, the Dunk Low Pro SB 'Gulf' was made in collaboration with four prominent Western European skate shops. The shoe's upper is built with suede, finsihed in Blue Chill and contrasted by the Swoosh branding and '58' graphic. A stuffed mesh tongue supports the fit, while underfoot, Zoom Air provides cushioning. A Safety Orange finish on the rubber outsole completes the look.",
        "url": "nike-sb-dunk-low-club-58-gulf",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-club-58-gulf",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2021-03-01"
    },
    {
        "_id": "64e81e0e37437752fdde3ef1",
        "name": "Nike SB Dunk Low StrangeLove Skateboards (Regular Box)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "862",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-StrangeLove-Skateboards-Product.jpg",
        "description": "The StrangeLove x Dunk Low SB QS 'Valentine's Day' released as part of a collaboration with Sean Cliver's skate brand. Dropping in February 2020, the upper is built with white crushed velvet, overlaid by pink suede and complemented by a red velvet Swoosh. The lateral heel sports Cliver's Heart Skull graphic, while underfoot, a series of red and blue hearts are visible through the translucent rubber outsole.",
        "url": "nike-sb-dunk-low-strangelove-skateboards",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-strangelove-skateboards",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2020-02-08"
    },
    // {
    //     "_id": "64e81e0e37437752fdde3ef2",
    //     "name": "Nike SB Dunk Low Travis Scott (Special Box)",
    //     "brand": "Nike",
    //     "lowestResellPrice.stockX": "1259",
    //     "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Travis-Scott-Product.jpg",
    //     "description": "Travis Scott teamed up with Nike to create the Travis Scott x SB Dunk Low PRM QS 'Cactus Jack.' Featuring a patchwork design, the shoe's upper emerges with a tan suede base accented by plaid on the quarter panel and paisley on the overlays. The overlays themselves are designed to wear away and reveal an elephant print, while the lateral side Swoosh sports a pink finish. Cactus Jack branding emerges on the tongue tag, while a rubber outsole is included for traction.",
    //     "url": "nike-sb-dunk-low-travis-scott-special-box",
    //     "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-travis-scott-special-box",
    //     "make": "Nike SB Dunk Low",
    //     "retailPrice": "150",
    //     "releaseDate": "2020-02-22"
    // },
    {
        "_id": "64e81e0e37437752fdde3ef3",
        "name": "Nike SB Dunk Low Ben & Jerry's Chunky Dunky (F&F Packaging)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "2100",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Ben-Jerrys-Chunky-Dunky-FF-Packaging.jpg",
        "description": "The Dunk Low SB 'Chunky Dunky' released as part of a collaboration with Ben & Jerry's. Drawing from the ice cream company's Chunky Monkey flavor, the shoe emerges with a look modeled after that flavor's packaging, highlighted by blue skies and green pastures on the shoe's leather base. Pony-hair overlays appears with a cow print, while the Swoosh branding sports a melting ice cream design. A Chunky Dunky callout on the tongue tag completes the thematic look.",
        "url": "nike-sb-dunk-low-ben-jerrys-chunky-dunky-ff-packaging",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-ben-jerrys-chunky-dunky-ff-packaging",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2020-05-23"
    },
    {
        "_id": "64e81e0e37437752fdde3ef4",
        "name": "Nike SB Dunk Low HUF New York City",
        "brand": "Nike",
        "lowestResellPrice.stockX": "139",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-HUF-New-York-City-Product.jpg",
        "description": "HUF branding and a glittering Swoosh on the toe box dominate in the HUF x Nike Dunk Low SB ‘New York.’ The late professional skateboarder Keith Hufnagel, his streetwear brand and the city of New York are honored with 'Keith Forever' on the heels hovering over etched visuals of the NYC skyline. The leather upper in tumbled leather combines navy with white overlays and a light cream Swoosh. Woven tags on the slimmed-down tongue feature Nike SB and New York City branding. Nike SB and HUF logos adorn the sockliners, the latter in the designer's trademark lime green. Beneath the navy quarter panels hides a tie-dye pattern that salutes the SB Dunk High collaboration from 2004.",
        "url": "nike-sb-dunk-low-huf-new-york-city",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-huf-new-york-city",
        "make": "Nike SB Dunk Low",
        "retailPrice": "130",
        "releaseDate": "2022-11-16"
    },
    {
        "_id": "64e81e0e37437752fdde3ef5",
        "name": "Nike SB Dunk Low Pro Be True",
        "brand": "Nike",
        "lowestResellPrice.stockX": "125",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-Be-True-Product-1.jpg",
        "description": "Celebrating Pride Month and the LGBTQIA+ community’s spirit of self-expression is the Nike Dunk Low SB ‘Be True.’ Panels in leather are layered with wear-away white that will fade to reveal a colorful palette underneath. The heel tabs deliver branding in alternating purple and aqua while the lateral heel is adorned with ‘Be True’ stitching which also appears on the sockliner. A Zoom Air unit embedded in the heel provides cushioned support.",
        "url": "nike-sb-dunk-low-pro-be-true",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-be-true",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "115",
        "releaseDate": "2022-06-22"
    },
    {
        "_id": "64e81e0e37437752fdde3ef6",
        "name": "Nike SB Dunk Low atmos Elephant",
        "brand": "Nike",
        "lowestResellPrice.stockX": "214",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-atmos-Elephant-Product.jpg",
        "description": "Drawing from a 2006 (and, later, 2017) Air Max 1 collaboration with atmos, the Dunk Low Pro SB 'Atmos Elephant' emerges with unique detailing throughout its construction. The shoe's upper is built with a mix of leather and suede, overlaid by a safari print on the forefoot and heel. Clear Jade branding accents the look, while Zoom Air in the sockliner provides cushioning.",
        "url": "nike-sb-dunk-low-atmos-elephant",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-atmos-elephant",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2020-11-11"
    },
    {
        "_id": "64e81e0e37437752fdde3ef7",
        "name": "Nike SB Dunk Low Sean Cliver",
        "brand": "Nike",
        "lowestResellPrice.stockX": "475",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Sean-Cliver-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-sean-cliver",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-sean-cliver",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2020-12-19"
    },
    {
        "_id": "64e81e0e37437752fdde3ef8",
        "name": "Nike SB Dunk Low J-Pack Chicago",
        "brand": "Nike",
        "lowestResellPrice.stockX": "333",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-J-Pack-Chicago.png",
        "description": "",
        "url": "nike-sb-dunk-low-j-pack-chicago",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-j-pack-chicago",
        "make": "Nike SB Dunk Low",
        "retailPrice": "95",
        "releaseDate": "2020-09-01"
    },
    {
        "_id": "64e81e0e37437752fdde3ef9",
        "name": "Nike SB Dunk Low Classic Green",
        "brand": "Nike",
        "lowestResellPrice.stockX": "240",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Classic-Green-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-classic-green",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-classic-green",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2021-06-05"
    },
    {
        "_id": "64e81e0e37437752fdde3efa",
        "name": "Nike SB Dunk Low Pro Dark Russet",
        "brand": "Nike",
        "lowestResellPrice.stockX": "141",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-Dark-Russet-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-pro-dark-russet",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-dark-russet",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "100",
        "releaseDate": "2022-04-07"
    },
    {
        "_id": "64e81e0e37437752fdde3efb",
        "name": "Nike SB Dunk Low Stingwater Magic Mushroom",
        "brand": "Nike",
        "lowestResellPrice.stockX": "174",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-Dunk-SB-Low-Stingwater-Magic-Mushroom-Product.jpg",
        "description": "The Stingwater x Dunk Low SB 'Magic Mushroom' is the result of a collaboration with Daniel Kim's skate brand. The shoe's upper is built with leather, with the University Red base highlighted by a safari print on the overlays, creating a design not unlike a mushroom cap. The lateral quarter panel includes a jewel Swoosh and scrambled Stingwater branding, while the heel patch includes reverse Nike branding. A zippered stash pocket on the tongue is joined by an interior woven tag that reads 'Free Your Mind,' while underfoot, the translucent rubber outsole reveals 'Plant Emoji' and 'With Eyes' across both shoes.",
        "url": "nike-dunk-sb-low-stingwater-magic-mushroom",
        "resellLinks.stockX": "https://stockx.com/nike-dunk-sb-low-stingwater-magic-mushroom",
        "make": "Nike SB Dunk Low",
        "retailPrice": "125",
        "releaseDate": "2021-05-10"
    },
    {
        "_id": "64e81e0e37437752fdde3efc",
        "name": "Nike SB Dunk Low Orange Label White Navy",
        "brand": "Nike",
        "lowestResellPrice.stockX": "235",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Orange-Label-White-Navy-Product.jpg",
        "description": "The Dunk Low Pro ISO SB 'Orange Label - White Navy' released in select skate shops as part of the Orange Label series. Featuring a simple look, the shoe's upper is built with a white leather base, with navy on the Swoosh and heel branding. Safety Orange marks the woven Nike SB tongue tag to add further color to the design, while the stuffed tongue itself supports the fit. Underfoot, the concentric gum rubber outsole offers traction and an elevated finish.",
        "url": "nike-sb-dunk-low-orange-label-white-navy",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-orange-label-white-navy",
        "make": "Nike SB Dunk Low",
        "retailPrice": "90",
        "releaseDate": "2021-05-01"
    },
    {
        "_id": "64e81e0e37437752fdde3efd",
        "name": "Nike SB Dunk Low Pro Blue Fury",
        "brand": "Nike",
        "lowestResellPrice.stockX": "225",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-Blue-Fury_Product.jpg",
        "description": "The Dunk Low SB 'Blue Fury' emerges with a vibrant look on its elevated construction. The shoe's upper is built with nubuck, overlaid by suede and finished primarily in Blue Fury. A Deep Royal leather Swoosh complements the design, while metallic silver accents the heel patch. A padded mesh tongue is included for comfort, while underfoot, Zoom Air in the sockliner provides cushioning. A translucent rubber outsole is included for traction.",
        "url": "nike-sb-dunk-low-pro-blue-fury",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-blue-fury",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "100",
        "releaseDate": "2020-04-01"
    },
    {
        "_id": "64e81e0e37437752fdde3efe",
        "name": "Nike SB Dunk Low Frame Skate Habibi",
        "brand": "Nike",
        "lowestResellPrice.stockX": "695",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Frame-Skate-Habibi-Product.jpg",
        "description": "Nike teamed up with the Dubai retailer to create the Frame Skate x Dunk Low SB 'Habibi' in December 2020. The shoe's upper is built with a mix of leather and textile, featuring a white base highlighted by Chile Red overlays, with black and Lucky Green on the stacked Swoosh branding to complete the colors of the UAE flag. The stacked tongues include an oyster tag and 'Habibi' on the inside tongue, with the removable external tongue sporting a tonal falcon graphic on the tag.",
        "url": "nike-sb-dunk-low-frame-skate-habibi",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-frame-skate-habibi",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2020-12-05"
    },
    {
        "_id": "64e81e0e37437752fdde3eff",
        "name": "Nike SB Dunk Low Supreme Rammellzee",
        "brand": "Nike",
        "lowestResellPrice.stockX": "990",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Supreme-Rammellzee-Product.jpg",
        "description": "The Supreme x Nike Dunk Low SB 'Rammellzee' brings together the late artist, who was known for his multimedia sculptures and graffiti with the renowned NYC skate brand. The Dunk Low silhouette is highlighted and adorned with Rammellzee's original designs on a canvas upper. The eyestay, Swoosh, and forefoot overlay are constructed from durable black suede that is repeated on the textile collar lining and the padded mesh tongue. The shoe is accented with metallic gold 'Supreme' lace dubrae, while a durable cupsole with black sidewalls and a gum rubber outsole supplies optimal support and grip underfoot.",
        "url": "nike-sb-dunk-low-supreme-rammellzee",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-supreme-rammellzee",
        "make": "Nike SB Dunk Low",
        "retailPrice": "130",
        "releaseDate": ""
    },
    {
        "_id": "64e81e0e37437752fdde3f00",
        "name": "Nike SB Dunk Low Green Apple",
        "brand": "Nike",
        "lowestResellPrice.stockX": "270",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Green-Apple-Product.jpg",
        "description": "The Nike Dunk Low Pro SB ‘Green Apple’ is one pair in the ‘Fruity Pack,’ rendered in granny-apple green. With Coconut Milk leather as the backdrop, Atomic Green overlays in suede are complemented by a signature Swoosh in a darker green hue. The low-tops foam sockliner benefits from a responsive Zoom Air unit in the heel. The ‘Nike SB’ tongue tag reveals a green apple image on the interior side.",
        "url": "nike-sb-dunk-low-green-apple",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-green-apple",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2022-07-09"
    },
    {
        "_id": "64e81e0e37437752fdde3f01",
        "name": "Nike SB Dunk Low Chlorophyll",
        "brand": "Nike",
        "lowestResellPrice.stockX": "178",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Chlorophyll-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-chlorophyll",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-chlorophyll",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2022-01-01"
    },
    {
        "_id": "64e81e0e37437752fdde3f02",
        "name": "Nike SB Dunk Low Street Hawker (2021)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "309",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-CNY-Chinese-New-Year-2021-Product.jpg",
        "description": "The Jason Deng x Dunk Low Pro SB 'Street Hawker' was designed by the Guangzhou artist. Giving the nod to Chinese food culture and street food vendors, the shoe emerges with a mismatched look made up of unique materials, colors and Deng's watercolor graphics. Representing six regional dishes from six Chinese cities, the design is also highlighted by a wood-grain Swoosh to callout chopsticks, while porcelain bowls are represented by the sockliner. The copper toe box instead recalls boiling chili oil, while the Chinese character for 'food' appears on the heel.",
        "url": "nike-sb-dunk-low-street-hawker",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-street-hawker",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2021-01-22"
    },
    {
        "_id": "64e81e0e37437752fdde3f03",
        "name": "Nike SB Dunk Low Pro ACG Terra Red Plum",
        "brand": "Nike",
        "lowestResellPrice.stockX": "166",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-Dunk-SB-Low-Pro-ACG-Terra-Red-Plum-Product.jpg",
        "description": "Inspired by 90s All Conditions Gear models, the Dunk Low Pro SB 'Red Plum' emerges with a rich colorway. Built entirely with suede, the shoe's upper appears in black, overlaid by Red Plum and contrasted by a Citron Swoosh on the side wall. Underfoot, Zoom Air in the heel of the foam insole provides cushioning, giving way to a speckled rubber midsole to complete the look.",
        "url": "nike-dunk-sb-low-pro-acg-terra-red-plum",
        "resellLinks.stockX": "https://stockx.com/nike-dunk-sb-low-pro-acg-terra-red-plum",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "100",
        "releaseDate": "2021-08-01"
    },
    {
        "_id": "64e81e0e37437752fdde3f04",
        "name": "Nike SB Dunk Low Medicom Toy (2020)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "156",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Medicom-Toy-2020-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-medicom-toy-2020",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-medicom-toy-2020",
        "make": "Nike SB Dunk Low",
        "retailPrice": "125",
        "releaseDate": "2020-08-25"
    },
    {
        "_id": "64e81e0e37437752fdde3f05",
        "name": "Nike SB Dunk Low Laser Blue",
        "brand": "Nike",
        "lowestResellPrice.stockX": "128",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Laser-Blue-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-laser-blue",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-laser-blue",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2021-11-12"
    },
    {
        "_id": "64e81e0e37437752fdde3f06",
        "name": "Nike SB Dunk Low Grateful Dead Bears Opti Yellow",
        "brand": "Nike",
        "lowestResellPrice.stockX": "763",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Grateful-Dead-Bears-Yellow-Product.jpg",
        "description": "The Grateful Dead x Dunk Low SB 'Yellow Bear' is the result of a collaboration between Nike and the Grateful Dead. Inspired by the back cover of History of the Grateful Dead, Volume One (Bear's Choice), a live album originally released in 1973, the shoe emerges with a furry construction on the upper bolstered by tonal suede overlays. The jagged Swoosh and tongue complement the look in blue, with a stash pocket on the latter element. The two-tone look continues onto the tooling.",
        "url": "nike-sb-dunk-low-grateful-dead-bears-yellow",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-grateful-dead-bears-yellow",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2020-07-24"
    },
    {
        "_id": "64e81e0e37437752fdde3f07",
        "name": "Nike SB Dunk Low ACG Celadon",
        "brand": "Nike",
        "lowestResellPrice.stockX": "171",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-Dunk-Low-SB-Celadon-Product.jpg",
        "description": "Inspired by the All Conditions Gear Caldera hiking boot, the Dunk Low SB 'ACG Celadon' emerges with an elevated build. The shoe's upper is built with suede, finished in a mix of tan and blue, with a lighter blue marking the Swoosh branding. A padded mesh tongue is included for breathability, while underfoot, Zoom Air in the heel of the sockliner provides cushioning. A speckled midsole gives way to a rubber outsole for traction.",
        "url": "nike-dunk-low-sb-celadon",
        "resellLinks.stockX": "https://stockx.com/nike-dunk-low-sb-celadon",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2021-04-10"
    },
    {
        "_id": "64e81e0e37437752fdde3f08",
        "name": "Nike SB Dunk Low Grateful Dead Bears Green",
        "brand": "Nike",
        "lowestResellPrice.stockX": "889",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Grateful-Dead-Bears-Green-Product.jpg",
        "description": "Inspired by the back cover of the Grateful Dead's 1973 live album, 'History of the Grateful Dead, Vol. One (Bear's Choice),' the Grateful Dead x Dunk Low SB 'Green Bear' was made in collaboration with the iconic band. The shoe's upper features a furry Electric Green construction on its underlays, with the jagged Swoosh and branding adding Game Royal to the design. A bear graphic marks the tongue, which includes a zippered stash pocket, while both colors come together on the rubber cupsole underfoot.",
        "url": "nike-sb-dunk-low-grateful-dead-bears",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-grateful-dead-bears",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2020-07-24"
    },
    {
        "_id": "64e81e0e37437752fdde3f09",
        "name": "Nike SB Dunk Low OG QS Quartersnacks Zebra",
        "brand": "Nike",
        "lowestResellPrice.stockX": "181",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-High-Quartersnacks-Zebra-Product.jpg",
        "description": "One of several Dunk collaborations for the 2021 Tokyo Games, the Quartersnacks x Nike Dunk Low SB 'Little Debbie’s Zebra Cakes' helps celebrate skateboarding's deubt as an Olympic sport. Designed with the help of the online magazine, the shoe's construction draws from Little Debbie Zebra Cakes, sporting zebra stripes on the toe box, quarter panel and collar. The forefoot and heel are overlaid by solid black leather, adding Quartersnacks branding on the lateral side, while underfoot, a two-tone rubber cupsole anchors the design.",
        "url": "nike-sb-dunk-low-quartersnacks-zebra",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-quartersnacks-zebra",
        "make": "Nike SB Dunk Low OG QS",
        "retailPrice": "110",
        "releaseDate": "2021-09-18"
    },
    {
        "_id": "64e81e0e37437752fdde3f0a",
        "name": "Nike SB Dunk Low Civilist",
        "brand": "Nike",
        "lowestResellPrice.stockX": "430",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Civilist-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-civilist",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-civilist",
        "make": "Nike SB Dunk Low",
        "retailPrice": "125",
        "releaseDate": "2020-08-29"
    },
    {
        "_id": "64e81e0e37437752fdde3f0b",
        "name": "Nike SB Dunk Low Supreme Stars Hyper Royal (2021)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "448",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Supreme-Hyper-Royal-Product.jpg",
        "description": "Inspired by a 2003 collaboration between Nike and Supreme, the Supreme x Dunk Low OG SB QS 'Hyper Royal' dropped in March 2021. Like its high-top predecessor, the shoe's upper is built with white leather, with the Hyper Royal overlays sporting crocodile detailing. The quarter panel is highlighted by metallic gold stars, matched by the heel patch and tongue tag Nike branding and Supreme lace deubré. Underfoot, the sockliner sports a red finish and co-branding, incorporating Zoom Air for cushioning.",
        "url": "nike-sb-dunk-low-supreme-hyper-royal",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-supreme-hyper-royal",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2021-03-04"
    },
    {
        "_id": "64e81e0e37437752fdde3f0c",
        "name": "Nike SB Dunk Low Laser Orange",
        "brand": "Nike",
        "lowestResellPrice.stockX": "248",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Laser-Orange-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-laser-orange",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-laser-orange",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2020-04-10"
    },
    {
        "_id": "64e81e0e37437752fdde3f0d",
        "name": "Nike SB Dunk Low VX1000",
        "brand": "Nike",
        "lowestResellPrice.stockX": "276",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-VX1000-Product.jpg",
        "description": "Inspired by the Sony DCR VX1000 camcorder, crucial to the creation of skate videos in the 90s, the Dunk Low SB 'Camcorder' emerges with a tribute look. The shoe's nubuck upper appears in a series of white, black and grey hues, with various camcorder functions making the synthetic leather heel overlay, including 'Shutter Speed' and 'Rec Level.' Underfoot, a Zoom Air sockliner provides cushioning, with a semitranslucent grey rubber outsole sporting a concentric pattern for traction.",
        "url": "nike-sb-dunk-low-vx1000",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-vx1000",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2021-02-20"
    },
    {
        "_id": "64e81e0e37437752fdde3f0e",
        "name": "Nike SB Dunk Low St. Patrick's Day (PS) (2022)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "125",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-St-Patricks-Day-PS-Product.jpg",
        "description": "The luckiest day of the year serves as inspiration for the Nike Dunk Low SB PS ‘St. Patrick’s Day,’ a low-top made for little kids. Vivid kelly green suede infuses the upper intersected by a gilded Swoosh. Branding displays additional metallic gold details on the back tag and tongue tag, and a four-leaf clover nods to March 17 on the lateral heel. A white rubber outsole supports the foot atop a gum rubber outsole for grippy traction.",
        "url": "nike-sb-dunk-low-st-patricks-day-ps",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-st-patricks-day-ps",
        "make": "Nike SB Dunk Low",
        "retailPrice": "90",
        "releaseDate": "2022-06-07"
    },
    {
        "_id": "64e81e0e37437752fdde3f0f",
        "name": "Nike SB Dunk Low Supreme Jewel Swoosh Red",
        "brand": "Nike",
        "lowestResellPrice.stockX": "195",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Supreme-Jewel-Swoosh-Red-Product.jpg",
        "description": "Dropping as part of the New York brand’s Fall/Winter 2019 collection, the Supreme x Dunk SB Low 'Varsity Red' features a two-tone leather upper with a red jewel Swoosh on the quarter panel. A metallic Varsity Red finish is applied to the forefoot, while the rest of the upper is dressed in white leather. A Supreme logo hit adorns the lateral heel.",
        "url": "nike-sb-dunk-low-supreme-jewel-swoosh-red",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-supreme-jewel-swoosh-red",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2019-09-14"
    },
    {
        "_id": "64e81e0e37437752fdde3f10",
        "name": "Nike SB Dunk Low J-Pack Shadow",
        "brand": "Nike",
        "lowestResellPrice.stockX": "428",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-J-Pack-Shadow-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-j-pack-shadow",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-j-pack-shadow",
        "make": "Nike SB Dunk Low",
        "retailPrice": "90",
        "releaseDate": "2020-02-04"
    },
    {
        "_id": "64e81e0e37437752fdde3f11",
        "name": "Nike SB Dunk Low Staple Panda Pigeon",
        "brand": "Nike",
        "lowestResellPrice.stockX": "795",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Panda-Pigeon-Product.jpg",
        "description": "The Jeff Staple x Dunk Low Pro SB ‘Panda Pigeon’ extends Staple’s enduring collaboration with Nike SB. The moniker lives up to its name with a black and white pattern on the leather and suede upper, finished with the integral pigeon on the lateral heel. A translucent outsole displays a collage of newspaper headlines referring to the legendary Pigeon Dunk launch from 2005.",
        "url": "nike-sb-dunk-low-panda-pigeon",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-panda-pigeon",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2019-01-15"
    },
    {
        "_id": "64e81e0e37437752fdde3f12",
        "name": "Nike SB Dunk Low Medicom Toy (2020) (PS)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "88",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Medicom-Toy-2020-PS-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-medicom-toy-2020-ps",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-medicom-toy-2020-ps",
        "make": "Nike SB Dunk Low",
        "retailPrice": "75",
        "releaseDate": "2020-08-25"
    },
    {
        "_id": "64e81e0e37437752fdde3f13",
        "name": "Nike SB Dunk Low 7-Eleven",
        "brand": "Nike",
        "lowestResellPrice.stockX": "2000",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-7-Eleven-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-7-eleven",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-7-eleven",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2020-04-19"
    },
    {
        "_id": "64e81e0e37437752fdde3f14",
        "name": "Nike SB Dunk Low Gnarhunters",
        "brand": "Nike",
        "lowestResellPrice.stockX": "194",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Gnarhunters-Product.jpg",
        "description": "Bringing a skate-meets-surf vibe to a heritage low-top is the Gnarhunters x Nike Dunk Low SB ‘Black.’ Following up on the brand’s 2019 Blazer SB collab, the upper in a beachy terry cloth features overlays in twill with a removeable Swoosh on the side panel, secured with Velcro. Bungie-cord laces are outfitted with a toggle. The heel tab and tongue deliver Gnarhunters branding. The rubber outsole in solid white offers grip underfoot.",
        "url": "nike-sb-dunk-low-gnarhunters",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-gnarhunters",
        "make": "Nike SB Dunk Low",
        "retailPrice": "120",
        "releaseDate": "2022-03-01"
    },
    {
        "_id": "64e81e0e37437752fdde3f15",
        "name": "Nike SB Dunk Low Los Angeles Dodgers (PS)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "120",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Los-Angeles-Dodgers-PS-Product.jpg",
        "description": "The Nike Dunk Low SB PS 'Los Angeles Dodgers' is a part of a shoe series that drew inspiration from distinguished MLB teams. These shoes are designed for little kids and are dedicated to the Boys in Blue. They feature an upper in white leather with a textile Swoosh in a deep royal color and overlays made of suede. The interior tongue features alternating tags showcasing a palm tree graphic and the legendary Dodger Stadium marquee. The gum rubber outsole of the right shoe sports a pinkish tint.",
        "url": "nike-sb-dunk-low-los-angeles-dodgers-ps",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-los-angeles-dodgers-ps",
        "make": "Nike SB Dunk Low",
        "retailPrice": "90",
        "releaseDate": "2022-10-01"
    },
    {
        "_id": "64e81e0e37437752fdde3f16",
        "name": "Nike SB Dunk Low Los Angeles Dodgers (TD)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "111",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Los-Angeles-Dodgers-TD.jpg",
        "description": "The Nike Dunk Low SB TD pays tribute to the Los Angeles Dodgers as part of a collection that honors some of MLB's most legendary franchises. This sneaker showcases a two-tone colorway that's perfect for younger baseball fans. The upper arrives in white leather with Deep Royal Blue suede overlays and a matching textile Swoosh. The interior tongue tags alternate and represent the Dodgers' home turf, featuring a palm tree graphic on one and the familiar welcome sign of Dodger Stadium on the other. The right shoe is designed with a pink-colored gum rubber outsole heel, a nod to discarded bubblegum on the field.",
        "url": "nike-sb-dunk-low-los-angeles-dodgers-td",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-los-angeles-dodgers-td",
        "make": "Nike SB Dunk Low",
        "retailPrice": "75",
        "releaseDate": "2022-10-01"
    },
    {
        "_id": "64e81e0e37437752fdde3f17",
        "name": "Nike SB Dunk Low Supreme Stars Black (2021)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "494",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Supreme-Black-Product.jpg",
        "description": "A spiritual follow-up to a 2003 Dunk High collaboration, the Supreme x Dunk Low OG SB QS 'Black' released in March 2021. Emerging with a look similar to its predecessor, the shoe's white leather upper is highlighted by metallic gold stars on the side wall. The black leather overlays sport crocodile detailing, while more metallic gold marks the tongue tag, heel patch and Supreme-branded lace deubré. Underfoot, a red custom sockliner sports co-branding, with Zoom Air providing cushioning.",
        "url": "nike-sb-dunk-low-supreme-black",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-supreme-black",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2021-03-04"
    },
    {
        "_id": "64e81e0e37437752fdde3f18",
        "name": "Nike SB Dunk Low Wasted Youth",
        "brand": "Nike",
        "lowestResellPrice.stockX": "140",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Wasted-Youth-Product.jpg",
        "description": "The Wasted Youth x Nike Dunk Low SB 'Black Denim' is a collaboration between Nike and the Japanese streetwear brand founded by the graphic designer Verdy, and provides a fresh take on the classic Dunk silhouette. The retro low-top is updated with a punk-rock vibe, featuring exposed stitching and a patchwork-like design on the black denim upper. A tonal leather overlay is added to the forefoot for texture. On the medial side, an embroidered red rose graphic is integrated into the Swoosh. The heel tab is adorned with metal hardware and both shoes are labeled with 'Wasted Youth.’ 'No Thank You I Don’t Need Your Support' and 'Don’t Bother Me Anymore' are declared on the custom sockliners.",
        "url": "nike-sb-dunk-low-wasted-youth",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-wasted-youth",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2021-04-06"
    },
    {
        "_id": "64e81e0e37437752fdde3f19",
        "name": "Nike SB Dunk Low Pro Hennessy",
        "brand": "Nike",
        "lowestResellPrice.stockX": "291",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Pro-Hennessy-Product.jpg",
        "description": "The Dunk Low SB 'Muslin' features a neutral look. The shoe's upper is built with a mix of leather and suede, finished in Muslin and contrasted by the Swoosh and laces. The inner lining adds further contrast, with the same hue on the midsole and rubber outsole. A metallic gold heel patch accents the design, while Zoom Air in the sockliner provides cushioning.",
        "url": "nike-sb-dunk-low-pro-hennessy",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-pro-hennessy",
        "make": "Nike SB Dunk Low Pro",
        "retailPrice": "100",
        "releaseDate": "2020-04-01"
    },
    {
        "_id": "64e81e0e37437752fdde3f1a",
        "name": "Nike SB Dunk Low Safari",
        "brand": "Nike",
        "lowestResellPrice.stockX": "221",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Safari-Product.jpg",
        "description": "Inspired by atmos' Air Max 1 collaboration from 2003, the Dunk Low Pro SB 'Safari' emerges with a safari print throughout its construction. Built with a mix of canvas and suede, the upper's orange base is complemented by mismatched Swoosh branding. Underfoot, a gum rubber outsole is included for traction.",
        "url": "nike-sb-dunk-low-atmos-safari",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-atmos-safari",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2020-03-14"
    },
    {
        "_id": "64e81e0e37437752fdde3f1b",
        "name": "Nike SB Dunk Low Denim Sashiko",
        "brand": "Nike",
        "lowestResellPrice.stockX": "227",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Sashiko-Product.jpg",
        "description": "Inspired by traditional Japanese needlework embroidery, the Dunk Low Pro PRM SB 'Sashiko Pack' emerges with decorative stitching throughout its construction. The upper itself is built with suede and denim, finished in different shades of blue. A stuffed tongue is included for comfort, while Zoom Air in the heel of the sockliner provides cushioning. A gum rubber outsole is included for traction.",
        "url": "nike-sb-dunk-low-sashiko",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-sashiko",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2020-08-01"
    },
    {
        "_id": "64e81e0e37437752fdde3f1c",
        "name": "Nike SB Dunk Low Instant Skateboards",
        "brand": "Nike",
        "lowestResellPrice.stockX": "249",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Instant-Skateboards-Product.jpg",
        "description": "",
        "url": "nike-sb-dunk-low-instant-skateboards",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-instant-skateboards",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2020-09-19"
    },
    {
        "_id": "64e81e0e37437752fdde3f1d",
        "name": "Nike SB Dunk Low Concepts Purple Lobster",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1012",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Concepts-Purple-Lobster-Product.jpg",
        "description": "Concepts and Nike SB are back with a new iteration inspired by the 'Lobster.' Similar to the three past executions, the Dunk Low Premium SB 'Purple Lobster' is influenced by strange color specimens discovered in nature due in part to genetic abnormalities that make their exoskeleton appear in distinct colors, such as yellow, blue and purple. Special details include a plaid pattern on the lining, red and white, and an elastic band wrapped around the forefoot comparable to how lobster claws are secured.",
        "url": "nike-sb-dunk-low-concepts-purple-lobster",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-concepts-purple-lobster",
        "make": "Nike SB Dunk Low",
        "retailPrice": "130",
        "releaseDate": "2018-12-14"
    },
    {
        "_id": "64e81e0e37437752fdde3f1e",
        "name": "Nike SB Dunk Low Supreme Stars Barkroot Brown (2021)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "435",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Supreme-Barkroot-Brown-Product.jpg",
        "description": "Releasing in March 2021, the Supreme x Dunk Low OG SB QS 'Barkroot Brown' is a follow-up to a 2003 Dunk High collaboration with Supreme. The shoe's upper features a white leather base, overlaid by crocodile detailing in Barkroot Brown. The quarter panel is highlighted by metallic gold stars, matched by the lace deubré, tongue tag and heel patch. A stuffed textile tongue supports the fit, while underfoot, the co-branded sockliner includes Zoom Air for cushioning.",
        "url": "nike-sb-dunk-low-supreme-barkroot-brown",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-supreme-barkroot-brown",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2021-03-04"
    },
    {
        "_id": "64e81e0e37437752fdde3f1f",
        "name": "Nike SB Dunk Low Supreme Jewel Swoosh Gold",
        "brand": "Nike",
        "lowestResellPrice.stockX": "179",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Supreme-Jewel-Swoosh-Gold-Product.jpg",
        "description": "The Supreme x Nike Dunk SB Low 'Metallic Gold' dropped in September 2019 as part of a three-piece pack, each featuring a simple two-tone design with a jewel Swoosh and Supreme embroidered branding on the lateral heel. Details include a navy leather upper with a contrasting metallic gold finish on the forefoot and rubber outsole. A padded mesh tongue completes the classic Nike SB aesthetic.",
        "url": "nike-sb-dunk-low-supreme-jewel-swoosh-gold",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-supreme-jewel-swoosh-gold",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2019-09-14"
    },
    {
        "_id": "64e81e0e37437752fdde3f20",
        "name": "Nike SB Dunk Low Familia First Avenue",
        "brand": "Nike",
        "lowestResellPrice.stockX": "391",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Familia-First-Avenue-Product.jpg",
        "description": "The Familia x Nike Dunk Low Pro QS SB 'First Avenue' is an updated shoe created in collaboration with a skate shop from Minneapolis and dedicated to a famous music venue. The upper is secured with purple laces and is constructed from black suede with tonal leather on the eyestay and forefoot that has a wear-away top layer. The heel overlay has an embossed brick pattern, while the design on the toe box is inspired by the distinctive façade of the First Avenue, with star-shaped perforations. Additionally, there is a star graphic stitched on the lateral heel. The interior is lined with plush velvet for comfort and a clear rubber outsole with a starry graphic print underneath provides support underfoot.",
        "url": "nike-sb-dunk-low-familia-first-avenue",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-familia-first-avenue",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2021-12-11"
    },
    {
        "_id": "64e81e0e37437752fdde3f21",
        "name": "Nike SB Dunk Low De La Soul (2015)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "593",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-Dunk-SB-Low-De-La-Soul-2015-Product.jpg",
        "description": "A low-top redesign of a 2005 high-top colorway made in collaboration with De La Soul, the SB Dunk Low 'De La Soul' features a vibrant look inspired by the cover of the album 3 Feet High and Rising. Sporting a Baroque Brown suede upper with an Altitude Green elephant print on the toe and eyestay, the heel sports a vinyl graphic design. An Altitude Green midsole and Baroque Brown outsole complete the look.",
        "url": "nike-dunk-sb-low-de-la-soul-low",
        "resellLinks.stockX": "https://stockx.com/nike-dunk-sb-low-de-la-soul-low",
        "make": "Nike SB Dunk Low",
        "retailPrice": "135",
        "releaseDate": "2015-05-16"
    },
    {
        "_id": "64e81e0e37437752fdde3f22",
        "name": "Nike SB Dunk Low Supreme Stars Mean Green (2021)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "688",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Supreme-Mean-Grean-Product.jpg",
        "description": "One of four colorways released as part of a spiritual sequel to a 2003 Dunk High collaboration, the Supreme x Dunk Low OG SB QS 'Mean Green' released in March 2021. Featuring a look that draws from the OG design, the shoe's upper is built with white leather, overlaid by Mean Green crocodile-embossed leather and highlighted by printed gold stars. More gold marks the Supreme lace deubré as well as the Nike branding, while underfoot, Zoom Air in the sockliner provides cushioning. The sockliner itself includes co-branding to complete the look.",
        "url": "nike-sb-dunk-low-supreme-mean-green",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-supreme-mean-green",
        "make": "Nike SB Dunk Low",
        "retailPrice": "110",
        "releaseDate": "2021-03-04"
    },
    {
        "_id": "64e81e0e37437752fdde3f23",
        "name": "Nike SB Dunk Low Concepts Green Lobster (Special Box)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1197",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Concepts-Green-Lobster-1-1.jpg",
        "description": "Nike collaborated with Boston-based brand Concepts to drop a limited edition colorway that is influenced by the brand’s crustacean motifs. The Concepts x Dunk Low SB 'Green Lobster' features a green colorway with a durabuck and suede upper in Green Stone, with an understated speckle graphic. The low top also flaunts a white padded tongue for comfort, patterns on the inner lining, and a Zoom Air insert in the sockliner for soft support.",
        "url": "nike-sb-dunk-low-concepts-green-lobster",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-concepts-green-lobster",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2018-12-14"
    },
    {
        "_id": "64e81e0e37437752fdde3f24",
        "name": "Nike SB Dunk Low Concepts Purple Lobster (Special Box)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1221",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Concepts-Purple-Lobster-Special-Packaging-1.jpg",
        "description": "Concepts and Nike SB are back with a new iteration inspired by the 'Lobster.' Similar to the three past executions, the Dunk Low Premium SB 'Purple Lobster' is influenced by strange color specimens discovered in nature due in part to genetic abnormalities that make their exoskeleton appear in distinct colors, such as yellow, blue and purple. Special details include a plaid pattern on the lining, red and white, and an elastic band wrapped around the forefoot comparable to how lobster claws are secured.",
        "url": "nike-sb-dunk-low-concepts-purple-lobster-special-packaging",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-concepts-purple-lobster-special-packaging",
        "make": "Nike SB Dunk Low",
        "retailPrice": "130",
        "releaseDate": "2018-12-14"
    },
    {
        "_id": "64e81e0e37437752fdde3f25",
        "name": "Nike SB Dunk Low Concepts Green Lobster (Regular Box)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1305",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Concepts-Green-Lobster-1-1.jpg",
        "description": "Nike collaborated with Boston-based brand Concepts to drop a limited edition colorway that is influenced by the brand’s crustacean motifs. The Concepts x Dunk Low SB 'Green Lobster' features a green colorway with a durabuck and suede upper in Green Stone, with an understated speckle graphic. The low top also flaunts a white padded tongue for comfort, patterns on the inner lining, and a Zoom Air insert in the sockliner for soft support.",
        "url": "nike-sb-dunk-low-concepts-green-lobster-regular-box",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-concepts-green-lobster-regular-box",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2018-12-14"
    },
    {
        "_id": "64e81e0e37437752fdde3f26",
        "name": "Nike SB Dunk Low Crenshaw Skate Club (TD)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "130",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-Crenshaw-Skate-Club-TD.jpg",
        "description": "Tailored for young ones, the Crenshaw Skate Club x Nike Dunk Low SB TD honors CSC founder Tobias McIntosh's LA neighborhood. The tan suede upper is accentuated by a pale blue leather Swoosh and cracked leather overlays inspired by the renowned Crenshaw Square sign. Atop a clear rubber outsole, the sneaker rests on a robust rubber cupsole with stitched sidewalls. The tongue tag, insole, and heel tab are embellished with both Nike and CSC branding.",
        "url": "nike-sb-dunk-low-crenshaw-skate-club-td",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-crenshaw-skate-club-td",
        "make": "Nike SB Dunk Low",
        "retailPrice": "75",
        "releaseDate": "2023-08-05"
    },
    {
        "_id": "64e81e0e37437752fdde3f27",
        "name": "Nike SB Dunk Low Disposable",
        "brand": "Nike",
        "lowestResellPrice.stockX": "625",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-Dunk-SB-Low-Disposable-Product.jpg",
        "description": "The Dunk Low Premium SB QS ‘Disposable’ celebrates the 10th anniversary of Sean Cliver’s book, ‘Disposable: A History of Skateboard Art.’ The low-top features a black suede upper, contrasted by a light grey suede toe box and white leather collar. Vibrant pops of fuchsia appear on the Swoosh, laces, collar lining and ‘Disposable’ embroidery on the lateral heel.",
        "url": "nike-dunk-sb-low-disposable",
        "resellLinks.stockX": "https://stockx.com/nike-dunk-sb-low-disposable",
        "make": "Nike SB Dunk Low",
        "retailPrice": "105",
        "releaseDate": "2014-11-19"
    },
    {
        "_id": "64e81e0e37437752fdde3f28",
        "name": "Nike SB Dunk Low StrangeLove Skateboards (Special Box)",
        "brand": "Nike",
        "lowestResellPrice.stockX": "1455",
        "image": "https://prime-orca.s3.us-east-2.amazonaws.com/nike-dunks/Nike-SB-Dunk-Low-StrangeLove-Skateboards-Special-Box-Product.png",
        "description": "The StrangeLove x Dunk Low SB QS 'Valentine's Day' released as part of a collaboration with Sean Cliver's skate brand. Dropping in February 2020, the upper is built with white crushed velvet, overlaid by pink suede and complemented by a red velvet Swoosh. The lateral heel sports Cliver's Heart Skull graphic, while underfoot, a series of red and blue hearts are visible through the translucent rubber outsole.",
        "url": "nike-sb-dunk-low-strangelove-skateboards-special-box",
        "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-strangelove-skateboards-special-box",
        "make": "Nike SB Dunk Low",
        "retailPrice": "100",
        "releaseDate": "2020-02-01"
    }
]

module.exports = nikeDunks;