const travis =
    [
        {
            "_id": "64d24327e50a880b29447fd7",
            "name": "Travis Scott x Jordan Flight Graphic Hoodie Archaeo Brown",
            "brand": "Travis Scott",
            "lowestResellPrice.stockX": "145",
            "image": "https://images.stockx.com/images/Travis-Scott-Cactus-Jack-x-Jordan-Flight-Graphic-Hoodie-Archaeo-Brown.jpg",
            "description": "The Travis Scott x Jordan Flight Graphic Hoodie Archaeo Brown was part of a Nike and musician Travis Scott collaboration honoring NBA player Michael Jordan. This garment  was made available in an all-brown colorway from 100% cotton fabric. It features kangaroo pockets with adjustable drawstrings on its hood. Additionally, the pullover sweater is embellished with miniature Cactus Jack and Jordan emblems on the chest. On its back and arms, there are Cactus Jack graphics, while a \"flight\" print adorns its medial back completing the design. The Travis Scott x Jordan Flight Graphic Hoodie Archaeo Brown debuted on December 15th, 2022 and retailed at $185.",
            "url": "travis-scott-cactus-jack-x-jordan-flight-graphic-hoodie-archaeo-brown",
            "resellLinks.stockX": "https://stockx.com/travis-scott-cactus-jack-x-jordan-flight-graphic-hoodie-archaeo-brown",
            "make": "Travis Scott x Jordan Flight Graphic",
            "retailPrice": "185",
            "releaseDate": "2022-12-15"
        },
        {
            "_id": "64d24327e50a880b29447fd8",
            "name": "Jordan 1 Retro Low OG SP Travis Scott Olive (Women's)",
            "brand": "Jordan",
            "lowestResellPrice.stockX": "341",
            "image": "https://images.stockx.com/images/Air-Jordan-1-Retro-Low-OG-SP-Travis-Scott-Olive-W-Product.jpg",
            "description": "The Travis Scott x Women's Air Jordan 1 Retro Low OG 'Olive' sneaker arrives exclusively in women's sizing. These sneakers feature off-white leather overlays against a sleek black suede base. A unique touch is added with the olive suede Swooshes which appear in reverse on one side and a classic design on the other. The muted earthy hues are brought to life with bold crimson accents and finished with Nike Air woven tongue tags and alternating Jordan and Cactus Jack branding on the heel tabs. The vintage off-white sidewalls and olive-green rubber outsole complete the look and provide a sturdy foundation atop the rubber cupsole.",
            "url": "air-jordan-1-retro-low-og-sp-travis-scott-olive-w",
            "resellLinks.stockX": "https://stockx.com/air-jordan-1-retro-low-og-sp-travis-scott-olive-w",
            "make": "Jordan 1 Retro Low OG SP",
            "retailPrice": "150",
            "releaseDate": "2023-04-26"
        },
        {
            "_id": "64d24327e50a880b29447fd9",
            "name": "Jordan 1 Retro Low OG SP Travis Scott Black Phantom",
            "brand": "Jordan",
            "lowestResellPrice.stockX": "403",
            "image": "https://images.stockx.com/images/Air-Jordan-1-Retro-Low-OG-SP-Travis-Scott-Black-Phantom-Product.jpg",
            "description": "The Travis Scott x Air Jordan 1 Low OG SP 'Black Phantom' sees the Houston-based rapper color up another AJ1 Low. This iteration features a blacked-out look, with nubuck and suede on the upper underscored by white contrast stitching throughout. Scott's signature reverse Swoosh remains, alongside a regular Swoosh on the medial side with Cactus Jack branding. The back heel features mismatched branding, with a Wings logo on the right shoe and a bee graphic on the left.",
            "url": "air-jordan-1-retro-low-og-sp-travis-scott-black-phantom",
            "resellLinks.stockX": "https://stockx.com/air-jordan-1-retro-low-og-sp-travis-scott-black-phantom",
            "make": "Jordan 1 Retro Low OG SP",
            "retailPrice": "150",
            "releaseDate": "2022-12-15"
        },
        {
            "_id": "64d24327e50a880b29447fda",
            "name": "Nike Air Force 1 Low '07 White (Travis Scott Cactus Jack Utopia Edition)",
            "brand": "Nike",
            "lowestResellPrice.stockX": "235",
            "image": "https://images.stockx.com/images/Nike-Air-Force-1-Low-07-White-Travis-Scott-Cactus-Jack-Utopia-Edition.jpg",
            "description": "Please note: by listing this item for sale, you agree to ship within the normal shipping window. Shipping deadlines will not be extended to accommodate shipping delays from the retailer.",
            "url": "nike-air-force-1-low-07-white-travis-scott-cactus-jack-utopia-edition",
            "resellLinks.stockX": "https://stockx.com/nike-air-force-1-low-07-white-travis-scott-cactus-jack-utopia-edition",
            "make": "Nike Air Force 1 Low '07",
            "retailPrice": "150",
            "releaseDate": "2023-07-28"
        },
        {
            "_id": "64d24327e50a880b29447fdb",
            "name": "Jordan 1 Retro Low OG SP Fragment x Travis Scott",
            "brand": "Jordan",
            "lowestResellPrice.stockX": "1000",
            "image": "https://images.stockx.com/images/Air-Jordan-1-Low-fragment-design-x-Travis-Scott-Product.jpg",
            "description": "The Fragment Design x Travis Scott x Air Jordan 1 Retro Low released as part of a collaboration with the Houston rapper and Japanese imprint. Featuring a colorway that recalls previous fragment design collaborations, the shoe's upper is built with a white leather base, overlaid by black and royal blue and complemented by inverted Swoosh branding on the lateral side. The heel patch of the left shoe includes Cactus Jack branding and a smiley face logo, while fragment's lightning bolt marks the right shoe. Underfoot, a two-tone rubber cupsole anchors the design.",
            "url": "air-jordan-1-low-fragment-design-x-travis-scott",
            "resellLinks.stockX": "https://stockx.com/air-jordan-1-low-fragment-design-x-travis-scott",
            "make": "Jordan 1 Retro Low OG SP",
            "retailPrice": "150",
            "releaseDate": "2021-08-13"
        },
        {
            "_id": "64d24327e50a880b29447fdc",
            "name": "Jordan 1 Retro Low OG SP Travis Scott Black Phantom (PS)",
            "brand": "Jordan",
            "lowestResellPrice.stockX": "129",
            "image": "https://images.stockx.com/images/Air-Jordan-1-Retro-Low-OG-SP-Travis-Scott-Black-Phantom-PS-Product.jpg",
            "description": "",
            "url": "air-jordan-1-retro-low-og-sp-travis-scott-black-phantom-ps",
            "resellLinks.stockX": "https://stockx.com/air-jordan-1-retro-low-og-sp-travis-scott-black-phantom-ps",
            "make": "Jordan 1 Retro Low OG SP",
            "retailPrice": "60",
            "releaseDate": "2022-12-15"
        },
        // {
        //     "_id": "64d24327e50a880b29447fdd",
        //     "name": "Jordan 1 Retro Low OG SP Travis Scott Reverse Mocha",
        //     "brand": "Jordan",
        //     "lowestResellPrice.stockX": "848",
        //     "image": "https://images.stockx.com/images/Air-Jordan-1-Retro-Low-OG-SP-Travis-Scott-Reverse-Mocha_V2-Product.jpg",
        //     "description": "Giving a remix on the original 'Mocha' AJ1 from 2019 is the Travis Scott x Air Jordan 1 Low from 2019. The upper features a brown suede base with ivory leather overlays and Scott's signature reverse Swoosh on the lateral side with oversized dimensions and a neutral cream finish. Contrasting scarlet accents distinguish a pair of woven Nike Air tongue tags and mismatched heel tabs with a Cactus Jack and retro Wings logos embroidered. It's built on an off-white rubber midsole with encapsulated Nike Air cushioning in the heel and a brown rubber outsole underfoot.",
        //     "url": "air-jordan-1-retro-low-og-sp-travis-scott-reverse-mocha",
        //     "resellLinks.stockX": "https://stockx.com/air-jordan-1-retro-low-og-sp-travis-scott-reverse-mocha",
        //     "make": "Jordan 1 Retro Low OG SP",
        //     "retailPrice": "150",
        //     "releaseDate": "2022-07-21"
        // },
        {
            "_id": "64d24327e50a880b29447fde",
            "name": "Jordan 1 Retro Low OG SP Travis Scott Olive (PS)",
            "brand": "Jordan",
            "lowestResellPrice.stockX": "145",
            "image": "https://images.stockx.com/images/Air-Jordan-1-Retro-Low-OG-SP-Travis-Scott-Olive-PS-Product.jpg",
            "description": "The Travis Scott x Air Jordan 1 Low OG PS 'Olive' is a shoe tailored for young children, showcasing a blend of muted hues and the rapper's personal style. The olive green cropped reverse Swoosh is the standout feature on the lateral side of the shoe, contrasting against the two-toned black suede and off-white leather upper. The woven Nike tongue tags and back tabs that showcase Cactus Jack and Jordan Wings branding have bright crimson accents. The long-lasting rubber cupsole is equipped with an olive green outsole and aged sidewalls, providing sturdy support underfoot.",
            "url": "air-jordan-1-retro-low-og-sp-travis-scott-olive-ps",
            "resellLinks.stockX": "https://stockx.com/air-jordan-1-retro-low-og-sp-travis-scott-olive-ps",
            "make": "Jordan 1 Retro Low OG SP",
            "retailPrice": "60",
            "releaseDate": "2023-04-26"
        },
        {
            "_id": "64d24327e50a880b29447fdf",
            "name": "Nike Air Max 1 Travis Scott Cactus Jack Saturn Gold",
            "brand": "Nike",
            "lowestResellPrice.stockX": "169",
            "image": "https://images.stockx.com/images/Nike-Air-Max-1-Travis-Scott-Wheat-Product.jpg",
            "description": "Travis Scott and Nike team up for an outdoor-inspired shoe in the Nike Air Max 1 'Saturn Gold.' It has a monochrome yellow palette throughout an upper crafted from breathable mesh with stitched leather overlays. It features two-tone rope laces and brown webbing straps that are integrated into the laces and heel overlay with mismatched Cactus Jack and Nike logos on each shoe. A rubber Cactus Jack patch is on the tongue with the rapper's trademark reverse Swoosh on the lateral side. The one-note finish extends to a wedge-shaped foam midsole with Air-sole cushioning in the heel and a waffle-tread rubber outsole underfoot.",
            "url": "nike-air-max-1-travis-scott-wheat",
            "resellLinks.stockX": "https://stockx.com/nike-air-max-1-travis-scott-wheat",
            "make": "Nike Air Max 1",
            "retailPrice": "150",
            "releaseDate": "2022-05-27"
        },
        {
            "_id": "64d24327e50a880b29447fe0",
            "name": "Nike Air Trainer 1 SP Travis Scott Grey Haze",
            "brand": "Nike",
            "lowestResellPrice.stockX": "90",
            "image": "https://images.stockx.com/images/Nike-Air-Trainer-1-SP-Travis-Scott-Grey-Haze-Product.jpg",
            "description": "Travis Scott works with Nike Sportswear on slight redesign of the classic Air Trainer 1. Replacing the traditional leather build and familiar panels, Scott opts for a textile finish in Grey Haze hue. 'Cactus Corporation' appears on the forefoot strap and back heel area, where a zippered stash pocket can be found. Scott's signature reverse Swoosh is found on the medial side, and Cactus Jack branding appears on the perforated nubuck tongue. Tiny holes can be found all over the upper, which are attachment points for a removable ripstop shroud (that can be stored in the pocket when not in use). Finally, the midsole shape stays the same, but the outsole traction is covered with rows of little nubs, forming a unique grippy pattern.",
            "url": "nike-air-trainer-1-sp-travis-scott-grey-haze",
            "resellLinks.stockX": "https://stockx.com/nike-air-trainer-1-sp-travis-scott-grey-haze",
            "make": "Nike Air Trainer 1 SP",
            "retailPrice": "160",
            "releaseDate": "2022-05-27"
        },
        {
            "_id": "64d24327e50a880b29447fe1",
            "name": "Jordan 1 Retro Low OG SP Travis Scott Olive (TD)",
            "brand": "Jordan",
            "lowestResellPrice.stockX": "139",
            "image": "https://images.stockx.com/images/Air-Jordan-1-Retro-Low-OG-SP-Travis-Scott-Olive-TD-Product.jpg",
            "description": "The Travis Scott x Air Jordan 1 Low OG TD 'Olive' presents a smaller iteration of the classic silhouette, with exclusive design elements that are now closely associated with the Houston rap artist. Its upper appears in black suede overlays in off-white leather accompanied by an opposite-facing olive green Swoosh. Adding contrast are woven Nike tongue tags and distinct heel tabs with Cactus Jack and Jordan Wings logos, all highlighted with bright crimson. The midsole is a vintage cream hue, while the olive rubber outsole provides stability and support.",
            "url": "air-jordan-1-retro-low-og-sp-travis-scott-olive-td",
            "resellLinks.stockX": "https://stockx.com/air-jordan-1-retro-low-og-sp-travis-scott-olive-td",
            "make": "Jordan 1 Retro Low OG SP",
            "retailPrice": "50",
            "releaseDate": "2023-04-26"
        },
        {
            "_id": "64d24327e50a880b29447fe2",
            "name": "Travis Scott x Jordan Paisley Shorts Orewood",
            "brand": "Travis Scott",
            "lowestResellPrice.stockX": "111",
            "image": "https://images.stockx.com/images/Travis-Scott-Cactus-Jack-x-Jordan-Paisley-Shorts-Orewood.jpg",
            "description": "The Travis Scott x Jordan Paisley Shorts Orewood comprises of Paisley pattern style make. This collaborative garment between American musician and Nike is made of a blend of cotton and polyester materials and features a contrast of black on its hems. The Paisley Shorts also have a ribbed waist, with multiple stitches. Additionally, an adjustable drawstring cords on its waist for fitting. The design is completed with paisley graphic and a black Jumpman logo near the waist and on its thighs. The Travis Scott x Jordan Paisley Shorts Orewood debuted in the market on December 15th, 2022, and retailed at $105.",
            "url": "travis-scott-cactus-jack-x-jordan-paisley-shorts-orewood",
            "resellLinks.stockX": "https://stockx.com/travis-scott-cactus-jack-x-jordan-paisley-shorts-orewood",
            "make": "Travis Scott x Jordan Paisley",
            "retailPrice": "105",
            "releaseDate": "2022-12-15"
        },
        {
            "_id": "64d24327e50a880b29447fe3",
            "name": "Nike Air Max 1 Travis Scott Cactus Jack Baroque Brown",
            "brand": "Nike",
            "lowestResellPrice.stockX": "220",
            "image": "https://images.stockx.com/images/Nike-Air-Max-1-Travis-Scott-Baroque-Brown-Product.jpg",
            "description": "The iconic runner gets a rugged outdoor-inspired makeover in the Travis Scott x Nike Air Max 1 'Baroque Brown.' Red hiker-style laces tie over a cream-colored mesh upper with dark tan leather overlays and a brown nubuck mudguard. The rapper's signature reverse Swoosh is on the lateral quarter panel in a Lemon Drop finish with multicolor woven straps that are integrated into the laces and heel overlay. The latter consists of a crimson triangular patch accompanied with Cactus Jack branding on the right shoe and the signature Nike logo is on the left. It's built on a two-tone foam midsole that's fitted with Air-sole cushioning in the heel and supported by a waffle-traction rubber outsole.",
            "url": "nike-air-max-1-travis-scott-baroque-brown",
            "resellLinks.stockX": "https://stockx.com/nike-air-max-1-travis-scott-baroque-brown",
            "make": "Nike Air Max 1",
            "retailPrice": "150",
            "releaseDate": "2022-05-27"
        },
        {
            "_id": "64d24327e50a880b29447fe4",
            "name": "Jordan 6 Retro Travis Scott British Khaki",
            "brand": "Jordan",
            "lowestResellPrice.stockX": "264",
            "image": "https://images.stockx.com/images/Air-Jordan-6-Retro-Travis-Scott-British-Khaki-Product.jpg",
            "description": "A follow-up to a 2019 collaboration, the Travis Scott x Air Jordan 6 Retro 'British Khaki' released with the help of the Houston rapper. Built with a mix of suede and canvas, the shoe's upper appears in British Khaki, highlighted by Bright Crimson on the heel pull-loop and tongue branding. The lateral collar includes a stash pouch, with the medial side sporting zippered detailing. The heels include mismatched Air and Cactus Jack branding, and underfoot, the usual visible Air in the heel provides cushioning.",
            "url": "air-jordan-6-retro-travis-scott-british-khaki",
            "resellLinks.stockX": "https://stockx.com/air-jordan-6-retro-travis-scott-british-khaki",
            "make": "Jordan 6 Retro",
            "retailPrice": "250",
            "releaseDate": "2021-04-30"
        },
        {
            "_id": "64d24327e50a880b29447fe5",
            "name": "Nike Air Trainer 1 SP Travis Scott Wheat",
            "brand": "Nike",
            "lowestResellPrice.stockX": "88",
            "image": "https://images.stockx.com/images/Nike-Air-Trainer-1-SP-Travis-Scott-Wheat-Product.jpg",
            "description": "Debuted as a cross-training shoe for use in multiple sports, the Air Trainer 1 has become a lifestyle staple. Originally designed by Tinker Hatfield, Travis Scott offers a unique take via altering key parts of the shoe. Textile and nubuck comprise the upper in Light Chocolate and Archaeo Brown, with Scott's signature reverse Swoosh appearing on the medial side of the shoe. 'Cactus Corporation' branding elements appear on the tongue and back heel counter, where a zippered stash pocket is found. The Houston rapper offers unique takes across the shoe, including a removable ripstop shroud that can be snapped onto the upper for protection against the elements, and a reworked outsole that feature rows of nubs for grippy traction.",
            "url": "nike-air-trainer-1-sp-travis-scott-wheat",
            "resellLinks.stockX": "https://stockx.com/nike-air-trainer-1-sp-travis-scott-wheat",
            "make": "Nike Air Trainer 1 SP",
            "retailPrice": "140",
            "releaseDate": "2022-05-27"
        },
        {
            "_id": "64d24327e50a880b29447fe6",
            "name": "Jordan 1 Retro Low OG SP Travis Scott Mocha",
            "brand": "Jordan",
            "lowestResellPrice.stockX": "1545",
            "image": "https://images.stockx.com/images/Air-Jordan-1-Retro-Low-Travis-Scott-Product.jpg",
            "description": "The Travis Scott x Air Jordan 1 Low 'Mocha' is the result of a collaboration between Jordan Brand and Travis Scott. The shoe's nubuck upper construction appears in black and Dark Mocha, accented by hits of University Red. The standout feature is the lateral-side Swoosh, which sports a backward application. A standard Swoosh appears on the medial side, while the tongue, medial quarter panel and sockliner include Cactus Jack branding. The heels sport a 'Wings' logo on the right shoe and Scott's crudely drawn face on the left to complete the collaborative look.",
            "url": "air-jordan-1-retro-low-travis-scott",
            "resellLinks.stockX": "https://stockx.com/air-jordan-1-retro-low-travis-scott",
            "make": "Jordan 1 Retro Low OG SP",
            "retailPrice": "130",
            "releaseDate": "2019-07-20"
        },
        {
            "_id": "64d24327e50a880b29447fe7",
            "name": "Jordan 1 Retro Low OG SP Travis Scott Black Phantom (TD)",
            "brand": "Jordan",
            "lowestResellPrice.stockX": "119",
            "image": "https://images.stockx.com/images/Air-Jordan-1-Retro-Low-OG-SP-Travis-Scott-Black-Phantom-TD-Product.jpg",
            "description": "",
            "url": "air-jordan-1-retro-low-og-sp-travis-scott-black-phantom-td",
            "resellLinks.stockX": "https://stockx.com/air-jordan-1-retro-low-og-sp-travis-scott-black-phantom-td",
            "make": "Jordan 1 Retro Low OG SP",
            "retailPrice": "50",
            "releaseDate": "2022-12-15"
        },
        {
            "_id": "64d24327e50a880b29447fe8",
            "name": "Jordan 6 Retro Travis Scott",
            "brand": "Jordan",
            "lowestResellPrice.stockX": "369",
            "image": "https://images.stockx.com/images/Air-Jordan-6-Retro-Travis-Scott-Product.jpg",
            "description": "The Travis Scott x Air Jordan 6 Retro 'Olive' showcases the Houston rapper’s unique take on the classic silhouette. Dressed in military green nubuck, the mid-top features a canvas stash pocket on the lateral collar and glow-in-the-dark translucent outsoles. The kicks are finished with Cactus Jack branding on the lace lock and heel embroidery of the right shoe, both rendered in a vibrant red hue.",
            "url": "air-jordan-6-retro-travis-scott",
            "resellLinks.stockX": "https://stockx.com/air-jordan-6-retro-travis-scott",
            "make": "Jordan 6 Retro",
            "retailPrice": "250",
            "releaseDate": "2019-10-11"
        },
        // {
        //     "_id": "64d24327e50a880b29447fe9",
        //     "name": "Jordan 1 Retro High OG SP Travis Scott Mocha",
        //     "brand": "Jordan",
        //     "lowestResellPrice.stockX": "1210",
        //     "image": "https://images.stockx.com/images/Air-Jordan-1-Retro-High-Travis-Scott-Product.jpg",
        //     "description": "A collaboration between Travis Scott and Jordan brand, the Travis Scott x Air Jordan 1 Retro High OG 'Mocha' features an oversized backward Swoosh on the lateral side. The tumbled white leather and Dark Mocha suede construction is accented by University Red Cactus Jack and Nike branding on the tongue, while the heel sports Scott's face logo in a debossed fashion.",
        //     "url": "air-jordan-1-retro-high-travis-scott",
        //     "resellLinks.stockX": "https://stockx.com/air-jordan-1-retro-high-travis-scott",
        //     "make": "Jordan 1 Retro High OG SP",
        //     "retailPrice": "175",
        //     "releaseDate": "2019-05-11"
        // },
        {
            "_id": "64d24327e50a880b29447fea",
            "name": "Nike Air Force 1 Low Travis Scott Cactus Jack",
            "brand": "Nike",
            "lowestResellPrice.stockX": "373",
            "image": "https://images.stockx.com/images/Nike-Air-Force-1-Low-Travis-Scott-Cactus-Jack-Product.jpg",
            "description": "The Travis Scott x Air Force 1 Low 'Cactus Jack' showcases a unique patchwork build on the upper, reflecting the Houston rapper’s upbringing and personal style. The rugged materials give the nod to traditional workwear, including a removable zippered overlay atop the tongue, while the various earth tones draw inspiration from the great outdoors. A gum rubber outsole anchors the eclectic design.",
            "url": "nike-air-force-1-low-travis-scott-cactus-jack",
            "resellLinks.stockX": "https://stockx.com/nike-air-force-1-low-travis-scott-cactus-jack",
            "make": "Nike Air Force 1 Low",
            "retailPrice": "160",
            "releaseDate": "2019-11-16"
        },
        {
            "_id": "64d24327e50a880b29447feb",
            "name": "Nike SB Dunk Low Travis Scott (Regular Box)",
            "brand": "Nike",
            "lowestResellPrice.stockX": "1020",
            "image": "https://images.stockx.com/images/Nike-SB-Dunk-Low-Travis-Scott-Product.jpg",
            "description": "Travis Scott teamed up with Nike to create the Travis Scott x SB Dunk Low PRM QS 'Cactus Jack.' Featuring a patchwork design, the shoe's upper emerges with a tan suede base accented by plaid on the quarter panel and paisley on the overlays. The overlays themselves are designed to wear away and reveal an elephant print, while the lateral side Swoosh sports a pink finish. Cactus Jack branding emerges on the tongue tag, while a rubber outsole is included for traction.",
            "url": "nike-sb-dunk-low-travis-scott",
            "resellLinks.stockX": "https://stockx.com/nike-sb-dunk-low-travis-scott",
            "make": "Nike SB Dunk Low",
            "retailPrice": "150",
            "releaseDate": "2020-02-29"
        },
        {
            "_id": "64d24327e50a880b29447fec",
            "name": "Nike Air Max 270 React ENG Travis Scott Cactus Trails",
            "brand": "Nike",
            "lowestResellPrice.stockX": "294",
            "image": "https://images.stockx.com/images/Nike-Air-Max-270-React-Travis-Scott-Product.jpg",
            "description": "A collaboration with the Houston rapper, the Travis Scott x Air Max 270 React 'Cactus Trails' emerges with a neutral colorway on its bold construction. The shoe's upper is built with textile, overlaid by tonal TPU, with brown nubuck at the toe. The heel sports Cactus Jack branding, while underfoot, the midsole incorporates a rough-hewn look. A 270 Max Air unit in the heel provides cushioning.",
            "url": "nike-air-max-270-react-travis-scott",
            "resellLinks.stockX": "https://stockx.com/nike-air-max-270-react-travis-scott",
            "make": "Nike Air Max 270 React ENG",
            "retailPrice": "170",
            "releaseDate": "2020-05-29"
        },
        {
            "_id": "64d24327e50a880b29447fed",
            "name": "Jordan 1 Retro Low OG SP Travis Scott Reverse Mocha (TD)",
            "brand": "Jordan",
            "lowestResellPrice.stockX": "180",
            "image": "https://images.stockx.com/images/Air-Jordan-1-Retro-Low-OG-SP-Travis-Scott-Reverse-Mocha-TD-Product.jpg",
            "description": "Maintaining an iconic Cactus Jack look is the Travis Scott x Air Jordan 1 Low OG TD ‘Reverse Mocha.' Echoing the 'Dark Mocha' Jordan 1 created in collaboration with the acclaimed rapper, the modern version features an upper in brown nubuck with overlays in off-white as background for an exaggerated and flipped Swoosh. Underfoot, an aged-looking midsole completes the heritage design. Branding adds red details on the Nike tongue tag and heel tabs alternating between signature Cactus Jack imagery on the left and Jordan Wings on the right.",
            "url": "air-jordan-1-retro-low-og-sp-travis-scott-reverse-mocha-td",
            "resellLinks.stockX": "https://stockx.com/air-jordan-1-retro-low-og-sp-travis-scott-reverse-mocha-td",
            "make": "Jordan 1 Retro Low OG SP",
            "retailPrice": "50",
            "releaseDate": "2022-07-21"
        },
        {
            "_id": "64d24327e50a880b29447fee",
            "name": "Jordan 4 Retro Travis Scott Cactus Jack",
            "brand": "Jordan",
            "lowestResellPrice.stockX": "799",
            "image": "https://images.stockx.com/images/Air-Jordan-4-Retro-Travis-Scott-Cactus-Jack-Product.jpg",
            "description": "The Travis Scott x Air Jordan 4 Retro 'Cactus Jack' honors the rapper’s hometown of Houston. Its palette borrows from the team colors of the city’s former Oilers football team, and features a Durabuck leather upper in University Blue, while its insole and branding are dressed in Varsity Red. Completing the look are a black lace cage and speckled light blue heel panel.",
            "url": "air-jordan-4-retro-travis-scott-cactus-jack",
            "resellLinks.stockX": "https://stockx.com/air-jordan-4-retro-travis-scott-cactus-jack",
            "make": "Jordan 4 Retro",
            "retailPrice": "225",
            "releaseDate": "2018-06-09"
        },
        {
            "_id": "64d24327e50a880b29447fef",
            "name": "Nike Air Max 1 Travis Scott Cactus Jack Wheat Lemon Drop",
            "brand": "Nike",
            "lowestResellPrice.stockX": "207",
            "image": "https://images.stockx.com/images/Nike-Air-Max-1-Travis-Scott-Wheat-Lemon-Drop-Product.jpg",
            "description": "The Travis Scott x Air Max 1 'Wheat' colorway is an exclusive release on the Houston rappers website. Modifying the design of the upper, Scott's take on the AM1 includes a Wheat mesh base with Baroque Brown nubuck overlays. Multicolor webbing straps connect a middle panel to the heel and lace area, while Scott's signature reverse Swoosh is seen on the lateral side profile. Cactus Jack branding can be found on the tongue, as well as a stitched pennant on the back heel. The classic AM1 visible Max Air unit remains intact, painted in to match the color of the midsole, while 'Cactus Corporation' is written on a revised waffle rubber outsole.",
            "url": "nike-air-max-1-travis-scott-wheat-lemon-drop",
            "resellLinks.stockX": "https://stockx.com/nike-air-max-1-travis-scott-wheat-lemon-drop",
            "make": "Nike Air Max 1",
            "retailPrice": "160",
            "releaseDate": "2022-05-23"
        },
        // {
        //     "_id": "64d24327e50a880b29447ff0",
        //     "name": "Jordan 1 Retro Low OG SP Travis Scott Reverse Mocha (PS)",
        //     "brand": "Jordan",
        //     "lowestResellPrice.stockX": "210",
        //     "image": "https://images.stockx.com/images/Air-Jordan-1-Retro-Low-OG-SP-Travis-Scott-Reverse-Mocha-PS-Product.jpg",
        //     "description": "The Travis Scott x Air Jordan 1 Low OG PS ‘Reverse Mocha’ renews a memorable color scheme with this version of the rapper's 2019 'Mocha.' Made for little kids, brown nubuck with leather overlays in off-white are accented on the upper by an exaggerated Swoosh in reverse. Branding pairs 'Nike Air' and Cactus Jack on the tongue, while the heel has the signature TS face sketch on the left and Jordan wings logo on the right, both in scarlet-red stitching. Underfoot, a brown rubber outsole enhances grip and traction beneath the midsole in an vintage-feel off-white.",
        //     "url": "air-jordan-1-retro-low-og-sp-travis-scott-reverse-mocha-ps",
        //     "resellLinks.stockX": "https://stockx.com/air-jordan-1-retro-low-og-sp-travis-scott-reverse-mocha-ps",
        //     "make": "Jordan 1 Retro Low OG SP",
        //     "retailPrice": "60",
        //     "releaseDate": "2022-07-21"
        // }
    ]
module.exports = travis