balenciProducts = [
    {
        "_id": "64c3566b3848d8e72c7972de",
        "name": "Balenciaga Track White Orange",
        "brand": "Balenciaga",
        "price": "180",
        "lowestResellPrice.stockX": "745",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-White-Orange-Product.jpg",
        "description": "The Balenciaga Track White Orange is a highly sought-after sneaker that was released on September 3, 2018, with a retail price of $1120. This shoe features a white and orange colorway that is eye-catching and unique. The upper is made of a combination of mesh, nylon, and rubber materials, which provide both durability and breathability. The shoe also features a chunky sole that is both comfortable and stylish. One of the standout features of the Balenciaga Track White Orange is its attention to detail. The shoe features a complex layering system that creates a dynamic and textured look. The orange accents on the shoe add a pop of color that makes it stand out from other sneakers on the market. Something we love about the Balenciaga Track White Orange is its ability to blend fashion and function seamlessly. The shoe is not only stylish but also comfortable and practical for everyday wear. Our experts think that the best features of this shoe are its unique design and attention to detail. If you're looking for a statement piece that will turn heads, the Balenciaga Track White Orange is the perfect choice.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-white-orange",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-white-orange",
        "make": "Balenciaga Track",
        "retailPrice": "1120",
        "metadata_": {
            "price": "205",
            "brand": "Balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-white-orange"
        },
        "releaseDate": "2018-09-03"
    },
    {
        "_id": "64c3566b3848d8e72c7972f9",
        "name": "Balenciaga Track LED Gray",
        "price": "205",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "968",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-LED-Gray.jpg",
        "description": "The Balenciaga Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-led-gray",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-led-gray",
        "make": "Balenciaga Track LED",
        "retailPrice": "1350",
        "metadata_": {
            "price": "205",
            "brand": "Balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-led-gray"
        },
        "releaseDate": "2018-09-24"
    },
    {
        "_id": "64c3566b3848d8e72c7972f5",
        "name": "Balenciaga Track Triple Grey",
        "price": "180",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "654",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Grey.jpg",
        "description": "The Balenciaga Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-triple-grey",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-triple-grey",
        "make": "Balenciaga Track",
        "retailPrice": "895",
        "metadata_": {
            "price": "205",
            "brand": "Balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-triple-grey"
        },
        "releaseDate": "2022-03-21"
    },
    {
        "_id": "64c3566b3848d8e72c7w54f2f5",
        "name": "Balenciaga Track LED Blue Yellow Black",
        "price": "205",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "1129",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Blue-Yellow-Black.jpg",
        "description": "Blue Yellow Black",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-blue-yellow-black",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-blue-yellow-black",
        "make": "Balenciaga Track",
        "retailPrice": "895",
        "metadata_": {
            "price": "205",
            "brand": "Balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-blue-yellow-black"
        },
        "releaseDate": "2022-03-21"
    },
    {
        "_id": "64c3566b3848d8e72c7972e8",
        "name": "Balenciaga Track Black Neon Yellow",
        "price": "180",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "835",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Black-Neon-Yellow-Product.jpg",
        "description": "The Balenciaga Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-black-neon-yellow",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-black-neon-yellow",
        "make": "Balenciaga Track",
        "retailPrice": "1050",
        "metadata_": {
            "price": "205",
            "brand": "Balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-black-neon-yellow"
        },
        "releaseDate": "2022-04-21"
    },
    {
        "_id": "64c3566b3848d8e72c7972e1",
        "name": "Balenciaga Track Trainer Red",
        "price": "180",
        "brand": "Balenciaga",
        "lowestResellPrice.stockX": "731",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Trainer-Red-Product.jpg",
        "description": "The Balenciaga Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-trainer-red",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-trainer-red",
        "make": "Balenciaga Track Trainer",
        "retailPrice": "895",
        "metadata_": {
            "price": "205",
            "brand": "Balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-trainer-red"
        },
        "releaseDate": "2022-03-22"
    },
    {
        "_id": "64c3566b3848d8e72c7972e0",
        "name": "Balenciaga Track Yellow",
        "brand": "Balenciaga",
        "price": "180",
        "lowestResellPrice.stockX": "690",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Yellow-Product.jpg",
        "description": "The Balenciaga Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-yellow",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-yellow",
        "make": "Balenciaga Track",
        "retailPrice": "1050",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-yellow"
        },
        "releaseDate": "2018-09-03"
    },
    {
        "_id": "64c3566b3848d8e72c7972e3",
        "name": "Balenciaga Track White",
        "brand": "Balenciaga",
        "price": "180",
        "lowestResellPrice.stockX": "706",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-White-Product.png",
        "description": "The Balenciaga Track White is a highly sought-after sneaker that combines style and functionality. Released in 2019, this shoe features a white mesh upper with synthetic overlays in shades of grey and black. The chunky sole is made of rubber and features a unique tread pattern that provides excellent traction on any surface. One of the standout features of the Balenciaga Track White is its attention to detail. The shoe is crafted from high-quality materials, including mesh, synthetic leather, and rubber, which ensures durability and longevity. The shoe's design is also highly functional, with a padded tongue and collar that provide comfort and support. At a retail price of $835, the Balenciaga Track White is a premium sneaker that is worth the investment. Its sleek design and high-quality construction make it a versatile shoe that can be worn with a variety of outfits. Something we love about Balenciaga Track White is its ability to seamlessly blend style and functionality. Our experts think that the shoe's attention to detail and high-quality materials are its best features. Whether you're hitting the gym or running errands, the Balenciaga Track White is a shoe that will keep you looking and feeling great.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-white",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-white",
        "make": "Balenciaga Track",
        "retailPrice": "835",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-white"
        },
        "releaseDate": "2019-01-01"
    },
    {
        "_id": "64c3566b3848d8e72c7972ea",
        "name": "Balenciaga Track White Blue",
        "brand": "Balenciaga",
        "price": "180",
        "lowestResellPrice.stockX": "676",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-White-Blue-Product.jpg",
        "description": "The Balenciaga Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-white-blue",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-white-blue",
        "make": "Balenciaga Track",
        "retailPrice": "995",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-white-blue"
        },
        "releaseDate": "2018-09-24"
    },
    {
        "_id": "64c3566b3848d8e72c7972eb",
        "name": "Balenciaga Track White Blue Green",
        "brand": "Balenciaga",
        "price": "180",
        "lowestResellPrice.stockX": "602",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-White-Blue-Green-Product.jpg",
        "description": "The Balenciaga Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-white-blue-green",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-white-blue-green",
        "make": "Balenciaga Track",
        "retailPrice": "995",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-white-blue-green"
        },
        "releaseDate": "2022-03-22"
    },
    {
        "_id": "64c3566b3848d8e72c7972ed",
        "name": "Balenciaga Track Faded Beige",
        "brand": "Balenciaga",
        "price": "180",
        "lowestResellPrice.stockX": "684",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Faded-Beige.png",
        "description": "The Balenciaga Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-faded-beige",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-faded-beige",
        "make": "Balenciaga Track Faded",
        "retailPrice": "1090",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-faded-beige"
        },
        "releaseDate": "2021-10-25"
    },
    {
        "_id": "64c3566b3848d8e72c7972ee",
        "name": "Balenciaga Track Black Grey Red",
        "brand": "Balenciaga",
        "price": "180",
        "lowestResellPrice.stockX": "724",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Black-Grey-Red-Product.jpg",
        "description": "The Balenciaga Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "balenciaga-track-black-grey-red",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-black-grey-red",
        "make": "Balenciaga Track",
        "retailPrice": "895",
        "metadata_": {
            "brand": "balenciaga",
            "category": "balenciaga",
            "collection": "balenciaga",
            "slug": "balenciaga-track-black-grey-red"
        },
        "releaseDate": "2019-01-01"
    },
]

module.exports = balenciProducts;