balenciProducts = [
    {
        "_id": "64c3566b3848d8e72c797306",
        "name": "Balenci Track Faded Pink (Women's)",
        "price": "180",
        "brand": "Balenci",
        "lowestResellPrice.stockX": "675",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Faded-Pink-W.png",
        "description": "The Balenci Track",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-faded-pink-w",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-faded-pink-w",
        "make": "Balenci Track Faded",
        "retailPrice": "1090",
        "metadata_": {
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-led-black"
        },
        "releaseDate": "2021-09-16"
    },
    {
        "_id": "64c3566b3848d8e72c797304",
        "name": "Balenci Track Clear Sole White/Black (Women's)",
        "brand": "Balenci",
        "price": "180",
        "lowestResellPrice.stockX": "690",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Clear-Sole-White-Black-W.jpg",
        "description": "The Balenci Track",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-clear-sole-white-black-w",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-clear-sole-white-black-w",
        "make": "Balenci Track Clear Sole",
        "retailPrice": "1090",
        "metadata_": {
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-led-black"
        },
        "releaseDate": "2018-09-24"
    },
    {
        "_id": "64c3566b3848d8e72c7972e4",
        "name": "Balenci Track LED Black",
        "brand": "Balenci",
        "lowestResellPrice.stockX": "988",
        "price": "180",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-LED-Black.jpg",
        "description": "Balenci Track LED!",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-led-black",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-led-black",
        "make": "Balenci Track LED",
        "retailPrice": "1305",
        "metadata_": {
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-led-black"
        },
        "releaseDate": "2021-11-04"
    },
    {
        "_id": "64c3566b3848d8e72c7972e5",
        "name": "Balenci Track Black",
        "brand": "Balenci",
        "lowestResellPrice.stockX": "870",
        "price": "180",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Black-2021-Product.jpg",
        "description": "Balenci Track!",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-black-2021",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-black-2021",
        "make": "Balenci Track",
        "retailPrice": "975",
        "metadata_": {
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-led-black"
        },
        "releaseDate": "2021-03-31"
    },
    {
        "_id": "64c3566b3848d8e72c7972de",
        "name": "Balenci Track White Orange",
        "brand": "Balenci",
        "price": "180",
        "lowestResellPrice.stockX": "745",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-White-Orange-Product.jpg",
        "description": "The Balenci Track White Orange is a highly sought-after sneaker that was released on September 3, 2018, with a retail price of $1120. This shoe features a white and orange colorway that is eye-catching and unique. The upper is made of a combination of mesh, nylon, and rubber materials, which provide both durability and breathability. The shoe also features a chunky sole that is both comfortable and stylish. One of the standout features of the Balenci Track White Orange is its attention to detail. The shoe features a complex layering system that creates a dynamic and textured look. The orange accents on the shoe add a pop of color that makes it stand out from other sneakers on the market. Something we love about the Balenci Track White Orange is its ability to blend fashion and function seamlessly. The shoe is not only stylish but also comfortable and practical for everyday wear. Our experts think that the best features of this shoe are its unique design and attention to detail. If you're looking for a statement piece that will turn heads, the Balenci Track White Orange is the perfect choice.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-white-orange",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-white-orange",
        "make": "Balenci Track",
        "retailPrice": "1120",
        "metadata_": {
            "price": "205",
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-white-orange"
        },
        "releaseDate": "2018-09-03"
    },
    {
        "_id": "64c3566b3848d8e72c7972f9",
        "name": "Balenci Track LED Gray",
        "price": "205",
        "brand": "Balenci",
        "lowestResellPrice.stockX": "968",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-LED-Gray.jpg",
        "description": "The Balenci Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-led-gray",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-led-gray",
        "make": "Balenci Track LED",
        "retailPrice": "1350",
        "metadata_": {
            "price": "205",
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-led-gray"
        },
        "releaseDate": "2018-09-24"
    },
    {
        "_id": "64c3566b3848d8e72c7972f5",
        "name": "Balenci Track Triple Grey",
        "price": "180",
        "brand": "Balenci",
        "lowestResellPrice.stockX": "654",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Grey.jpg",
        "description": "The Balenci Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-triple-grey",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-triple-grey",
        "make": "Balenci Track",
        "retailPrice": "895",
        "metadata_": {
            "price": "205",
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-triple-grey"
        },
        "releaseDate": "2022-03-21"
    },
    {
        "_id": "64c3566b3848d8e72c7w54f2f5",
        "name": "Balenci Track LED Blue Yellow Black",
        "price": "205",
        "brand": "Balenci",
        "lowestResellPrice.stockX": "1129",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Blue-Yellow-Black.jpg",
        "description": "Blue Yellow Black",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-blue-yellow-black",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-blue-yellow-black",
        "make": "Balenci Track",
        "retailPrice": "895",
        "metadata_": {
            "price": "205",
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-blue-yellow-black"
        },
        "releaseDate": "2022-03-21"
    },
    {
        "_id": "64c3566b3848d8e72c7972e8",
        "name": "Balenci Track Black Neon Yellow",
        "price": "180",
        "brand": "Balenci",
        "lowestResellPrice.stockX": "835",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Black-Neon-Yellow-Product.jpg",
        "description": "The Balenci Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-black-neon-yellow",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-black-neon-yellow",
        "make": "Balenci Track",
        "retailPrice": "1050",
        "metadata_": {
            "price": "205",
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-black-neon-yellow"
        },
        "releaseDate": "2022-04-21"
    },
    {
        "_id": "64c3566b3848d8e72c7972e1",
        "name": "Balenci Track Trainer Red",
        "price": "180",
        "brand": "Balenci",
        "lowestResellPrice.stockX": "731",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Trainer-Red-Product.jpg",
        "description": "The Balenci Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-trainer-red",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-trainer-red",
        "make": "Balenci Track Trainer",
        "retailPrice": "895",
        "metadata_": {
            "price": "205",
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-trainer-red"
        },
        "releaseDate": "2022-03-22"
    },
    {
        "_id": "64c3566b3848d8e72c7972e0",
        "name": "Balenci Track Yellow",
        "brand": "Balenci",
        "price": "180",
        "lowestResellPrice.stockX": "690",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Yellow-Product.jpg",
        "description": "The Balenci Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-yellow",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-yellow",
        "make": "Balenci Track",
        "retailPrice": "1050",
        "metadata_": {
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-yellow"
        },
        "releaseDate": "2018-09-03"
    },
    {
        "_id": "64c3566b3848d8e72c7972e3",
        "name": "Balenci Track White",
        "brand": "Balenci",
        "price": "180",
        "lowestResellPrice.stockX": "706",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-White-Product.png",
        "description": "The Balenci Track White is a highly sought-after sneaker that combines style and functionality. Released in 2019, this shoe features a white mesh upper with synthetic overlays in shades of grey and black. The chunky sole is made of rubber and features a unique tread pattern that provides excellent traction on any surface. One of the standout features of the Balenci Track White is its attention to detail. The shoe is crafted from high-quality materials, including mesh, synthetic leather, and rubber, which ensures durability and longevity. The shoe's design is also highly functional, with a padded tongue and collar that provide comfort and support. At a retail price of $835, the Balenci Track White is a premium sneaker that is worth the investment. Its sleek design and high-quality construction make it a versatile shoe that can be worn with a variety of outfits. Something we love about Balenci Track White is its ability to seamlessly blend style and functionality. Our experts think that the shoe's attention to detail and high-quality materials are its best features. Whether you're hitting the gym or running errands, the Balenci Track White is a shoe that will keep you looking and feeling great.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-white",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-white",
        "make": "Balenci Track",
        "retailPrice": "835",
        "metadata_": {
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-white"
        },
        "releaseDate": "2019-01-01"
    },
    {
        "_id": "64c3566b3848d8e72c7972ea",
        "name": "Balenci Track White Blue",
        "brand": "Balenci",
        "price": "180",
        "lowestResellPrice.stockX": "676",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-White-Blue-Product.jpg",
        "description": "The Balenci Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-white-blue",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-white-blue",
        "make": "Balenci Track",
        "retailPrice": "995",
        "metadata_": {
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-white-blue"
        },
        "releaseDate": "2018-09-24"
    },
    {
        "_id": "64c3566b3848d8e72c7972eb",
        "name": "Balenci Track White Blue Green",
        "brand": "Balenci",
        "price": "180",
        "lowestResellPrice.stockX": "602",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-White-Blue-Green-Product.jpg",
        "description": "The Balenci Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-white-blue-green",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-white-blue-green",
        "make": "Balenci Track",
        "retailPrice": "995",
        "metadata_": {
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-white-blue-green"
        },
        "releaseDate": "2022-03-22"
    },
    {
        "_id": "64c3566b3848d8e72c7972ed",
        "name": "Balenci Track Faded Beige",
        "brand": "Balenci",
        "price": "180",
        "lowestResellPrice.stockX": "684",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Faded-Beige.png",
        "description": "The Balenci Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-faded-beige",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-faded-beige",
        "make": "Balenci Track Faded",
        "retailPrice": "1090",
        "metadata_": {
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-faded-beige"
        },
        "releaseDate": "2021-10-25"
    },
    {
        "_id": "64c3566b3848d8e72c7972ee",
        "name": "Balenci Track Black Grey Red",
        "brand": "Balenci",
        "price": "180",
        "lowestResellPrice.stockX": "724",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/iaga-track/Balenciaga-Track-Black-Grey-Red-Product.jpg",
        "description": "The Balenci Track  is a highly sought-after sneaker that combines style and functionality.", "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "Balenci-track-black-grey-red",
        "resellLinks.stockX": "https://stockx.com/balenciaga-track-black-grey-red",
        "make": "Balenci Track",
        "retailPrice": "895",
        "metadata_": {
            "brand": "Balenci",
            "category": "Balenci",
            "collection": "track",
            "slug": "Balenci-track-black-grey-red"
        },
        "releaseDate": "2019-01-01"
    },
]

module.exports = balenciProducts;