const eybl = [
    {
        "_id": "64c3501cd5108ecc23fa0e42",
        "name": "Nike Air Zoom G.T. Cut EYBL Black",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "399",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Air-Zoom-GT-Cut-EYBL-Black.jpg",
        "description": "Premium S Tier Batch - Nike Air Zoom G.T. Cut EYBL Black",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-air-zoom-gt-cut-eybl-black",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-eybl-black",
        "make": "Nike Air Zoom G.T. Cut",
        "retailPrice": "140",
        "releaseDate": "2022-02-13",
        "metadata_": {
            "brand": "nike",
            "category": "gt",
            "collection": "eybl",
            "collection2": "gt",
            "slug": "nike-air-zoom-gt-cut-eybl-black",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e3e",
        "name": "Nike Kobe 5 Protro EYBL Girls (2020)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "360",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Kobe-5-Protro-EYBL-Forest-Green-2020-Product.jpg",
        "description": "Part of a collection that released for Mamba Week, the Zoom Kobe 5 Protro 'EYBL' dropped in August 2020. Inspired by Greek mythology, the shoe's synthetic upper includes a scaly texture modeled after Medusa. The left tongue sports an EYBL logo, with Kobe branding on the right shoe. The collar lining and heel accent the look, while underfoot, Zoom in the midsole provides cushioning.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-5-protro-eybl-forest-green-2020",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-5-protro-eybl-forest-green-2020",
        "retailPrice": "180",
        "releaseDate": "2020-08-29",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "eybl",
            "collection2": "kobe5",
            "slug": "nike-kobe-5-protro-eybl-forest-green-2020",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e41",
        "name": "Nike Kobe 6 Protro EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "2108",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/nike-kobe-6-protro-eybl.png",
        "description": "Premium S Tier Batch - Nike Kobe 6 Protro EYBL",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-6-protro-eybl",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-protro-eybl",
        "make": "Nike Kobe 6 Protro",
        "retailPrice": "225",
        "releaseDate": "2022-05-01",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "eybl",
            "collection2": "kobe6",
            "slug": "nike-kobe-6-protro-eybl",
        },
    },
    {
        "_id": "64c3501cd5108ecc23fa0e5d",
        "name": "Nike KD 12 NRG Peach Jam",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "292",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-KD-12-EYBL-Product.jpg",
        "description": "The Nike KD 12 NRG Peach Jam is a special-edition colorway of the NBA star Kevin Durant's 12th signature shoe with Nike.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kd-12-eybl",
        "resellLinks.stockX": "https://stockx.com/nike-kd-12-eybl",
        "retailPrice": "150",
        "releaseDate": "2019-07-13",
        "metadata_": {
            "brand": "nike",
            "category": "KD",
            "collection": "eybl",
            "slug": "nike-kd-12-eybl",
        },
    },
]

module.exports = eybl