const gtcuts = [
    {
        "_id": "64cf14d6f7204deafca94486",
        "name": "Nke Air Zoom G.T. Cut Ghost",
        "price": "135",
        "brand": "Nke",
        "lowestResellPrice.stockX": "347",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-Ghost.jpg",
        "description": "Premium S Tier Batch - Nke Air Zoom G.T. Cut Ghost",
        "url": "nke-air-zoom-gt-cut-ghost",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-ghost",
        "make": "NkeAir Zoom G.T. Cut",
        "retailPrice": "175",
        "metadata_": {
            "brand": "Nke",
            "category": "Nke",
            "collection": "gtcuts",
            "slug": "nke-air-zoom-gt-cut-ghost"
        },
        "releaseDate": "2022-04-06"
    },
    {
        "_id": "64c3501cd5108ecc23fa0e42",
        "name": "Nke Air Zoom G.T. Cut EYBL Black",
        "brand": "Nke",
        "price": "150",
        "lowestResellPrice.stockX": "399",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/Nike-Air-Zoom-GT-Cut-EYBL-Black.jpg",
        "description": "Premium S Tier Batch - Nke Air Zoom G.T. Cut EYBL Black",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nke-air-zoom-gt-cut-eybl-black",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-eybl-black",
        "make": "Nke Air Zoom G.T. Cut",
        "retailPrice": "140",
        "releaseDate": "2022-02-13",
        "metadata_": {
            "brand": "Nke",
            "category": "Nke",
            "collection": "gtcuts",
            "slug": "nke-air-zoom-gt-cut-eybl-black",
        },
    },
    {
        "_id": "64cf14d6f7204deafca94481",
        "name": "Nke Air Zoom G.T. Cut Black Crimson Green",
        "price": "135",
        "brand": "Nke",
        "lowestResellPrice.stockX": "292",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-Black-Crimson-Green-Product.jpg",
        "description": "Premium S Tier Batch - The Nke Air Zoom GT Cut Black Crimson Green was created with insights from WNBA point guard Sabrina Ionescu and NBA point guard De’Aaron Fox. The shoe was designed with comfort and stability in mind. The Nke Air Zoom GT Cut Black Crimson Green boasts a clean black base paired with open mesh weaves to enhance breathability. In addition, the nylon panels on the instep, tongue, and toe box add a bit of contrast to the design. The shoes also feature non-filled lateral Swooshes and branded heels that sit on a rubber outsole. This shoe, which comes in a black/hyper crimson/vapor green/ghost colorway was released on May 26, 2021, and retailed for $170.",
        "url": "nke-air-zoom-gt-cut-black-crimson-green",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-black-crimson-green",
        "make": "Nke Air Zoom G.T. Cut",
        "retailPrice": "170",
        "metadata_": {
            "brand": "Nke",
            "category": "Nke",
            "collection": "gtcuts",
            "slug": "nke-air-zoom-gt-cut-black-crimson-green"
        },
        "releaseDate": "2021-05-26"
    },
    {
        "_id": "64cf14d6f7204deafca9448a",
        "name": "Nke Air Zoom G.T. Cut White Black Laser Blue",
        "price": "135",
        "brand": "Nke",
        "lowestResellPrice.stockX": "380",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-White-Black-Laser-Blue-Product.jpg",
        "description": "Premium S Tier Batch - The Nke Air Zoom G.T. Cut White Black Laser Blue is a new running shoe released by Nike. The White Black Laser Blue Nke Air Zoom G.T. Cut features a white upper with black overlays, and Laser Blue detailing. The midsole has a Zoom Air sole unit that provides cushioning and support to the foot, and the Nke Swoosh is prominently displayed on the side of the shoe. We think that one of the key features of the Nke Air Zoom G.T. Cut is its lightweight construction which makes it a versatile shoe that can be used for different kinds of workouts, including running, training, and even casual wear. The shoe is composed of a breathable mesh upper and boasts a foam material provided by Nke called React foam, which is soft and yet responsive. This combination of materials reduces the overall weight of the shoe while providing maximum comfort to the wearer. The Nke Air Zoom G.T. Cut White Black Laser Blue was released on May 26, 2021 at a retail price of $170.",
        "url": "nke-air-zoom-gt-cut-white-black-laser-blue",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-white-black-laser-blue",
        "make": "Nke Air Zoom G.T. Cut",
        "retailPrice": "170",
        "metadata_": {
            "brand": "Nke",
            "category": "Nke",
            "collection": "gtcuts",
            "slug": "nke-air-zoom-gt-cut-white-black-laser-blue"
        },
        "releaseDate": "2021-05-26"
    },
    {
        "_id": "64cf14d6f7204deafca9448d",
        "name": "Nke Air Zoom G.T. Cut University Red White Yellow",
        "price": "135",
        "brand": "Nke",
        "lowestResellPrice.stockX": "506",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-University-Red-White-Yellow.jpg",
        "description": "Premium S Tier Batch - Nke Air Zoom G.T. Cut University Red White Yellow",
        "url": "nke-air-zoom-gt-cut-university-red-white-yellow",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-university-red-white-yellow",
        "make": "Nke Air Zoom G.T. Cut",
        "retailPrice": "170",
        "metadata_": {
            "brand": "Nke",
            "category": "Nke",
            "collection": "gtcuts",
            "slug": "nke-air-zoom-gt-cut-university-red-white-yellow"
        },
        "releaseDate": "2021-05-26"
    },
    {
        "_id": "64cf14d6f7204deafca94488",
        "name": "Nke Air Zoom G.T. Cut Think Pink",
        "price": "108",
        "brand": "Nke",
        "lowestResellPrice.stockX": "479",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-Think-Pink-Product.jpg",
        "description": "Nke Air Zoom G.T. Cut Think Pink",
        "url": "nke-air-zoom-gt-cut-think-pink",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-think-pink",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "make": "Nke Air Zoom G.T. Cut",
        "retailPrice": "170",
        "metadata_": {
            "brand": "Nke",
            "category": "Nke",
            "collection": "gtcuts",
            "slug": "nke-air-zoom-gt-cut-think-pink"
        },
        "releaseDate": "2022-02-22"
    },
    {
        "_id": "64cf14d6f7204deafca94485",
        "name": "Nke Air Zoom G.T. Cut Violet Crimson",
        "price": "108",
        "brand": "Nke",
        "lowestResellPrice.stockX": "175",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/gtcuts/Nike-Air-Zoom-GT-Cut-Violet-Crimson-Product.jpg",
        "description": "Nke Air Zoom G.T. Cut Violet Crimson",
        "url": "nke-air-zoom-gt-cut-violet-crimson",
        "resellLinks.stockX": "https://stockx.com/nike-air-zoom-gt-cut-violet-crimson",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "make": "Nke Air Zoom G.T. Cut",
        "retailPrice": "170",
        "metadata_": {
            "brand": "Nke",
            "category": "Nke",
            "collection": "gtcuts",
            "slug": "nke-air-zoom-gt-cut-violet-crimson"
        },
        "releaseDate": "2021-12-01"
    },
]

module.exports = gtcuts;