const kobe5Products = [
    {
        "_id": "64a323f989fa75170e1077d8",
        "name": "Nike Kobe 5 Dark Knight",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "527",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Dark-Knight.png",
        "description": "The Zoom Kobe 5 ‘Dark Knight’ shows off a subdued color scheme inspired by the 2008 Christopher Nolan film of the same name. The low-top’s black synthetic upper is accented with a heat-welded overlay in Neptune Blue, as well as a signature Swoosh outlined in white. A matching black and blue midsole packs Nike Zoom units in the heel and forefoot for lightweight cushioning.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "kobe-5-dark-knight",
        "resellLinks.stockX": "https://stockx.com/kobe-5-dark-knight",
        "make": "Nike Kobe 5",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe-5",
            "slug": "kobe-5-dark-knight"
        },
        "releaseDate": "2010-01-22"
    },
    {
        "_id": "64a323f989fa75170e1077bf",
        "name": "Nike Kobe 5 Protro Lakers",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "309",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Protro-Lakers-Product.png",
        "description": "Releasing for Mamba Week to celebrate Kobe Bryant's legacy, the Zoom Kobe 5 Protro '5x Champ' features inspiration from the championship jackets Bryant received after winning his second and third NBA titles. Built with patent leather, the upper sports a Los Angeles Lakers mix of Court Purple and University Gold, with black throughout. The custom sockliner sports an LA theme.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "nike-kobe-5-protro-lakers",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-5-protro-lakers",
        "make": "Nike Kobe 5",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe-5",
            "slug": "nike-kobe-5-protro-lakers",
        },
        "releaseDate": "2020-08-24"
    },
    {
        "_id": "64a323f989fa75170e1077e2",
        "name": "Nike Kobe 5 Joker (Chaos)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "529",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Chaos-Product.png",
        "description": "The Nike Zoom Kobe 5 ‘Chaos’ features a design inspired by Heath Ledger’s portrayal of the Joker in the second installment of Christopher Nolan’s Batman trilogy, The Dark Knight. The low-top’s synthetic upper is finished in a unique purple hue, contrasted by a neon green Swoosh and white heat-bonded overlays. A speckled phylon midsole in white is supported by a green rubber outsole.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "kobe-5-joker-chaos",
        "resellLinks.stockX": "https://stockx.com/kobe-5-joker-chaos",
        "make": "Nike Kobe 5",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe-5",
            "slug": "kobe-5-joker-chaos"
        },
        "releaseDate": "2009-12-26"
    },
    {
        "_id": "64a323f989fa75170e1077bd",
        "name": "Nike Kobe 5 Protro Bruce Lee Alternate",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "525",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Protro-Bruce-Lee-Alternate-Product.png",
        "description": "Drawing from a 2010 colorway, the Zoom Kobe 5 Protro 'Alternate Bruce Lee' released in November 2020. A more subdued colorway than its predecessor, the shoe's upper appears primarily in black and white, with Comet Red on the Swoosh outline and scratch marks at the forefoot. A touch of yellow highlights the heel and heel branding, while underfoot, the midsole incorporates Zoom Air in the forefoot.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "nike-kobe-5-protro-bruce-lee-alternate",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-5-protro-bruce-lee-alternate",
        "make": "Nike Kobe 5 Protro",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe-5",
            "slug": "nike-kobe-5-protro-bruce-lee-alternate",
        },
        "releaseDate": "2020-11-24"
    },
];


module.exports = kobe5Products;