kobe6product = [
    {
        "_id": "64a3210b5d8fce08b7d5d724",
        "name": "Nike Kobe 6 Protro Chaos",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/kobe-6-protro-chaos.png",
        "description": "Kobe Bryant",
        "url": "nike-kobe-6-protro-chaos",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-protro-chaos",
        "make": "Nike Kobe 6 Protro",
        "retailPrice": "190",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-chaos"
        },
        "releaseDate": ""
    },
    {
        "_id": "64a3210b5d8fce08b7d5d6fa",
        "name": "Nike Kobe 6 Protro Mambacita Sweet 16",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "570",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Protro-Mamba-Forever-Product.png",
        "description": "`Nike honors the legacy of Kobe Bryant and his daughter Gigi with the Kobe 6 Protro 'Mambacita Sweet Sixteen.' Black snake scales across the upper reference the Laker legend's Black Mamba alter ego, while the Swoosh, tongue logo and leather back panels are executed in white. A Mamba & Mambacita Sports Foundation crest appears in place of the traditional Kobe signature heel mold, with \"Kobe\" and \"Gigi\" printed on the left and right shoe, respectively. A gold \"2\" on the lateral window represents Gigi's AAU uniform number. The insole design pays further tribute to Gigi with an illustration that features a halo, angel wings, the nickname \"Mambacita\" and another \"2.\"\n`",
        "url": "nike-kobe-6-protro-mamba-forever",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-protro-mamba-forever",
        "make": "Nike Kobe 6 Protro",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-6-protro-mamba-forever"
        },
        "releaseDate": "2022-05-01"
    },
    {
        "_id": "64a3210b5d8fce08b7d5d6fe",
        "name": "Nike Kobe Protro 6 Think Pink",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "2999",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-Protro-6-Think-Pink-Product.png",
        "description": "Kobe Bryant",
        "url": "nike-kobe-protro-6-think-pink",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-protro-6-think-pink",
        "make": "Nike Kobe Protro 6",
        "retailPrice": "225",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe6",
            "slug": "nike-kobe-protro-6-think-pink"
        },
        "releaseDate": "2021-12-28"
    },
    {
        "_id": "64c3501cd5108ecc23fa0e41",
        "name": "Nike Kobe 6 Protro EYBL",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "2108",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/eybl/nike-kobe-6-protro-eybl.png",
        "description": "Premium S Tier Batch - Nike Kobe 6 Protro EYBL",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "url": "nike-kobe-6-protro-eybl",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-6-protro-eybl",
        "make": "Nike Kobe 6 Protro",
        "retailPrice": "225",
        "releaseDate": "2022-05-01",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe-6",
            // "collection2": "kobe6",
            "slug": "nike-kobe-6-protro-eybl",
        },
    },
]

module.exports = kobe6product;

// {
//     "_id": "64a3210b5d8fce08b7d5d713",
//     "name": "Nike Kobe 6 Draft Day",
//     "brand": "Nike",
//     "price": "150",
//     "lowestResellPrice.stockX": "700",
//     "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe6/Nike-Kobe-6-Draft-Day.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1617290549",
//     "description": "The Zoom Kobe 6 'Draft Day' gives the nod to the famous 1996 draft day trade that saw the Charlotte Hornets send the 13th overall pick to the Los Angeles Lakers in exchange for Vlade Divac. The Lakers would take Kobe Bryant, whose signature shoe appears here in the colors of the team that didn't draft him. The shoe's white snakeskin-textured upper sports a Varsity Purple Swoosh and laces, with Photo Blue on the heel counter, lining and midsole to complete the team look.",
//     "url": "kobe-6-draft-day",
//     "currency": "USD",
//     "shippable": true,
//     "statement_descriptor": "PRIME ORCA LLC",
//     "resellLinks.stockX": "https://stockx.com/kobe-6-draft-day",
//     "make": "Nike Kobe 6",
//     "retailPrice": "130",
//     "metadata_": {
//         "brand": "nike",
//         "category": "kobe",
//         "collection": "kobe6",
//         "slug": "kobe-6-draft-day"
//     },
//     "releaseDate": "2011-05-26"
// },