const kobe5Products = [

    {
        "_id": "64a323f989fa75170e1077c5",
        "name": "Nike Kobe 5 Bruce Lee",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "800",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Bruce-Lee-Product.png",
        "description": "The Zoom Kobe 5 'Bruce Lee,' like several other Kobe silhouettes, pays tribute to Bruce Lee. The black and yellow look gives the nod to two of Lee's iconic films, with the colorway itself inspired by the jumpsuit Lee wore in Game of Death, while the red scratch-mark detailing recalls the final fight scene from Enter the Dragon.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "kobe-5-bruce-lee",
        "resellLinks.stockX": "https://stockx.com/kobe-5-bruce-lee",
        "make": "Nike Kobe 5",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe5",
            "slug": "kobe-5-bruce-lee",
        },
        "releaseDate": "2010-02-06"
    },
    {
        "_id": "64a323f989fa75170e1077c3",
        "name": "Nike Kobe 5 Protro PJ Tucker",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "740",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Protro-PJ-Tucker.png",
        "description": "The P.J. Tucker x Zoom Kobe 5 Protro PE is a special colorway made for the NBA player. The shoe's upper is built with lightweight synthetic, complemented by tonal animal prints throughout. Flywire cables support the fit, while red mesh on the collar accents the design. Kobe Bryant's signature marks the heel counter, and the Swoosh branding includes a dot matrix-style design.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "nike-kobe-5-protro-pj-tucker",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-5-protro-pj-tucker",
        "make": "Nike Kobe 5 Protro",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe5",
            "slug": "nike-kobe-5-protro-pj-tucker",
        },
        "releaseDate": "2020-09-25"
    },
    {
        "_id": "64a323f989fa75170e1077bc",
        "name": "Nike Kobe 5 Protro 2K Gamer Exclusive",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1099",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Protro-2K-Gamer-Exclusive-Product.png",
        "description": "Made available for purchase to players who completed an in-game challege in NBA 2K20, the NBA 2K20 x Kobe 5 Protro 'Chaos Alternate' Gamer Exclusive updates the Kobe 5 'Chaos.' The shoe's upper appears largely similar to its predecessor, although the grey overlays replace the former's white finish. Flywrie cables support the fit, while Volt and iridescent purple accent the look throughout. Underfoot, Air Zoom Turbo provides cushioning.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "nike-kobe-5-protro-2k-gamer-exclusive",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-5-protro-2k-gamer-exclusive",
        "make": "Nike Kobe 5 Protro",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe5",
            "slug": "nike-kobe-5-protro-2k-gamer-exclusive",
        },
        "releaseDate": "2019-12-26"
    },
    {
        "_id": "64a323f989fa75170e1077d2",
        "name": "Nike Kobe 5 USA",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1269",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-USA.png",
        "description": "The Zoom Kobe 5 'USA' is a performance basketball shoe with a patriotic look. The shoe's upper features a synthetic construction, finished in white and highlighted by Obsidian and Sport Red throughout. Heat-bonded overlays support the fit, with Flywire cables securing the design. Underfoot, an injection-molded phylon midsole houses Zoom Air for cushioning, working with a carbon-fiber weave shank to provide stability.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "nike-kobe-5-usa",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-5-usa",
        "make": "Nike Kobe 5",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe5",
            "slug": "nike-kobe-5-usa"
        },
        "releaseDate": "2010-08-06"
    },
    {
        "_id": "64a323f989fa75170e1077d5",
        "name": "Nike Kobe 5 5 Rings (2010)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "525",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Kobe-5-5-Rings-Product.png",
        "description": "The Zoom Kobe 5 'Rings' celebrates Kobe Bryant's fifth NBA title with the Los Angeles Lakers. The shoe's upper appears primarily in purple, accented by various graphics giving the nod to the accomplishment, including hits of Midwest Gold at the forefoot. More Midwest Gold emerges on the branding, while Zoom Air underfoot provides cushioning.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "kobe-5-5-rings",
        "resellLinks.stockX": "https://stockx.com/kobe-5-5-rings",
        "make": "Nike Kobe 5",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "kobe",
            "collection": "kobe5",
            "slug": "kobe-5-5-rings"
        },
        "releaseDate": "2010-10-15"
    },
];


module.exports = kobe5Products;