const kobe5Products = [
    {
        "_id": "64a323f989fa75170e1077d8",
        "name": "Nike KB 5 Dark Knight",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "527",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Dark-Knight.png",
        "description": "The Zoom KB 5 ‘Dark Knight’ shows off a subdued color scheme inspired by the 2008 Christopher Nolan film of the same name. The low-top’s black synthetic upper is accented with a heat-welded overlay in Neptune Blue, as well as a signature Swoosh outlined in white. A matching black and blue midsole packs Nike Zoom units in the heel and forefoot for lightweight cushioning.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "KB-5-dark-knight",
        "resellLinks.stockX": "https://stockx.com/kobe-5-dark-knight",
        "make": "Nike KB 5",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "KB",
            "collection": "KB-5",
            "slug": "KB-5-dark-knight"
        },
        "releaseDate": "2010-01-22"
    },
    {
        "_id": "64a323f989fa75170e1077bf",
        "name": "Nike KB 5 Protro Lakers",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "309",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Protro-Lakers-Product.png",
        "description": "Releasing for Mamba Week to celebrate KB Bryant's legacy, the Zoom KB 5 Protro '5x Champ' features inspiration from the championship jackets Bryant received after winning his second and third NBA titles. Built with patent leather, the upper sports a Los Angeles Lakers mix of Court Purple and University Gold, with black throughout. The custom sockliner sports an LA theme.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "nike-KB-5-protro-lakers",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-5-protro-lakers",
        "make": "Nike KB 5",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "KB",
            "collection": "KB-5",
            "slug": "nike-KB-5-protro-lakers",
        },
        "releaseDate": "2020-08-24"
    },
    {
        "_id": "64a323f989fa75170e1077e2",
        "name": "Nike KB 5 Joker (Chaos)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "529",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Chaos-Product.png",
        "description": "The Nike Zoom KB 5 ‘Chaos’ features a design inspired by Heath Ledger’s portrayal of the Joker in the second installment of Christopher Nolan’s Batman trilogy, The Dark Knight. The low-top’s synthetic upper is finished in a unique purple hue, contrasted by a neon green Swoosh and white heat-bonded overlays. A speckled phylon midsole in white is supported by a green rubber outsole.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "KB-5-joker-chaos",
        "resellLinks.stockX": "https://stockx.com/kobe-5-joker-chaos",
        "make": "Nike KB 5",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "KB",
            "collection": "KB-5",
            "slug": "KB-5-joker-chaos"
        },
        "releaseDate": "2009-12-26"
    },
    {
        "_id": "64a323f989fa75170e1077bd",
        "name": "Nike KB 5 Protro Bruce Lee Alternate",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "525",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Protro-Bruce-Lee-Alternate-Product.png",
        "description": "Drawing from a 2010 colorway, the Zoom KB 5 Protro 'Alternate Bruce Lee' released in November 2020. A more subdued colorway than its predecessor, the shoe's upper appears primarily in black and white, with Comet Red on the Swoosh outline and scratch marks at the forefoot. A touch of yellow highlights the heel and heel branding, while underfoot, the midsole incorporates Zoom Air in the forefoot.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "nike-KB-5-protro-bruce-lee-alternate",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-5-protro-bruce-lee-alternate",
        "make": "Nike KB 5 Protro",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "KB",
            "collection": "KB-5",
            "slug": "nike-KB-5-protro-bruce-lee-alternate",
        },
        "releaseDate": "2020-11-24"
    },
    {
        "_id": "64a323f989fa75170e1077c5",
        "name": "Nike KB 5 Bruce Lee",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "800",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Bruce-Lee-Product.png",
        "description": "The Zoom KB 5 'Bruce Lee,' like several other KB silhouettes, pays tribute to Bruce Lee. The black and yellow look gives the nod to two of Lee's iconic films, with the colorway itself inspired by the jumpsuit Lee wore in Game of Death, while the red scratch-mark detailing recalls the final fight scene from Enter the Dragon.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "KB-5-bruce-lee",
        "resellLinks.stockX": "https://stockx.com/kobe-5-bruce-lee",
        "make": "Nike KB 5",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "KB",
            "collection": "KB-5",
            "slug": "KB-5-bruce-lee",
        },
        "releaseDate": "2010-02-06"
    },
    {
        "_id": "64a323f989fa75170e1077c3",
        "name": "Nike KB 5 Protro PJ Tucker",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "740",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Protro-PJ-Tucker.png",
        "description": "The P.J. Tucker x Zoom KB 5 Protro PE is a special colorway made for the NBA player. The shoe's upper is built with lightweight synthetic, complemented by tonal animal prints throughout. Flywire cables support the fit, while red mesh on the collar accents the design. KB Bryant's signature marks the heel counter, and the Swoosh branding includes a dot matrix-style design.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "nike-KB-5-protro-pj-tucker",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-5-protro-pj-tucker",
        "make": "Nike KB 5 Protro",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "KB",
            "collection": "KB-5",
            "slug": "nike-KB-5-protro-pj-tucker",
        },
        "releaseDate": "2020-09-25"
    },
    {
        "_id": "64a323f989fa75170e1077bc",
        "name": "Nike KB 5 Protro 2K Gamer Exclusive",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1099",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-Protro-2K-Gamer-Exclusive-Product.png",
        "description": "Made available for purchase to players who completed an in-game challege in NBA 2K20, the NBA 2K20 x KB 5 Protro 'Chaos Alternate' Gamer Exclusive updates the KB 5 'Chaos.' The shoe's upper appears largely similar to its predecessor, although the grey overlays replace the former's white finish. Flywrie cables support the fit, while Volt and iridescent purple accent the look throughout. Underfoot, Air Zoom Turbo provides cushioning.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "nike-KB-5-protro-2k-gamer-exclusive",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-5-protro-2k-gamer-exclusive",
        "make": "Nike KB 5 Protro",
        "retailPrice": "180",
        "metadata_": {
            "brand": "nike",
            "category": "KB",
            "collection": "KB-5",
            "slug": "nike-KB-5-protro-2k-gamer-exclusive",
        },
        "releaseDate": "2019-12-26"
    },
    {
        "_id": "64a323f989fa75170e1077d2",
        "name": "Nike KB 5 USA",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "1269",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Nike-Kobe-5-USA.png",
        "description": "The Zoom KB 5 'USA' is a performance basketball shoe with a patriotic look. The shoe's upper features a synthetic construction, finished in white and highlighted by Obsidian and Sport Red throughout. Heat-bonded overlays support the fit, with Flywire cables securing the design. Underfoot, an injection-molded phylon midsole houses Zoom Air for cushioning, working with a carbon-fiber weave shank to provide stability.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "nike-KB-5-usa",
        "resellLinks.stockX": "https://stockx.com/nike-kobe-5-usa",
        "make": "Nike KB 5",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "KB",
            "collection": "KB-5",
            "slug": "nike-KB-5-usa"
        },
        "releaseDate": "2010-08-06"
    },
    {
        "_id": "64a323f989fa75170e1077d5",
        "name": "Nike KB 5 5 Rings (2010)",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "525",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/Kobe-5-5-Rings-Product.png",
        "description": "The Zoom KB 5 'Rings' celebrates KB Bryant's fifth NBA title with the Los Angeles Lakers. The shoe's upper appears primarily in purple, accented by various graphics giving the nod to the accomplishment, including hits of Midwest Gold at the forefoot. More Midwest Gold emerges on the branding, while Zoom Air underfoot provides cushioning.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "KB-5-5-rings",
        "resellLinks.stockX": "https://stockx.com/kobe-5-5-rings",
        "make": "Nike KB 5",
        "retailPrice": "130",
        "metadata_": {
            "brand": "nike",
            "category": "KB",
            "collection": "KB-5",
            "slug": "KB-5-5-rings"
        },
        "releaseDate": "2010-10-15"
    },
    {
        "_id": "64a323f989fa75170e1077d8",
        "name": "KB 5 x Off White",
        "brand": "Nike",
        "price": "150",
        "lowestResellPrice.stockX": "10000",
        "image": "https://po-prod.s3.us-west-1.amazonaws.com/kobe5/kobe-5-off-white.jpg",
        "description": "KB 5 x Off White collab.",
        "currency": "USD",
        "shippable": true,
        "statement_descriptor": "PRIME ORCA LLC",
        "colorway": "Metallic Gold/Field Purple-Multi-Color",
        "url": "KB-5-off-white",
        "resellLinks.stockX": "https://stockx.com/",
        "make": "Nike KB 5",
        "retailPrice": "999",
        "metadata_": {
            "brand": "nike",
            "category": "KB",
            "collection": "KB5",
            "slug": "KB-5-off-white"
        },
        "releaseDate": "2010-01-22"
    },
];


module.exports = kobe5Products;